dogtagpki/jss

- org/mozilla/jss/pkcs11/PK11KeyWrapper.java
NSS identifies RSA private keys by setting the PKCS #11 CKA_ID
attribute to the SHA-1 digest of the public key (modulus).
PK11KeyWrapper can receive this modulus value (a byte[]) with a
leading null byte.  This results in the digest (CKA_ID) not matching
what the rest of NSS expects, e.g. when adding the corresponding
certificate, NSS fails to associate it with the private key, because
it is looking for a different CKA_ID.
This results in Dogtag lightweight CA key replication failures.
Apparently the problem did not occur with the old DB backend, only
with the new SQL backend.  Or there was some other change in NSS
that landed in Fedora 28, which prompted this issue.  In either
case, the resolve the problem by dropping the leading null byte from
the modulus byte[].
Fixes: …
> Strip leading null byte from public key when unwrapping key

- build.sh
- jss.spec.in
A new build script has been added to simplify the build process.
Documentation is available here:
http://www.dogtagpki.org/wiki/JSS_4.4.5_Development
> Added build.sh

- README
README instructions still used mercurial for updating the repository and tagging new releases. It appears that the new standard for tags/branches is `v<major>.<minor>.<patch>`, so perhaps all of section 7 should be updated. I left the ids/versions/tag messages untouched to minimize changes.
> Updated README instructions for git

- org/mozilla/jss/provider/java/security/JSSKeyStoreSpi.java
- org/mozilla/jss/provider/java/security/JSSLoadStoreParameter.java
The JSSKeyStoreSpi.engineLoad() has been modified to store the
token provided via JSSLoadStoreParameter in the keystore. The
token later will be used to execute various operations in the
keystore (i.e. retrieving certs and keys from the token).
https://pagure.io/jss/issue/10
> Fixed JSSKeyStoreSpi.engineLoad()

- org/mozilla/jss/provider/java/security/JSSKeyStoreSpi.java
The JSSKeyStoreSpi.engineGetKey() has been rewritten in Java to
search for a private key by its cert. If that is not found, it
will search for a private key by its key ID. If that is not found
either, it will search for a symmetric key by its nickname.
https://pagure.io/jss/issue/10
> Fixed JSSKeyStoreSpi.engineGetKey()

- lib/jss.def
- org/mozilla/jss/pkcs11/PK11KeyWrapper.java
- org/mozilla/jss/pkcs11/PK11Token.c
- org/mozilla/jss/pkcs11/PK11Token.java
The NSS SQL backend, unlike the DBM backend that preceded it, does
not automatically create PKCS #11 public key objects when unwrapping
private keys.  When certificates are added, this can result in a
failure to properly associate the certificate with a private key in
the token.
When unwrapping a private key, if the given public key wraps an NSS
SECKEYPublicKey object, import the public key to the token as well.
Change-Id: I146952382d535ad71d9914f3a43d7df5c0a0f510
Related: https://pagure.io/jss/issue/13
> Import public key when unwrapping private key

- .classpath
- org/mozilla/jss/netscape/security/acl/AclEntryImpl.java
- org/mozilla/jss/netscape/security/acl/AclImpl.java
- org/mozilla/jss/netscape/security/acl/AllPermissionsImpl.java
- org/mozilla/jss/netscape/security/acl/GroupImpl.java
- org/mozilla/jss/netscape/security/acl/OwnerImpl.java
- org/mozilla/jss/netscape/security/acl/PermissionImpl.java
- org/mozilla/jss/netscape/security/acl/PrincipalImpl.java
- org/mozilla/jss/netscape/security/acl/WorldGroupImpl.java
Some classes in org/mozilla/jss/netscape/security/acl folder have
been modified to use the correct package.
The Eclipse .classpath has been fixed to remove some build errors.
https://bugzilla.redhat.com/show_bug.cgi?id=1560682
> Fixed package declarations

- lib/jss.def
- org/mozilla/jss/crypto/CryptoStore.java
- org/mozilla/jss/pkcs11/PK11Store.c
- org/mozilla/jss/pkcs11/PK11Store.java
- org/mozilla/jss/provider/java/security/JSSKeyStoreSpi.java
Updated JSSKeyStoreSpi.engineDeleteEntry()
The JSSKeyStoreSpi.engineDeleteEntry() has been modified such that:
* if the given alias is a cert nickname, it will delete the cert without deleting the public and private keys
* if the given alias is a key ID, it will delete the public and private keys without deleting the cert
> Updated JSSKeyStoreSpi.engineDeleteEntry()

- build_java.pl
- org/mozilla/jss/tests/all.pl
On debian the paths to various jar files are different than fedora and other Linux distros.
Prior to building do export DEBIAN_BUILD in addition to the other required exports
Also add support the option to add -Xlint:deprecation
Do export CHECK_DEPRECATION=1 to activate the feature
Related: https://pagure.io/jss/issue/14
> Add support for debian builds and tests

- coreconf/Linux.mk
This one line change gets rid of all those warnings.
> Deprecated bsd source and svid source warnings

- build_java.pl
For https://pagure.io/jss/issue/18
> duplicate name in manifest warnings

- README.md
I noticed that dependency information was missing from the README and thought it was useful to add.
On Fedora, there's also the `dnf builddep jss`, but I'm not sure if that'd be desired instead of the explicit command.
Interestingly, `dnf builddep jss` fails to pull in `zlib-devel`, as it is missing from the spec file. However, without `zlib-devel`, `nss` fails to build. This is only required if building with (1)(a) instructions though.
> Reflect dependencies in README

- Makefile
- rules.mk
A common pattern across projects is to use `make check` to execute
tests, `make dist` to build a release, and `make distclean` to
clean the tree after a release. This adds targets to `rules.mk`
which support these targets and moves a target from the `Makefile`
to `rules.mk`.
This help aligns the project with the GNU coding standards: https://www.gnu.org/prep/standards/html_node/Standard-Targets.html
Signed-off-by: Alexander Scheel <ascheel@redhat.com>
> Align jss with make standard targets

- build_java.pl
- tools/test_perl_style.sh
A few improvements to the `build_java.pl` script: 
- Linting it with Perl `-Mstrict` flag
- New tool introduced in `tools/check_perl_style.sh` to validate this.
- Remove the unnecessary `eval` just to call a function inside the script.
- Removed the logic around appending to manifest.
- Simplified the logic around the test suite to avoid nested `if` statements.
(The `B::Lint` module was giving what I believe to be a false positive and wouldn't install cleanly from `cpan` so I decided against it). 
The second change introduces a hash to map `name->subroutine`; this would need to be kept in sync if more commands are introduced, but I don't think this is likely. Secondly, it drops passing `ARGV` into the function. This would be easy to add, but I don't believe any of the functions use this …
> build_java.pl improvements

- org/mozilla/jss/CryptoManager.java
- org/mozilla/jss/crypto/Algorithm.java
- org/mozilla/jss/crypto/BadPaddingException.java
- org/mozilla/jss/crypto/EncryptionAlgorithm.java
- org/mozilla/jss/crypto/PBEKeyGenParams.java
- org/mozilla/jss/crypto/PrivateKey.java
- org/mozilla/jss/crypto/TokenCertificate.java
- org/mozilla/jss/netscape/security/acl/AclEntryImpl.java
- org/mozilla/jss/netscape/security/acl/AclImpl.java
- org/mozilla/jss/netscape/security/acl/GroupImpl.java
- org/mozilla/jss/netscape/security/acl/OwnerImpl.java
- org/mozilla/jss/netscape/security/acl/WorldGroupImpl.java
- org/mozilla/jss/netscape/security/provider/DSA.java
- org/mozilla/jss/netscape/security/x509/AlgorithmId.java
- org/mozilla/jss/netscape/security/x509/CertAndKeyGen.java
- org/mozilla/jss/netscape/security/x509/X509Cert.java
- org/mozilla/jss/pkcs11/KeyType.java
- org/mozilla/jss/pkcs11/PK11Cipher.java
- org/mozilla/jss/pkcs11/PK11PubKey.java
- org/mozilla/jss/pkix/cmc/RevokeRequest.java
- org/mozilla/jss/pkix/cmmf/RevRequest.java
- org/mozilla/jss/provider/javax/crypto/JSSKeyGeneratorSpi.java
- org/mozilla/jss/provider/javax/crypto/JSSSecretKeyFactorySpi.java
- org/mozilla/jss/ssl/SSLSecurityStatus.java
- org/mozilla/jss/ssl/SSLServerSocket.java
- org/mozilla/jss/ssl/SSLSocket.java
- org/mozilla/jss/tests/Constants.java
- org/mozilla/jss/util/NativeErrcodes.java
- org/mozilla/jss/util/NativeProxy.java
- org/mozilla/jss/util/Password.java
Addresses https://pagure.io/jss/issue/19
Replaces the previous pull request
https://github.com/emaldona/jss/commit/5305574fc02f655d99615c757d4bedbdee5cfdf8
that failed tests.
> Complete deprecation annotations already started

- org/mozilla/jss/tests/all.pl
- tools/test_perl_style.sh
- Address https://pagure.io/jss/issue/23
- perl -Mstrict -Mdiagnostics -cw org/mozilla/jss/tests/all.pl
- now shows org/mozilla/jss/tests/all.pl syntax OK
> Cleanup all.pl to address test_perl_style.sh tool messages

- build.sh
- tools/test_shell_style.sh
This PR does two things:
- Improves the quality of the `build.sh` script
- Adds a style checker (`shellcheck`) to the repository that validates shell scripts.
Most of the issues found were minor style nits; a later PR might refactor the build script.
> shellcheck build.sh

- docs/build_system.md
- docs/ci.md
- docs/gh_pages.md
- docs/using_jss.md
This is the initial step in improving documentation about JSS. In particular, this PR documents two aspects:
- The build system and the various parts of it. It will be expanded as more information is acquired.
- Using JSS in an external project. This documents the CLASSPATH dependencies of JSS.
The latter is important as [389-console](https://pagure.io/389-console) appears to be using JSS [without including `slf4j-api.jar` in the classpath](https://pagure.io/389-console/blob/master/f/build.xml#_39).
> Add documentation about JSS

- README.md
- docs/repo_archive.md
In conjunction with https://pagure.io/jss/issue/25, proposed documentation for using the `jss-archive` repository.
> Document branches in upstream [skip ci]

- build_java.pl
This prevents reproducible builds for the `jss-javadoc` sub-package; in particular, any compilation at a slightly different time will produce javadocs which differ in contents by a hidden comment. This is undesirable and thus should be prevented with the `-notimestamp` feature. 
> Add -notimestamp option to javadoc creation

- org/mozilla/jss/pkix/cms/SignedData.java
Note that the patch in mbz#384470 is incorrect as the type is:
org.mozilla.jss.pkix.cms.SignerInfo
and not:
org.mozilla.jss.cms.SignerInfo
rhbz: 1534765
url: https://bugzilla.redhat.com/show_bug.cgi?id=1534765
mbz: 384470
url: https://bugzilla.mozilla.org/show_bug.cgi?id=384470
> Fix docstring for org.mozilla.jss.pkix.cms.SignedData

- tools/autoenv.sh
- tools/test_shell_style.sh
This introduces a new script, `tools/autoenv.sh` that should hope to plaster over most of the differences across Debian/SUSE/Fedora and allow the user to `source tools/autoenv.sh && make clean all check` to build the project easier.
In particular, we:
- Make an attempt to detect a JDK 8 version.
- Make an attempt to detect 64-bit mode.
- Check if we need to export a build-env specific flag
- Check if we need to use the system NSS/NSPR or if we're building in a sandbox with NSS/NSPR.
> Create script to automatically detect exports for build

- build_java.pl
- lib/Common.pm
- org/mozilla/jss/crypto/Algorithm.c
- org/mozilla/jss/tests/all.pl
- org/mozilla/jss/util/jssutil.c
This PR contains work by @emaldona that he has agreed to let me separate out from his JDK11-related work.
This introduces a `lib/Common.pm` Perl module for use by both `build_java.pl` and `tests/all.pl`, along with various small refactoring. This removes the call to `javah`, which has been removed in JDK9+, and replaces it to a single call to `javac` with the `-h` flag.
I'll be reviewing and cleaning up these two commits in this PR.
> lib/Common.pm - Common library for build_java.pl and tests/all.pl

- build_java.pl
- lib/Common.pm
- org/mozilla/jss/tests/all.pl
- tools/Dockerfiles/ubuntu_jdk8
- tools/autoenv.sh
- tools/test_perl_style.sh
This PR includes several Perl improvements split off from #47. In particular:
- Do jar detection versus using ENV vars to set the location of jars in `lib/Common.pm`
- Use fatal warnings in `build_java.pl` and `tests/all.pl` -- this found a number of bugs and more importantly, stops the script in the event of failure
- Uses the revised autoenv.sh in the Ubuntu build; this should allow us to test it more frequently.
Of particular note in the `tests/all.pl` revisions are the following:
- An error in the tests now results in an error in the build. Previously the exit status was still zero in the event of one or more test failures.
- `NATIVE_FLAG` has been removed. There appears to have been a [discussion with wtc](https://bugzilla.mozilla.org/show_bug.cgi?id=302550) in which nobody stated …
> Various Perl improvements

- .travis.yml
Note that F27 was the last release that shipped with v4.4.x;
on F28, ldapjdk 4.20 requires jss >= 4.5.0 and hence we can't
build v4.4.x with F28.
> Fix Travis CI on v4.4.x branch

- coreconf/nsinstall/pathsub.c
https://pagure.io/jss/issue/21
‘strncpy’ output truncated before terminating nul copying 3 bytes from a string of the same length
Using memcpy gets rid of the warning, same way NSS folks dealt with it.
Backport of #24 to v4.4.x
> Fix truncation warning

- README.md
- jss.spec
- lib/Common.pm
- tools/Dockerfiles/ubuntu_jdk8
- tools/autoenv.sh
Per discussion in #49 and [jss issue#27 / RFC](https://pagure.io/jss/issue/27), add a dependency on JAXB for JDK9+ builds. This is the last major issue preventing a build for JDK8 - JDK11 besides #41.
> Add dependency on JAXB for JDK9+

- .travis.yml
- org/mozilla/jss/tests/SymKeyDeriving.java
- tools/Dockerfiles/debian_jdk11
- #41: PKCS11Constants -- Those commits are duplicated here for CI / testing efforts. When that is merged, this PR can be rebased.
- #48: Perl improvements -- Those commits are duplicated here for CI / testing efforts. When that is merged, this PR can be rebased. 
This PR introduces two new commits:
1. Switching to the new PKCS11 Constants interface exposed in #41.
2. Add a Debian Testing / JDK11 test to the Travis matrix + rework the Travis matrix.
The second commit adds a Dockerfile for `debian_jdk11` which installs the necessary dependencies and runs the test against JDK11. Reworking the Travis matrix at the same time to allow easy view of what's required and what isn't:
I've opted to make `debian_jdk11` optional as it _is_ Debian Testing and might be unstable. Also, Debian is the only …
> JDK9+ support

- rules.mk
html is another standard build target that I missed earlier and is
documented here:
https://www.gnu.org/prep/standards/html_node/Standard-Targets.html
This makes the html target build the javadocs, as they are generated in
HTML format.
> Add html build target

- .travis.yml
- tools/Dockerfiles/fedora_29
- tools/Dockerfiles/fedora_29_jdk11
- tools/Dockerfiles/fedora_rawhide
These images help ensure support for later Fedora releases and ensure
that we maintain JDK8+ support across various Fedora releases. They've
been added to the Extras section such that they don't fail the build and
aren't required to pass for the build to succeed, but so that we can
keep an eye on their status.
The `fedora_29` image can be moved to the main section when 29 ships and
27 can then be removed.
> Add additional Fedora testing images

- build_java.pl
- overview.html
- address: https://pagure.io/jss/issue/28
- add "-overview ./overview.html" option to the javadoc command invocation
- add overview.html file at the top of the source tree
- overview.html provides a title and a brief description of jss
- no longer need to replace index.html with overview-summary.html
> Fix problem where firefox could not display the INDEX tab as of jdk 11

- build_java.pl
- jss.spec
- org/mozilla/jss/tests/all.pl
- rules.mk
- tools/reproducible_jar.sh
- tools/test_shell_style.sh
This PR adds support for reproducible builds in two parts:
- In `build_java.pl` and `tests/all.pl`, inconsistent use was made for using `xpclass.jar` directly as a literal or as a variable. I've updated this such that the variables set in `rules.mk` (which are passed to the `build_java.pl` script) control the jar name throughout building and testing. This allows us to change the `xpclass.jar` name at a later point if we desire.
- Implement reproducible JAR builds via a shell script, `tools/reproducible_jar.sh`. This is added as a make target, `reproducible`, a test target of `reproducibleCheck`, and then added to the `jss.spec` for use in Fedora.
To validate that this build really is reproducible:
```bash
cd sandbox/jss
rm ../dist -rf
make clean all reproducible
md5sum ../dist/*.jar …
```
> Reproducible JAR builds

- .travis.yml
As promised... [Fedora 29 is here](https://fedoramagazine.org/announcing-fedora-29) :)
Celebrate by kicking Fedora 27 out of the Travis images and adding Fedora 29 in. Keeping the Docker file around for now in case we decide we want to keep it later or want it for testing.
> Fedora 29 was released!

- org/mozilla/jss/CryptoManager.java
- org/mozilla/jss/InitializationValues.java
- org/mozilla/jss/SecretDecoderRing/KeyManager.java
- org/mozilla/jss/asn1/BIT_STRING.java
- org/mozilla/jss/crypto/Algorithm.java
- org/mozilla/jss/crypto/KeyPairGenerator.java
- org/mozilla/jss/netscape/security/pkcs/PKCS7.java
- org/mozilla/jss/netscape/security/provider/DSA.java
- org/mozilla/jss/pkix/cert/CertificateInfo.java
- org/mozilla/jss/pkix/cmc/RevokeRequest.java
- org/mozilla/jss/pkix/cmmf/RevRequest.java
- org/mozilla/jss/ssl/SSLServerSocket.java
- org/mozilla/jss/ssl/SSLSocket.java
- org/mozilla/jss/ssl/SSLSocketException.java
- org/mozilla/jss/ssl/SocketBase.java
- Address: https://github.com/dogtagpki/jss/issues/65
- use of `<tt>/</tt>` tags causes failures with jdk11 tools
- see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tt
- not a problem with either jdk8 or jdk10
> Fix javadoc reported errors when switching to jdk11

- org/mozilla/jss/netscape/security/util/DerOutputStream.java
- org/mozilla/jss/tests/DEROutputStreamTests.java
- org/mozilla/jss/tests/EnumerationZeroTest.java
- org/mozilla/jss/tests/all.pl
When an enumerated type has value zero, it is incorrectly given a length
of zero. Per X609, Section 8.4:
The encoding of an enumerated value shall be that of the integer value
with which it is associated. NOTE - It is primitive.
An integer is always encoded as a pair <length>+<value>, with value
always being specified, and thus <length> is always at least 1. However,
we were encoding enumerated as:
0A 00
instead of the correct value:
0A 01 00
This fixes the above error.
This error occurs because the range check on `length` allows it to reach zero, which occurs precisely when the value (`i`) is zero. This logic is correct in the negative case above, though negative zero does not occur in Java. This includes the original test case from the BZ along with a new test case that can be extended …
> DER encode error for zero-valued enumerated types

- tools/autoenv.sh
- tools/build_pkcs11_constants.py
`tools/autoenv.sh` now returns rather than exiting; when sourced and
`JAVA_HOME` could not be determined, the entire shell exited.
`tools/build_pkcs11_constants.py` has been updated to conform to F29
`pylint` standards; this limits the number of branches in a function.
> Small script fixes

- org/mozilla/jss/CryptoManager.c
- org/mozilla/jss/PK11Finder.c
- org/mozilla/jss/pkcs11/PK11SecureRandom.c
- org/mozilla/jss/pkcs11/PK11SymmetricKeyDeriver.c
- org/mozilla/jss/ssl/callbacks.c
I'm not a fan of the `loser` label, so I'm opting to replace it with `finish` instead as it is more clear.
> Replace instances of loser label with finish

- cmake/FindNSPR.cmake
- cmake/FindNSS.cmake
These are imported from dogtagpki/pki, with minor improvements to make
them work on Debian and Ubuntu.
> Add FindNSS and FindNSPR from PKI

- lib/jss.def
- lib/manifest.mn
- manifest.mn
- org/mozilla/jss/CryptoManager.c
- org/mozilla/jss/CryptoManager.java
- org/mozilla/jss/JSSProvider.java
- org/mozilla/jss/tests/JSSPackageTest.java
- org/mozilla/jss/util/jssver.h
We define the JSS version in three places:
lib/manifest.mn
manifest.mn
org/mozilla/jss/util/jssver.h
By using JNI, we can extract the JSS version from `org/mozilla/jss/util/jssver.h`, reducing the number of places we have to define the version manually.
Note that I've not fully updated the docstring to reflect the second location (`jss/manifest.mn`) -- we're removing both it and `jss/lib/manifest.mn` anyways in #78.
> Simplify version handling

- lib/MANIFEST.MF.in
- lib/jss.map
In preparation for the new CMake build system, introduce two new files
to the `lib/` directory. The `MANIFEST.MF.in` is used to generate the
`META-INF/MANIFEST.MF` file in the JSS JAR, and `jss.map` is used as the
linker version script when building the JSS library.
> Add lib/MANIFEST.MF.in and lib/jss.map

- cmake/JSSCommon.cmake
- cmake/JSSConfig.cmake
- cmake/JSSTests.cmake
Adds more extensive source-level documentation about CMake to the CMake build itself. This also fixes a few minor issues, such as better parallelizing the test suite and missing dependencies during build.
Acceptance Criteria:
> cmake in-source documentation

- cmake/JSSCommon.cmake
- cmake/JSSConfig.cmake
- cmake/JSSTests.cmake
Adds DER Encoding tests to the ctest test suite. These were present in all.pl at time of moving to CMake, but weren't yet added. This adds them back in.
Note that this PR is dependent upon #84, and includes commits in that PR.
> DER Encoding to Ctest

- cmake/JSSConfig.cmake
- cmake/JSSTests.cmake
Note that, per [jss issue#30](https://pagure.io/jss/issue/30), these fail under `FUTURE` crypto policy. 
Adds SSLClientAuth tests to the ctest test suite. These were present in `all.pl` at time of moving to CMake, but weren't yet added. This adds them back in.
Note that this PR is dependent upon #84, and includes commits in that PR.
> Add ClientAuth tests to ctest

- cmake/JSSCommon.cmake
- cmake/JSSConfig.cmake
In preparation for a C language test, this refactors CMake so that it
can support building other C targets besides the `libjss4.so` library.
This will allow us to build stand-alone executables which don't depend
on `libjss4.so` but could depend on the NSS/NSPR libraries.
> Refactor CMake to support building other C targets

- org/mozilla/jss/tests/GenerateTestCert.java
- org/mozilla/jss/tests/SSLClientAuth.java
- org/mozilla/jss/tests/X509CertTest.java
This is required if we wish to run the JSS test suite on a system
with the `FUTURE` cryptopolicy currently enforcing. In particular, key
sizes of 1024 and 2048 are too small for later use by NSS, causing test
failures. Note that `FUTURE` currently sets a minimum key length for RSA
of 3072 bits.
Part of this (changing `GenerateTestCert`) is required for the later work on SSLEngine, and for reintroducing the Client/Server SSL tests to JSS. Currently a 1024-bit RSA certificate is created, which is too small for any (except LEGACY?) policy.
This is related to [jss issue#30](https://pagure.io/jss/issue/30). 
> Bump keysizes to 4096

- cmake/JSSTests.cmake
When switching to CMake in #78, this was one of the tests dropped from the new test system. This PR adds it back in and addresses the AI from @emaldona's #91. 
> Reintroduce PKCS11 Constants test

- cmake/JSSConfig.cmake
- cmake/JSSTests.cmake
Remove and recreate the NSS DB folders as part of the test suite to
enable CTests to be executed multiple times without the user having to
manually remove and recreate them.
> Allow tests to be run repeatedly

- README.md
- cmake/JSSCommon.cmake
- cmake/JSSConfig.cmake
- docs/dependencies.md
- tools/Dockerfiles/debian_jdk11
- tools/Dockerfiles/ubuntu_jdk8
- tools/reproducible_jar.sh
When CMake was introduced, reproducible JAR builds were not part of the pull request. 
This reintroduces reproducible JAR builds in three commits:
- Document the usage of `tools/reproducible_jar.sh`
- Add reproducible JAR build back to CMake
- Make `tools/reproducible_jar.sh` silent except on errors.
> CMake reproducible JARs

- cmake/JSSCommon.cmake
- cmake/JSSConfig.cmake
- cmake/JSSTests.cmake
This PR is dependent upon #97 and #98 and includes commits from both. Only the last commit is new.
In a future PR to test #93 and the SSLEngine work, we'd like to also be able to test C code which lives in `libjss4.so` but _isn't_ a JNI call. Thus, we require an unversioned `libjss4.so` or directly link to all of the objects we wish to test. If the objects we wish to test are complex and in turn depend on other objects, an unversioned `libjss4.so` is best; if however, these objects are always simple, directly compiling in the objects (from `build/lib/*.o`) would suffice.
In the test suite, we continue using the versioned library for Java calls, but use the unversioned library for directly executed programs: this ensures that any new tests we introduce for new methods will fail if these …
> Library testing

- CMakeLists.txt
- cmake/JSSCommon.cmake
- cmake/JSSConfig.cmake
Respect `CMAKE_BUILD_TYPE` for Release vs Debug
This is the final step in enabling CMake builds to replace the old
functionality: specifying `-DCMAKE_BUILD_TYPE=Release` on the CMake
command line is equivalent to setting `BUILD_OPT=1` in the old build
system.
This has been verified by comparing the RPM builds from branch HEAD to the commit before the introduction of CMake and checking the contents of the JAR after extraction. 
Depends on commits from #98 and #99; will be rebased after they merge. 
> Enable release builds

- cmake/JSSConfig.cmake
- jss.spec
A several notable changes have been made since 4.5.0:
- A new CMake build system has been introduced to replace coreconf,
- Support for OpenJDK versions 8 through 11 has been added,
- Reproducible JAR builds,
- Minor DER encoding issues have been fixed,
- Synced supported TLS ciphersuites with NSS,
- Introduced PKCS11 Constants in JSS to replace Sun constants,
- And various other minor changes.
Thanks to everyone who has contributed since 4.5.0!
> Release JSS version 4.5.1

- org/mozilla/jss/pkcs11/PK11Store.c
- org/mozilla/jss/ssl/callbacks.c
This PR fixes two warnings during the build: an unused variable in `callbacks.c` and more importantly, fix an uninitialized return in error cases in `PK11Store.c`.
I'm scheduling this for 4.5.2 time frame as it is only a minor change.
> Cleanup warnings

- org/mozilla/jss/netscape/security/util/DerOutputStream.java
- org/mozilla/jss/netscape/security/util/DerValue.java
This backports two DER encoding fixes from master to the v4.4.x branch.
#69 and #89.
> Backport two DER encoding fixes

- org/mozilla/jss/crypto/KeyWrapAlgorithm.java
This is a copy of the `getKeyWrapAlgorithmFromOID` method from PKI's
`com.netscape.cmsutil.crypto.CryptoUtil`. This introduces new OID members
with public scope to allow future code to use the OID values (especially
under the `org.mozilla.jss.netscape.security` package).
> Add fromOID to KeyWrapAlgorithm

- cmake/JSSTests.cmake
- org/mozilla/jss/crypto/KeyWrapAlgorithm.java
- org/mozilla/jss/netscape/security/pkcs/PKCS10.java
- org/mozilla/jss/netscape/security/pkcs/PKCS12.java
- org/mozilla/jss/netscape/security/pkcs/PKCS12CertInfo.java
- org/mozilla/jss/netscape/security/pkcs/PKCS12KeyInfo.java
- org/mozilla/jss/netscape/security/pkcs/PKCS12Util.java
- org/mozilla/jss/netscape/security/util/Cert.java
- org/mozilla/jss/netscape/security/util/ObjectIdentifier.java
- org/mozilla/jss/netscape/security/util/Utils.java
- org/mozilla/jss/netscape/security/util/WrappingParams.java
- org/mozilla/jss/netscape/security/x509/AlgorithmId.java
- org/mozilla/jss/netscape/security/x509/CIDRNetmask.java
- org/mozilla/jss/netscape/security/x509/GeneralName.java
- org/mozilla/jss/netscape/security/x509/GeneralNameInterface.java
- org/mozilla/jss/netscape/security/x509/IPAddressName.java
- org/mozilla/jss/netscape/security/x509/InvalidNetmaskException.java
- org/mozilla/jss/tests/BigObjectIdentifier.java
This PR depends on #104 and includes commits from that series; it will be rebased when that PR is merged.
Each commit in question includes two paths: the path under the JSS source repo and the path under the PKI source repo. This allows easy review: clone PKI at master, clone JSS at this PR's `HEAD`, and diff each of the changed files. The changes should be minimal, only changing associated imports and other fully qualified package names.
This will allow us to remove the code from PKI, release a new JSS version with the changes, make PKI depend on this new JSS version, and remove from PKI these classes. See: 
- [PKI PR#121](https://github.com/dogtagpki/pki/pull/121) - which updates package paths (`netscape.security` -> `org.mozilla.jss.netscape.security`)
- [PKI …
> Sync PKI and JSS common classes

- org/mozilla/jss/crypto/KeyWrapAlgorithm.java
- org/mozilla/jss/netscape/security/pkcs/PKCS10.java
- org/mozilla/jss/netscape/security/pkcs/PKCS12.java
- org/mozilla/jss/netscape/security/pkcs/PKCS12CertInfo.java
- org/mozilla/jss/netscape/security/pkcs/PKCS12KeyInfo.java
- org/mozilla/jss/netscape/security/pkcs/PKCS12Util.java
- org/mozilla/jss/netscape/security/util/Cert.java
- org/mozilla/jss/netscape/security/util/ObjectIdentifier.java
- org/mozilla/jss/netscape/security/util/Utils.java
- org/mozilla/jss/netscape/security/util/WrappingParams.java
- org/mozilla/jss/netscape/security/x509/AlgorithmId.java
- org/mozilla/jss/netscape/security/x509/CIDRNetmask.java
- org/mozilla/jss/netscape/security/x509/GeneralName.java
- org/mozilla/jss/netscape/security/x509/GeneralNameInterface.java
- org/mozilla/jss/netscape/security/x509/IPAddressName.java
- org/mozilla/jss/netscape/security/x509/InvalidNetmaskException.java
- org/mozilla/jss/tests/BigObjectIdentifier.java
- org/mozilla/jss/tests/all.pl
Backport of #101. ~Depends on #109.~
Each commit in question includes two paths: the path under the JSS source repo and the path under the PKI source repo. This allows easy review: clone PKI at master, clone JSS at this PR's `HEAD`, and diff each of the changed files. The changes should be minimal, only changing associated imports and other fully qualified package names.
This will allow us to remove the code from PKI, release a new JSS version with the changes, make PKI depend on this new JSS version, and remove from PKI these classes. See: 
- [PKI PR#121](https://github.com/dogtagpki/pki/pull/121) - which updates package paths (`netscape.security` -> `org.mozilla.jss.netscape.security`)
- [PKI PR#122](https://github.com/dogtagpki/pki/pull/122) - which removes `netscape.security` from the …
> [WIP] Backport Sync PKI and JSS common classes

- org/mozilla/jss/tests/GenerateTestCert.java
- org/mozilla/jss/tests/SSLClientAuth.java
- org/mozilla/jss/tests/X509CertTest.java
Backport of #92.
This is required if we wish to run the JSS test suite on a system
with the FUTURE cryptopolicy currently enforcing. In particular, key
sizes of 1024 and 2048 are too small for later use by NSS, causing test
failures. Note that FUTURE currently sets a minimum key length for RSA
of 3072 bits.
> Backport - Bump keysizes to 4096

- .classpath
- build_java.pl
- jss.spec.in
These changes were backported from master; jss no longer requires
ldapjdk so we can remove it from the spec file and the build scripts.
> Fix LDAPJDK circular dependency

- .classpath
- .travis.yml
- build.sh
- build_java.pl
- jss.spec.in
- tools/Dockerfiles/centos_7
- tools/Dockerfiles/fedora_26
- tools/Dockerfiles/fedora_27
- tools/Dockerfiles/fedora_28
- tools/Dockerfiles/fedora_29
- tools/run_container.sh
This backports most of the CI improvements from `master` to `v4.4.x` and fixes the build on older Fedoras (pre F27) and CentOS 7. 
In particular:
- Backport Containerized (`Dockerfile`) based CI
- Fix `pki.spec.in` to not use pre-F27 macros.
- Fix `build.sh` to not use `git -C` as CentOS doesn't support `git -C`.
- Backport Travis configuration.
Note that `build.sh` doesn't pass `ShellCheck` and while we could include the `test_perl_style.sh` as the `v4.4.x` still uses the Perl build and test system, I've decided to omit the `stylecheck` CI pass.
@SilleBille Thoughts from the CI czar? :)
> Backport CI Improvements

- org/mozilla/jss/CryptoManager.c
- org/mozilla/jss/CryptoManager.java
NSS's pkcs11.txt includes global ciphersuite options, however, it
doesn't understand Curve25519 as a parameter. Until such support is
added (or NIST finally approves Curve25519 for FIPS 140-2 usage!),
manually disable Curve25519 when FIPS mode is enabled.
> Disable x25519 in FIPS mode

- README.md
- jss.spec
Reported by @emaldona via email.
Minimum NSS version is 3.28 in the spec file, but SSLAlert is introduced in 3.30:
https://github.com/nss-dev/nss/blob/NSS_3_28_BRANCH/lib/ssl/ssl.h
https://github.com/nss-dev/nss/blob/NSS_3_29_BRANCH/lib/ssl/ssl.h
https://github.com/nss-dev/nss/blob/NSS_3_30_BRANCH/lib/ssl/ssl.h#L832
> Bump NSS version to 3.30 for SSLAlert

- jss.spec
Minor spec change to output cause on failure.
Will make CI more useful. :)
> [spec] ctest: --output-on-failure

- .travis.yml
- tools/Dockerfiles/debian_jdk11
- tools/Dockerfiles/fedora_29_jdk11
- tools/Dockerfiles/fedora_rawhide
- tools/Dockerfiles/ubuntu_jdk8
Like #127, we add `ctest --output-on-failure` to the container images.
We also remove the `stylecheck` / `validate` stage of the Travis build to save time. The python and shell scripts aren't changing much so there's little point in running it every time.
> CI changes: ctest --output-on-failure and remove stylecheck image

- cmake/JSSConfig.cmake
- cmake/JSSTests.cmake
In addition to the two existing NSS DBs:
- `results/nssdb`
- `results/fips`
Add a new `results/data` directory for files created during tests.
(Bug tag since without creating the directories earlier, `results/` doesn't exist so we can't put stuff in it. Might as well separate that into `results/data`, so this does that). 
> Add data directory for tests to use.

- cmake/JSSConfig.cmake
- org/mozilla/jss/PK11Finder.c
- org/mozilla/jss/pkcs11/PK11KeyGenerator.c
- org/mozilla/jss/pkcs11/PK11KeyPairGenerator.c
This fixes a `-Werror=sign-compare` mistake in three locations and blacklists two other casts.
We don't currently pass `-Wall -Werror -Wextra` on clang, but that's for another time... This at least passes it on GCC.
The two whitelisted warnings are due to JNI and NSPR.
> Cleanup remaining warnings

- org/mozilla/jss/pkcs11/PK11Cert.c
- org/mozilla/jss/pkcs11/PK11Cipher.c
- org/mozilla/jss/pkcs11/PK11PrivKey.c
- org/mozilla/jss/pkcs11/PK11Signature.c
- org/mozilla/jss/ssl/common.c
- org/mozilla/jss/ssl/javasock.c
- org/mozilla/jss/util/jssutil.c
- org/mozilla/jss/util/jssutil.h
~Includes a commit from #124. Will be rebased after that PR is merged.~
A small helper method with consistent implementation for creating a new `jByteArray` from an existing array-like item in JSS. This proved useful in #122, so I split it off here. 
Ultimately I'd like more small wrappers like this around JNI functionality to have more consistent error handling.
I'm not sure what we should do instead of `assert` in C when `env` is `NULL`, but I'm guessing we don't have many options. Wrapping error handling would be another series of good JNI improvements.
> JNI improvements: ToByteArray

- jss.spec
- org/mozilla/jss/netscape/security/util/Cert.java
The sortCertificateChain() has been moved from
com.netscape.cmsutil.crypto.CryptoUtil in PKI to
org.mozilla.jss.netscape.security.util.Cert in
JSS for reusability.
The version number has been updated to 4.5.3 such
that the JSS dependency can be set properly in
other packages.
> Added Cert.sortCertificateChain()

- org/mozilla/jss/CryptoManager.c
- org/mozilla/jss/PK11Finder.c
- org/mozilla/jss/SecretDecoderRing/KeyManager.c
- org/mozilla/jss/pkcs11/PK11Cert.c
- org/mozilla/jss/pkcs11/PK11Store.c
- org/mozilla/jss/pkcs11/PK11SymKey.c
- org/mozilla/jss/pkcs11/PK11Token.c
- org/mozilla/jss/pkcs11/pk11util.h
- org/mozilla/jss/provider/java/security/JSSKeyStoreSpi.c
- org/mozilla/jss/ssl/SSLServerSocket.c
- org/mozilla/jss/ssl/SSLSocket.c
- org/mozilla/jss/ssl/callbacks.c
- org/mozilla/jss/ssl/common.c
- org/mozilla/jss/util/jssutil.c
- org/mozilla/jss/util/jssutil.h
This simplifies the interaction between C and Java with regards to JNI's `jstring` representation of Java's `String` objects. 
In particular, we only ever access JString's via their UTF8 representations, so this wrapper assumes we're doing that. It also handles `NULL` strings, simplifying the logic to call these wrappers: always call them and condition around a `NULL` return value instead of a `NULL` input value. 
This also caught two types of bugs:
- Where we forget to dereference at all.
- Where we (incorrectly) conditionally dereference around whether or not we're acting on a copy. Common consensus seems to be to always dereference, even on copies.
Questions: 
- Should we add error handling logic when the string fails to parse/reference? E.g., `jstring != NULL` but the return value is …
> JNI JString improvements

- README.md
- docs/dependencies.md
- jss.spec
- tools/Dockerfiles/debian_jdk11
- tools/Dockerfiles/fedora_29_jdk11
- tools/Dockerfiles/fedora_rawhide
- tools/Dockerfiles/ubuntu_jdk8
jUnit pulls in `hamcrest-core` for us, which is all we need. This should fix Rawhide builds, since `hamcrest` fails to install.
> Remove needless dependency on hamcrest

- jss.spec.in
- org/mozilla/jss/CryptoManager.java
- org/mozilla/jss/JSSProvider.java
- org/mozilla/jss/util/jssver.h
This release includes various fixes for ANS.1 encoding/decoding,
increased TLS cipher support, various OCSP related enhanacements,
support for PKCS11Constants (under the org.mozilla.jss.pkcs11
namespace), and an update to the netscape/security classes.
> Release JSS v4.4.5

- build.sh
- jss.spec.in
In JSS version 4.4.5, changes to the spec file were made that brought
upstream and downstream spec files out of alignment, because v4.4.5
chose to follow the .spec and build.sh changes to later v4.5.x releases.
This fixes the build.sh script to generate source tarballs like
downstream expects and updates the spec file accordingly.
> Align upstream and downstream spec files

- jss.spec
As discovered with the v4.4.6 release, the tarball creation process as
described in the spec file was wrong and/or generated a different
tarball than linked to by the Source URL. Update the procedure to match
the URL.
> Fix release procedure in jss.spec

- cmake/JSSConfig.cmake
- jss.spec
To make packaging easier, branch v4.5.x after the TomcatJSS fixes (in commit 91870d5b5898dcb1a82c3691449e50baa8fbd9ba). master branch becomes the new v4.6.x series; marking this as beta.
> Branch to v4.6.x

- README.md
- docs/contributing.md
> Fix IRC channel name: #dogtag-pki

- org/mozilla/jss/tests/SetupDBs.java
As far as I can tell, this 3s sleep is extraneous. This test creates the
NSS DB (instead of calling certutil -N) and provides an anchor point in
the test suite. Our alternatives are to use `certutil -N` instead of
SetupDBs, but we might as well keep this, just without the sleep.
It is possible the sleep was used, perhaps to ensure that the DB is
flushed to disk before the test suite continues, but this should be
handled by the JVM and shouldn't be considered as a side-effect of a
Sleep.
> Remove 3s sleep from SetupDBs

- .copr/Makefile
This lets us see which commit a user is at when using our various auto-built COPRs. This'd let us triage bugs better to know if something recent broke, or if a bug was fixed recently, etc. Thoughts?
> Use --with-timestamp and --with-commit-id for COPR

- org/mozilla/jss/CryptoManager.c
- org/mozilla/jss/PK11Finder.c
- org/mozilla/jss/pkcs11/PK11MessageDigest.c
- org/mozilla/jss/pkcs11/PK11SecureRandom.c
- org/mozilla/jss/pkcs11/PK11Signature.c
- org/mozilla/jss/pkcs11/PK11Store.c
- org/mozilla/jss/pkcs11/PK11SymmetricKeyDeriver.c
- org/mozilla/jss/pkcs11/PK11Token.c
- org/mozilla/jss/ssl/SSLSocket.c
- org/mozilla/jss/ssl/common.c
- org/mozilla/jss/ssl/javasock.c
- org/mozilla/jss/util/jssutil.c
- org/mozilla/jss/util/jssutil.h
Similar to #134, this changes how byte arrays are handled and using them in several places.
We already have a `JSS_ToByteArray` that we're using extensively, but `JSS_FromByteArray` does the opposite (`jbyteArray -> uint8_t *`). It also adds underlying `JSS_RefByteArray` and `JSS_DerefByteArray` helpers to access the raw byte array elements. 
Unlike `JSS_RefByteArray`, `JSS_FromByteArray` always makes a copy, so rather than returning it with `JSS_DerefByteArray`, free it with `free(...)`.
~Currently WIP because I need to:~
> JNI Enhancements: JSS_FromByteArray

- org/mozilla/jss/ssl/SSLVersion.java
`SSLVersion` currently only supports a single alias for naming TLS
protocol versions. Keep providing (and defaulting to) the NSS style
names, but also provide the JDK style names. This allows us to map
between the NSS constant and the JDK names.
@edewata Are there other changes you'd make to `SSLVersion` while we're here? 
> Extend SSLVersion to support JDK names

- org/mozilla/jss/pkcs11/PK11PrivKey.java
- org/mozilla/jss/pkcs11/PK11RSAPublicKey.java
- org/mozilla/jss/pkix/crmf/CertReqMsg.java
- org/mozilla/jss/tests/CloseDBs.java
Several of the usages of `BigInteger`s lead to the potential of negative
numbers, though only positive numbers should be returned.
`PK11RSAPublicKey`'s `getModulus()` and `getPublicExponent()` methods can
potentially return negative values, when both the modulus and exponent
should be strictly positive.
`PK11PrivKey`'s `getDSAParams()` could return negative values depending on
the PQG parameters.
The Key Identifiers printed by `tests.CloseDBs` should be positive (as
they're UIDs) but could be displayed as negative values; the same
happens in `crmf.CertReqMsg`.
This negation property is discussed [here](https://docs.oracle.com/javase/7/docs/api/java/math/BigInteger.html#BigInteger(int,%20byte[])).
> Return positive BigIntegers

- index.md
I'd like to see `#dogtag-pki` opened up to unregistered users before we merge this. 
> Add contact information to gh-pages

- cmake/JSSConfig.cmake
Reported by tjaalton on `#dogtag-pki`.
Adds two patches:
- Use JDK8 as the source and target release; this ensures we don't use any JDK9+ features by accident, and ensures that if we're building with a newer compiler (e.g., JDK11's `javac`), we still end up with something backwards compatible.
- Support [`JAVACFLAGS`](https://www.gnu.org/software/automake/manual/html_node/Java.html) as a method for passing flags to `javac` from the user.
> Support JDK8-target on JDK11

- cmake/JSSConfig.cmake
While Debian packages a useful junit4 (that already includes
hamcrest-core in its MANIFEST's Class-Path), we might as well include
the correct path in the auto detection script to silence the incorrect
warning.
> Add hamcrest-core for Debian

- cmake/JSSConfig.cmake
- jss.spec
(I'm interested in seeing if this'll fail CI)
- Add `netscape.security` to javadoc build  
I noticed this was missing after a discussion on `#dogtag-pki`; we're not    
building the javadocs for these packages; in part I'm guessing that this    
is because there's a number of errors associated with the build (bad    
formatting, parameters, etc), so these should be fixed as well.    
- Fix javadocs build
Since the current javadocs build process is broken (due to various  
non-fatal errors in the build), ignore the error code of make javadocs  
when building the RPM for now.
> Fix javadocs: add netscape.security packages

- org/mozilla/jss/ssl/common.c
This fixes the following compilation warning:
```c
jss/org/mozilla/jss/ssl/common.c: In function ‘getRoot’:
jss/org/mozilla/jss/ssl/common.c:923:5: warning: ‘certList’ may be used uninitialized in this function [-Wmaybe-uninitialized]
CERT_DestroyCertList (certList);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
> Declare certList earlier in ssl/common.c:getRoot

- org/mozilla/jss/crypto/Algorithm.c
- org/mozilla/jss/crypto/Algorithm.h
- org/mozilla/jss/crypto/Algorithm.java
- org/mozilla/jss/crypto/EncryptionAlgorithm.java
- org/mozilla/jss/crypto/KeyWrapAlgorithm.java
- org/mozilla/jss/pkcs11/PK11KeyWrapper.c
- org/mozilla/jss/pkcs11/pk11util.h
- org/mozilla/jss/tests/KeyWrapping.java
This patch adds  HSM support for the PKCS#11 standard defined KeyWrap/Padding
mechanism. Prior to this patch, only NSS (CKM_NSS_AES_KEY_WRAP_PAD) was supported.
Note that this is based on Thales's projection of having the following supported
in the next SW version, 12.60: CKM_AES_KEY_WRAP_PAD
For completeness, CKM_AES_KEY_WRAP is also added, although it is not suitable
for private key wrapping.
> Add HSM support for PKCS#11 AES KeyWrap/Padding

- cmake/JSSTests.cmake
- org/mozilla/jss/ssl/javax/BufferPRFD.c
- org/mozilla/jss/ssl/javax/BufferPRFD.h
- org/mozilla/jss/tests/TestBufferPRFD.c
~This PR is blocked on #103 and depends on commits in it.~
In order to support the `javax.net.ssl.SSLEngine` interface, we need to implement SSL-over-buffers instead of SSL over Sockets. This is the first step towards that: implementing a `PRFileDesc` which NSS can wrap with SSL to provide read/write methods. This can then be used in Java and then used to implement SSLEngine.
There are two commits here:
- Add the `PRFileDesc` implementation as a new header
- Use this new header in a test to ensure that it provides the requisite features.
Much of this code was previewed in [`cipherboy/testbed/c-prfd`](https://github.com/cipherboy/testbed/tree/master/c-prfd) before being cleaned up and introduced to JSS.
> Implement a NSPR PRFileDesc using buffers - 0:1

- tools/Dockerfiles/ubuntu_jdk8
We should have at least one build using this to ensure we detect issues
earlier.
> Add -Wall -Wextra -Werror to Ubuntu build

- cmake/JSSConfig.cmake
All platforms we support should support the newer C99 standard.
Explicitly pass it during build to ensure we don't fail to build on
platforms where the default is C89.
> Set an explicit C standard: C99

- org/mozilla/jss/CryptoManager.c
- org/mozilla/jss/ssl/common.c
In the OCSP patches, there were two issues detected by clang (on top of #175): 
- Addition between a `const char *` and an `int`; this is legal in Java but not in C.
- An uninitialized (and undefined) use of `root` due to the use of `goto`.
> Fix issues with OCSP patch

- cmake/JSSTests.cmake
- lib/jss.map
- org/mozilla/jss/nss/PR.c
- org/mozilla/jss/nss/PR.java
- org/mozilla/jss/nss/PRFDProxy.c
- org/mozilla/jss/nss/PRFDProxy.h
- org/mozilla/jss/nss/PRFDProxy.java
- org/mozilla/jss/tests/TestPRFD.java
- org/mozilla/jss/util/java_ids.h
- org/mozilla/jss/util/jssutil.h
This includes commits from ~#125~ and ~#129~.
The goal here is to pull methods up from the C layer and place them in Java land. We're ultimately going to write a SSLEngine entirely in Java, by forking out to the relevant wrapper methods when appropriate.
This should help to complete some of our NSS API wrapping as well. Rather than only exposing "complex" methods which potentially make several NSS/NSPR calls, expose simpler calls and wrap them in higher-level objects.
I realize that the `org.mozilla.jss.nss` folder is a bit of a misnomer right now as it only contains NSPR methods, but I figured I'd prefer to place everything "raw" under `org.mozilla.jss.nss` rather than splitting them.
Alternatively, we could call it `org.mozilla.jss.raw.` but I wasn't as happy with that name.
> JNI for NSS's PRFileDesc - 1:0

- .travis.yml
By giving a simple `true` script, the Extras section will have a job
which succeeds quickly. This should make the entire Travis run take
less time, as while the Extras section is fast-finish, it won't finish
until the first job succeeds.
> Allow Travis Extras section to succeed quickly

- org/mozilla/jss/util/jssutil.h
Also, switch to including all required headers, removing the old
comment.
Reported by @emaldona.
> Move include after copyright in util/jssutil.h

- cmake/JSSTests.cmake
- lib/jss.map
- org/mozilla/jss/nss/SSL.c
- org/mozilla/jss/nss/SSL.java
- org/mozilla/jss/nss/SecurityStatusResult.java
- org/mozilla/jss/tests/TestRawSSL.java
- org/mozilla/jss/util/java_ids.h
~Depends on and includes commits from #122. Will be rebased once that merges.~
~Independent from #130.~ -- PR #130 has been closed as unnecessary. 
This begins implementing methods from NSS with the `SSL_` in an abstraction/JNI layer. This lets us pull the calls away from C, using them later from Java, without having to write a bunch of messy JNI.
These methods were ones included in the example C code from #93. The end goal will be a parallel implementation of the test in #93 except in Java.
(Commits currently messy; missing functionality).
> JNI for NSS's `SSL_` methods - 1:1

- cmake/JSSTests.cmake
- lib/jss.map
- org/mozilla/jss/nss/Buffer.c
- org/mozilla/jss/nss/Buffer.java
- org/mozilla/jss/nss/BufferProxy.c
- org/mozilla/jss/nss/BufferProxy.h
- org/mozilla/jss/nss/BufferProxy.java
- org/mozilla/jss/tests/TestBuffer.java
- org/mozilla/jss/util/java_ids.h
Dependencies:
- ~#138 - for JNI enhancements.~
- ~#103 - for the buffer implementation.~
- ~#93 - for buffer-prfd and associated `j_buffer` improvements.~
- ~#122 - for accessing NSPR's `PRFileDesc` objects in Java.~
(Note that #93 and #122 aren't strictly necessary for this PR, but are for the next PR in the series).
This PR adds support for calling into `j_buffer` objects from Java. The next PR in this series (`2:1`) will let us construct `BufferPRFD` objects in Java.
Then `3:0` will combine `2:1` with `1:1` and let us reproduce the [test case](https://github.com/cipherboy/jss/blob/buffer-prfd/org/mozilla/jss/tests/TestBufferPRFD.c) for a Buffer PRFileDesc (i.e., do a single-threaded async SSL handshake) in Java, and `4:0` will begin implementing a `SSLEngine`.
> JNI for j_buffer - 2:0

- cmake/JSSTests.cmake
- lib/jss.map
- org/mozilla/jss/nss/PR.c
- org/mozilla/jss/nss/PR.java
- org/mozilla/jss/tests/TestBufferPRFD.java
As a continuation of #145...
This adds support (and tests!) creating a BufferPRFD from Java. This will ultimately be used as the core of a new SSLEngine, encrypting data to/from the buffer. Adds a test case to ensure send/recv on a BufferPRFD work as expected. 
Questions:
Answers: 
- The buffer should only have wire contents in it; these will all be encrypted data which is no more than what an attacker would get. So it is fine to not clean these.
> JNI for BufferPRFD - 2:1

- org/mozilla/jss/pkcs11/PK11Cert.java
By extending the `java.security.cert.X509Certificate` class, we can now
use `PK11Cert` in a variety of Java-standard interfaces, downcasting to
`PK11Cert` when applicable. This lets us preserve the NSS pointer to the
certificate so we can make future NSS calls on it.
As @edewata pointed out, we already have a [`X509CertImpl`](https://github.com/dogtagpki/jss/blob/master/org/mozilla/jss/netscape/security/x509/X509CertImpl.java) that handles all the decoding of certificates for us. Choose a lazy evaluation strategy: the contents of the `x509` aren't parsed until a `java.security.cert.X509Certificate` method is called, and then evaluated only once. This means constructing the `PK11Cert` isn't any slower and unless you use the `java.security.cert.X509Certificate` methods, you won't incur any …
> Extend java.security.cert.X509Certificate in PK11Cert - 5:0

- cmake/JSSTests.cmake
- org/mozilla/jss/tests/TestBufferPRFD.java
This depends on all open JNI javax-labeled PRs:
- ~#146 for JNI access to the Buffer PRFileDesc.~
- ~BufferPRFDs are described in #93 ~
- ~Which use `j_buffer`s from #103.~
- ~#132 for access to NSS's SSL implementation.~
- ~With `NSS_Init` from #132 (maybe not necessary).~
- ~And JNI PRFD access from #130 (also included in #146).~
This PR will include the equivalent test as #93's `TestBufferPRFD.c`, which performs a single-threaded, asynchronous SSL connection, except using JNI and Java instead of the NSS C API. 
This PR is WIP because:
> JNI SSL Handshake Test - 3:0

- lib/jss.map
- org/mozilla/jss/nss/SSL.c
- org/mozilla/jss/nss/SSL.java
- org/mozilla/jss/tests/TestRawSSL.java
To mirror `SSL.OptionSet`, expose `SSL_OptionGet` as `org.mozilla.jss.nss.SSL.OptionGet`.
> Add SSL.OptionGet

- CMakeLists.txt
The old build system respected the `CHECK_DEPRECATION` environment
variable to enforce deprecation checks during (Java) compilation
time. In the new system, this was broken by not using the `ENV{}`
construct and not adding the flag to the correct variable.
This was reported by @emaldona.
Should be backported to `v4.5.x` branch as well. 
> Fix CHECK_DEPRECATION compatibility

- org/mozilla/jss/JSSProvider.java
- org/mozilla/jss/provider/javax/crypto/JSSKeyManager.java
- org/mozilla/jss/provider/javax/crypto/JSSKeyManagerFactory.java
- org/mozilla/jss/provider/javax/crypto/JSSTrustManager.java
- org/mozilla/jss/provider/javax/crypto/JSSTrustManagerFactory.java
~Depends on commits from #158. Will be rebased once that is merged.~
This includes a KeyManager and TrustStore implementation in the JSS crypto provider. Copied from TomcatJSS into JSS.
Work in progress as:
> Add KeyManager and TrustStore - 5:1

- cmake/JSSTests.cmake
- org/mozilla/jss/tests/JSSProvider.java
Depends on #159 and #160. Will be rebased when they merge. Only the [last commit](https://github.com/dogtagpki/jss/pull/164/commits/7b9c64397b9041ee21bea8aeb1a854b53230bde2) in this series is useful.
Adds tests for the [`JSSProvider`](https://github.com/dogtagpki/jss/blob/master/org/mozilla/jss/JSSProvider.java) to ensure that it exposes stuff useful for our consumption internally (subclasses in `org.mozilla.jss.provider`). Also ensures that the provider we insert (via the `CryptoManager`) gets utilized by default.
> Add tests for JSSProvider - 5:3

- org/mozilla/jss/CryptoManager.c
- org/mozilla/jss/ssl/common.c
Backport of three OCSP related fixes to `v4.4.x` branch.
These come from #175 and #180 against master.
> Backport OCSP fixes

- org/mozilla/jss/CryptoManager.c
- org/mozilla/jss/ssl/common.c
Backport of three OCSP related fixes to `v4.5.x` branch.
These come from #175 and #180 against master. Related backport: #192
> Backport OCSP fixes to v4.5.x

- org/mozilla/jss/ssl/javax/JSSParameters.java
This class extends [`SSLParameters`](https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLParameters.html) to provide convenience wrappers for
interacting with NSS classes in a standard Java environment. In
particular, they allow for the parsing of cipher suites into and out of
`ssl.SSLCipher` enum values, and for handling the differences between the
Java standard form of TLS versions as a String, `ssl.SSLVersion` enum
values, and `ssl.SSLVersionRange` instances.
Blocks #150 as this is included in that range of commits.
> Add ssl.javax.JSSParameters

- org/mozilla/jss/ssl/javax/JSSParameters.java
This lets us find the certificate in the NSS DB by alias; none of the
existing `SSLParameters` are sufficient for this task.
> Store cert alias in JSSParameters

- org/mozilla/jss/tests/TestBufferPRFD.java
The [NSS documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/SSL_functions/sslfnc.html#1085950) allows `SSL_ImportFD` to take a null first
parameter; in this case, NSS defaults will be used instead of defaults
from the model. Since we're creating the model *with* default parameters
(and not really saving a global model with updated parameters), don't
bother creating a model `PRFileDesc`.
> Test SSL handshake without TCP model

- org/mozilla/jss/nss/PR.c
Unlike `read_buf` or `write_buf`, peer_info can reasonably be null; handle
this gracefully and create the `BufferPRFD` instead of returning a null
`PRFDProxy` reference.
> [nss.PR] Create BufferPRFD when peer_info is null

- org/mozilla/jss/ssl/javax/JSSParameters.java
When using NSS as a client, `SSL_SetURL` must be called with the remote
host for certificate verification. Store the hostname in `JSSParameters`
so we can set it later in the `JSSEngine` (from #150).
> Track server hostname in JSSParameters

- cmake/JSSConfig.cmake
This is necessary for downstream builds. 
> Support LD_FLAGS from environment

- org/mozilla/jss/ssl/SSLServerSocket.c
In `SSLServerSocket.c`, we use the deprecated form, `SSL_ConfigSecureServer`.
Switch to using the newer form, `SSL_ConfigServerCert`. This also saves us
a call to check the KEA usage.
`SSL_ConfigSecureServer` [deprecation notice](https://github.com/nss-dev/nss/blob/master/lib/ssl/ssl.h#L986-L998).
`SSL_ConfigServerCert` [description](https://github.com/nss-dev/nss/blob/master/lib/ssl/ssl.h#L933-L984).
NSS likely won't remove `SSL_ConfigSecureServer`, but we might as well do our part to help with its deprecation. Since we're just querying KEA directly, passing the default `NULL` struct will do the same. 
> Switch to SSL_ConfigServerCert

- org/mozilla/jss/tests/TestBufferPRFD.c
- org/mozilla/jss/tests/TestBufferPRFD.java
When the handshake fails to complete in a certain number of steps,
terminate it. We set this limit as 40 as it should be significantly
larger than the number of required steps (since the buffer limit is at
2048, we'd expect no more than 10 steps, even with a large certificate
or chain).
> Terminate SSL test cases after too many attempts

- CMakeLists.txt
- cmake/JSSTests.cmake
- jss.spec
Certain tests will fail in FIPS mode. These are largely expected on our part, so detect if we're in FIPS mode and just disable them.
There's three categories of failures:
- Things which use the wrong algorithms -- we could fix these if we wanted to, but we might as well still test them.
- Things which are unexpected failures -- we can fix these on a per-case basis and move them back.
- Things which will never work (like, disabling FIPS mode)  -- these we can't fix.
This was tested on @edewata's F28 FIPS VM and it builds successfully.
> Disable tests in FIPS mode

- org/mozilla/jss/JSSProvider.java
As mentioned in [`dogtagpki/pki pr#230`](https://github.com/dogtagpki/pki/pull/230), we should add these to the JSS provider to avoid the need for `CryptoUtil.getHMACAlgName(...)`. 
> Add alternative HMAC names for JSSProvider

- cmake/JSSTests.cmake
- org/mozilla/jss/tests/CrossHMACTest.java
On systems with case-insensitive file systems, cloning will likely fail
as there's two files with the "same" name but different contents:
`HmacTest.java` and `HMACTest.java`. Rename the latter, which attempts to
test different providers, to `CrossHMACTest`.
> Rename HMACTest -> CrossHMACTest

- org/mozilla/jss/crypto/Algorithm.java
- org/mozilla/jss/crypto/PKCS11Algorithm.java
We need to map PKCS11 Constants between their names and their values and
also between their values and Algorithm identifiers. To do so, we add
PKCS11Algorithm which enumerates identifiers common to both Algorithm
and PKCS11Constants. This will let us call into the NSS API with the
correct constant identifier from PKCS11, when needed.
(More concretely, we can now call into the PKCS11 NSS API without resolving the values from Algorithm if we desire. This will let us upcast generic Keys (which are, oddly, instances of Algorithms) into `PK11SymKey` objects (which contain a NSS pointer)). 
> Add enum for Algorithm's PKCS #11 Constants

- org/mozilla/jss/crypto/KeyGenAlgorithm.java
- org/mozilla/jss/crypto/SymmetricKey.java
In `SymmetricKey.java`, SHA-1 HMAC was defined as [`PBA_SHA1_HMAC`](http://docs.oasis-open.org/pkcs11/pkcs11-curr/v2.40/os/pkcs11-curr-v2.40-os.html#_Toc228894782), a version
of HMAC for extending a password (using a salt) and turning it into a
key. Usually when one requests HMAC, one expects vanilla HMAC; use this
instead. We expose the old `SHA1_HMAC` (with PBA) as `PBA_SHA1_HMAC` now.
Note that later SHA-2 and SHA-3 algorithms lack PBA-based HMACs (in PKCS
v2.40 and v3.0 standards).
> Fix SHA1-HMAC in SymmetricKey

- org/mozilla/jss/crypto/Algorithm.c
- org/mozilla/jss/crypto/Algorithm.h
- org/mozilla/jss/crypto/Algorithm.java
- org/mozilla/jss/crypto/KeyGenAlgorithm.java
- org/mozilla/jss/crypto/SymmetricKey.java
~Blocked by #222 and #224; will be rebased once those merge.~
SHA2-based HMACs have different key lengths than SHA1. We should expose both in SymmetricKey, in case we end up using them. It isn't clear whether this is strictly checked by the API though: `SHA1_HMAC` has been used as the key type for SHA2-based HMACs already. The difference is likely minimal.
We should add a more extensive HMAC-based test suite to JSS to validate that our HMAC implementation is indeed correct and functions under either set of constants. To do so, we'll want to expose a byte-based key importing instead of requiring randomly generated keys.
> Add SHA2 HMAC

- cmake/JSSConfig.cmake
might need to get backported to 4.5 if so desired
also for jaxb, the errormessage refers to javaee-jaxb-api.jar while only checking for jaxb-api.jar but i don't know how common that name actually is so i didn't touch that part
> fix typo in JUnit CMake variable

- org/mozilla/jss/crypto/Cipher.java
- org/mozilla/jss/crypto/SymmetricKey.java
- org/mozilla/jss/pkcs11/PK11Key.java
- org/mozilla/jss/pkcs11/PK11SymKey.java
This extends our interfaces to be compatible with the default JDK
interfaces whenever possible. In particular:
- jss.crypto.SymmetricKey now extends javax.crypto.SecretKey
- jss.pkcs11.PK11Key now implements java.security.Key
A few clarifying comments have been added where necessary.
> Add a few standard Java interfaces when possible

- org/mozilla/jss/tests/TestBufferPRFD.c
Fixes `std::bad_alloc` when building on s390x, where TestBufferPRFD wouldn't exit due to NSS bug. 
> Add exit(1) in failure case of TestBufferPRFD

- org/mozilla/jss/tests/TestBufferPRFD.c
NSS on s390x seems to ignore the semantics of async io/`EWOULDBLOCK`:
rather than retrying the failing write, it drops the data and refuses to
continue. This manifests itself as RSA-based TLS handshakes failing,
because the certificate and associated packets exceeded the size of the
internal buffer (2048).
Bumping the buffer for the tests to 4096 plasters over the issue (so
long as we only include one certificate and not the entire chain).
redhat-bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1730109
> Increase size of async io buffer in TestBufferPRFD

- CMakeLists.txt
This mirrors the behavior of the environment variable, but exposes it as the more standard CMake option so it is a touch more discoverable. 
> Add CHECK_DEPRECATION CMake option

- org/mozilla/jss/pkcs11/PK11KeyPairGenerator.java
- org/mozilla/jss/util/ECCurve.java
~Based on #230. Will be rebased once that gets reviewed and merged.~
The standard Java interface for EC key pair generation only includes a
name. Use the ECCurve enum to resolve this to an OID for use by NSS.
A similar patch was initially proposed by Andrew Helgeson (@ZuluForce)
in upstream issue https://github.com/dogtagpki/jss/issues/226.
> Support ECGenParameterSpec in PK11KeyPairGenerator

- org/mozilla/jss/ssl/callbacks.c
This fixes three things while we're here:
- Misleading indentation
- Trailing whitespace
- Unnecessary NULL checks prior to destroy
Signed-off-by: Alexander Scheel <ascheel@redhat.com>
> Remove misleading indentation in ssl/callbacks.c

- cmake/JSSTests.cmake
- org/mozilla/jss/tests/KeyStoreTest.java
Per report by Magnus Karlsson on pki-devel@redhat.com, `KeyStoreTest` is
bad example code because it doesn't actually work. In particular, it
fails to initialize a `KeyStore` instance correctly (passing only the name
of the provider and not the name of the `KeyStore` type we want).
Fix the test and re-add it to the test suite.
> Add KeyStoreTest back to test suite

- org/mozilla/jss/pkcs11/PKCS11Constants.java
This includes the new `CKM_AES_CMAC` and `CKM_AES_CMAC_GENERAL` constants.
> Add additional PCKS11 Constants

- .travis.yml
- tools/Dockerfiles/fedora_sandbox
This tests the latest upstream NSPR and NSS from Mozilla, on the latest
Fedora rawhide container, and ensures that we can build and pass our
current test suite.
We also add the `fedora_sandbox` image as a required test in Travis. 
> Add Fedora rawhide based sandbox builds

- cmake/JSSConfig.cmake
- tools/common_roots.sh
- tools/run_test.sh.in
This introduces two utilities:
- `run_test.sh`, which gets templated by CMake, allowing you to run a single test after building JSS (in the correct context with all the required libraries and a correct `classpath`). This includes support for running the test under `gdb`.
- `common_roots.sh`, which installs all root certificates trusted by the OS into a local NSS DB.
> Add run_test.sh, common_roots.sh

- org/mozilla/jss/JSSProvider.java
- org/mozilla/jss/crypto/PKCS11Algorithm.java
- org/mozilla/jss/crypto/SymmetricKey.java
- org/mozilla/jss/provider/javax/crypto/JSSSecretKeyFactorySpi.java
- org/mozilla/jss/tests/HmacTest.java
In the course of #259, I wanted to finish creating a `PK11SymKey` from a byte array. In doing so, I realized that, when we specify a [`SecretKeySpec`](https://docs.oracle.com/javase/7/docs/api/javax/crypto/spec/SecretKeySpec.html), we do the import correctly already in our [`SecretKeyFactory`](https://docs.oracle.com/javase/7/docs/api/javax/crypto/SecretKeyFactory.html) implementation, [`JSSSecretKeyFactorySpi`](https://github.com/dogtagpki/jss/blob/master/org/mozilla/jss/provider/javax/crypto/JSSSecretKeyFactorySpi.java). However, what is missing is support for a few newer HMAC variants.
This PR does the following things:
- Finishes adding support for SHA2 variants. This includes adding missing class stubs using the right constants.
- Allows mapping for `SymmetricKey.Usage` to …
> Finish creating SymmetricKeys from byte arrays

- org/mozilla/jss/nss/PRFDProxy.c
- org/mozilla/jss/nss/PRFDProxy.h
- org/mozilla/jss/nss/SSL.c
- org/mozilla/jss/nss/SSL.java
- org/mozilla/jss/nss/SSLFDProxy.java
- org/mozilla/jss/tests/TestBufferPRFD.java
- org/mozilla/jss/tests/TestRawSSL.java
- org/mozilla/jss/util/java_ids.h
Off of a SSL-enabled `PRFileDesc` created by NSS's `SSL_ImportFD`, we might
want to store various information which would be helpful (and, necessary
to free at the end):
- Any `TrustManager`s we're using on this connection,
- Whether or not the handshake has finished,
- The client certificate, or
- Additional parameters required for NSS callbacks.
Some of these will be Java-backed values, in which case they should be
added directly to `SSLFDProxy`. Others will be C-backed values, in which
case they should be freed once the SSL Socket is closed.
> Add SSL Storage class, SSLFDProxy

- org/mozilla/jss/CryptoManager.java
- org/mozilla/jss/InitializationValues.java
We're previously given the option to either install the JSS provider or
not, and optionally to remove the Sun Provider. Users can re-order the
providers later if they want, but the most common other option will be
to only use JSS for specified operations. To achieve this, we put JSS as
the very last provider. Hence, add:
installJSSProviderFirst = true
as a new value in InitializationValues.
> Support favoring other Cryptographic Providers

- org/mozilla/jss/util/jssutil.c
- org/mozilla/jss/util/jssutil.h
Sometimes we have only a single `CERTCertificate` but wish to inquire
about as much of its chain as we can, and return the result as a
`jobjectArray` to pass back to Java. This is helpful when we've gotten a
`CERTCertificate` from NSS and we need to check it against a `TrustManager`
instance.
> Wrap a certificate with chain to jobjectArray

- org/mozilla/jss/util/jss_exceptions.h
- org/mozilla/jss/util/jssutil.c
- org/mozilla/jss/util/jssutil.h
Often we'll need to take a `PRErrorCode` and raise it as a Java Exception
(via the JNI interface) of the proper type. Other times, we'll need to
take a raised Java Exception and return it as the correct
(`SECStatus`, `PRErrorCode`) pair.
We introduce `JSS_ExceptionToSECStatus` and `JSS_SECStatusToException` to
handle this. The latter has a *Message form, which takes an error
message to raise with the exception.
> Capture PRErrorCode <-> Exception mappings

- lib/jss.map
- org/mozilla/jss/CertificateUsage.java
- org/mozilla/jss/CryptoManager.java
- org/mozilla/jss/PK11Finder.c
- org/mozilla/jss/tests/X509CertTest.java
ImportDERCert differs from other calls in that it allows importing a
certificate temporarily, without putting it in the permanent trust
store. This lets you import (and trust) an intermediate CA certificate
without permanently storing it, and use it to validate a leaf
certificate.
> Add CryptoManager.ImportDERCert(...)

- org/mozilla/jss/CryptoManager.java
- org/mozilla/jss/PK11Finder.c
We extend the existing VerifyCertificate logic to include support for
validating a certificate by reference (e.g., an instance of
X509Certificate) instead of purely by nickname.
We also expose the value of ocspPolicy from the CryptoManager (instead
of the ordinal, which we'd have to convert back to an enum for most
calls).
> Validate X509Certificates from CryptoManager

- org/mozilla/jss/ssl/callbacks.c
In 871231d20f6e6956134c670d57087f121ffe0563 I incorrectly handled an
unused variable warning, where rc is unused when compiling outside of
debug mode. As part of this fix, I incorrectly returned based on the
same values we were asserting -- for 3 of the 4 values. Instead, I
should've returned when these conditionals were negated.
Candidate to backport to `v4.5.x`. Not necessary to backport to `v4.4.x` to my knowledge. 
@geetikakay Do you mind checking the resulting build to see if this happens to fix the SSLAlert issue you were mentioning in a [previous BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1733651)?
> Fix callback alert handling

- tools/Dockerfiles/fedora_sandbox
Since we're building NSS in debug mode by default, we should also build
JSS in debug mode here. This will be our only build with CMake release
type DEBUG and debug CFLAGS.
> Make sandbox build fully debug

- CMakeLists.txt
- cmake/JSSConfig.cmake
- cmake/JSSTests.cmake
- org/mozilla/jss/JSSProvider.java
- org/mozilla/jss/crypto/Algorithm.c
- org/mozilla/jss/crypto/Algorithm.h
- org/mozilla/jss/crypto/Algorithm.java
- org/mozilla/jss/crypto/CMACAlgorithm.java
- org/mozilla/jss/crypto/PKCS11Algorithm.java
- org/mozilla/jss/pkcs11/PK11MessageDigest.java
- org/mozilla/jss/provider/javax/crypto/JSSMacSpi.java
- org/mozilla/jss/tests/TestCmac.java
~This is WIP as it depends on #258 being merged. This series will be rebased afterwards. The commits will be squashed and rewritten.~
This adds initial support for CMAC to the JSS Provider interface. This depends on a recent enough NSS that includes [CMAC](https://bugzilla.mozilla.org/show_bug.cgi?id=1570501) support in PKCS#11. ~Thus CI will fail until I introduce a new instance with Sandboxed NSS builds.~
I've added build time support for CMAC. What this means is that JSS only needs a rebuild in order to take advantage of CMAC support in NSS. Otherwise, it'll ignore the non-existence of CMAC and not run the applicable test from the test suite. CMAC will still be defined in the JSS provider though.
You can see this via checking the output of CI: currently there are 66 tests without CMAC, …
> Add CMAC to JSS

- org/mozilla/jss/provider/javax/crypto/JSSMacSpi.java
`JSSMacSpi` differs from `JSSCipherSpi` in that it requires the caller to
pass a `SecretKeyFacade` instance (which merely wraps a `SymmetricKey`) and
are typically created by `SecretKeyFactory`. However, the caller might
have an existing `SymmetricKey` and wish to use that with `JSSMacSpi`; check
for that case and handle it gracefully. Unlike `JSSCipherSpi`, we don't
use the `SecretKeyFactory` to clone the underlying key.
> Support using SymmetricKey in JSSMacSpi

- lib/jss.map
- org/mozilla/jss/nss/SSL.c
- org/mozilla/jss/nss/SSL.java
- org/mozilla/jss/nss/SSLFDProxy.c
- org/mozilla/jss/nss/SSLFDProxy.h
- org/mozilla/jss/nss/SSLFDProxy.java
- org/mozilla/jss/tests/TestBufferPRFD.java
- org/mozilla/jss/util/java_ids.h
This PR adds support for SSL client certificates in `org.mozilla.jss.nss`, which will eventually enable their use in the SSLEngine (#150). In particular, we:
- Add a new field to `SSLFDProxy`, `clientCert`,
- Add a setter,
- Add a new callback, `JSSL_SSLFDCertSelectionCallback` which returns the single cert we've already selected for use. 
Later enhancements can add other certificate selection mechanisms, but this should interact well with our current SSLEngine design.
> SSL Client Certificates

- lib/jss.map
- org/mozilla/jss/CryptoManager.c
- org/mozilla/jss/CryptoManager.java
- org/mozilla/jss/nss/Buffer.c
- org/mozilla/jss/nss/BufferProxy.java
- org/mozilla/jss/nss/PR.c
- org/mozilla/jss/util/NativeProxy.java
- org/mozilla/jss/util/jssutil.c
- org/mozilla/jss/util/jssutil.h
I thought about this while I was implementing SSLAlert handling, so I figured I'd attempt it here.
We extend the default NativeProxy implementation in three directions:
- Make it `AutoCloseable`,
- Add a `clear()` method which supports clearing the value of the
pointer without calling `releaseNativeResources(...)`, and
- Save a stack trace when assertions are enabled.
By implementing `AutoCloseable`, we enable the common Java pattern of
try-with-resources:
try (NativeProxy item = ...) {
...
}
and have the item automatically be closed (in our case, `finalized(...)`)
at the end of its life cycle. We've added additional logic to prevent
double-free bugs.
Additionally, by adding `clear(...)`, we both add protection from
double-free bugs and enable resource cleanup from native handlers that …
> Native proxy improvements

- CMakeLists.txt
- cmake/JSSConfig.cmake
- cmake/Shims.cmake
On CMake versions less than 3.12.0 (shipped July 17, 2018), the
`list(...)` helper lacks the `JOIN` subcommand. We use this for joining the
C compiler flags into `CMAKE_REQUIRED_FLAGS` for symbol detection.
This introduces a shim for older systems lacking these useful macros,
including RHEL 8.
> Fix build on older CMake versions

- org/mozilla/jss/pkcs11/PK11MessageDigest.c
This `ASSERT_OUTOFMEM(env)` is incorrect for two reasons:
1. When `JSS_RefByteArray` detects a zero-length result, it returns
false but doesn't throw an exception. It is up to the caller to
handle that as they wish. In our case, we can safely skip the
`PK11_DigestOp` call.
2. When `length < offset+len` (and `JSS_RefByteArray` exits
successfully), we won't have thrown an exception.
This only shows up in debug builds; release builds aren't affected.
This bug was detected by CI after merging the CMAC changes (#259).
> Remove unnecessary assert in PK11MessageDigest.c

- org/mozilla/jss/tests/BadSSL.java
badssl.com maintains a number of subdomains with valid and invalid TLS
configurations. A number of these test certificates which fail in
certain scenarios (revoked, expired, etc). Add a test runner which
validates SSLSocket's implementation against badssl.com.
> Add optional test case against badssl.com

- cmake/JSSConfig.cmake
- jss.spec
This version of JSS has a security fix:
- CVE-2019-14823: Fix root certificate validation when using Leaf and
Chain OCSP mode
This version of JSS also has a few enhancements over v4.6.1:
- Fixing JSS internal deprecation warnings by @emaldona
- Fixing javadoc builds by @stanislavlevin
- Introduce a new InitializationValue, installJSSProviderFirst, to
support favoring other cryptographic providers.
- Add support for CMAC as a Mac algorithm from JSSProvider; note that
this requires JSS to be compiled with a NSS release which also
supports CMAC (3.47+).
- Various improvements to the Key APIs.
Thanks to everyone who contributed to this release!
> Release v4.6.2

- cmake/JSSConfig.cmake
- jss.spec
This version of JSS has a security fix:
- CVE-2019-14823: Fix root certificate validation when using Leaf and
Chain OCSP mode. Note that unlike the v4.6.x or v4.4.x series, the
previous v4.5.3 release was not impacted.
This version of JSS also has a few enhancements over v4.5.3:
- Backporting @Dessa's JUnit CMake typo fix
- Adding HSM support for PKCS#11 AES KeyWrap/Padding (by @ladycfu)
- OCSP checking for leaf and chain (by @jmagne)
Thanks to all who contributed to this release!
> Release v4.5.4

- org/mozilla/jss/ssl/SSLAlertEvent.java
- org/mozilla/jss/ssl/callbacks.c
These three commits are various improvements we'd like for `SSLAlertEvent`. `SSLAlertEvent` is a subclass of [`java.util.EventObject`](https://docs.oracle.com/javase/8/docs/api/java/util/EventObject.html). 
- A [common pattern](https://github.com/dogtagpki/pki/blob/master/base/server/src/org/dogtagpki/server/PKIClientSocketListener.java#L106-L109) in PKI is to enable the `SSLAlert` handler for a `SSLSocket`, and then read the parameters via their Enums instead of directly from their int values. I think we might as well store the Enums on the alert when we can. 
- We simplify construction such that we only need one JNI call (the constructor) instead of three (constructor, `setLevel`, and `setDescription`).
- We use the simplified constructor.
- We also let the `SSLAlertEvent` store …
> SSLAlertEvent enhancements

- lib/jss.map
- org/mozilla/jss/util/GlobalRefProxy.c
- org/mozilla/jss/util/GlobalRefProxy.h
- org/mozilla/jss/util/GlobalRefProxy.java
- org/mozilla/jss/util/java_ids.h
Java JNI has the notion of a global reference to an object, instead of
the traditional local reference created by the JVM when calling any
JNI'd function. Since all global references have the same type (`jobject`)
and release handler (`(*env)->DeleteGlobalRef(...)`), it makes sense to
track these as a single JNI type.
This ensures that these resources are released, allowing the referenced
object to be garbage collected.
> Introduce GlobalRefProxy

- README.md
- docs/dependencies.md
With the advent of JDK 11+ being the default JDK in Debian testing,
we should stop suggesting that JDK 8 is the only supported JDK for JSS.
Since we are compatible with JDK 8+ and Debian provides a default-jdk
installation target, use that instead.
This change was suggested by @emaldona.
> Switch to suggesting default-jdk

- org/mozilla/jss/netscape/security/pkcs/PKCS10.java
The PKCS10.print() has been modified to remove the extra blank
line before the PEM request footer.
> Fixed PKCS10.print()

- org/mozilla/jss/util/NativeProxy.java
In eb5df01003d74b57473eacb84e538d31f5bb06ca, I introduced a bug by
setting `mPointer` after trying to add `NativeProxy` to the registry. In
most instances this won't matter, however, if another instance exists in
the `HashSet` with the same hash value, the equals comparator will be
used, triggering a NPE.
> Fix NativeProxy reference tracker

- cmake/FindNSPR.cmake
- cmake/FindNSS.cmake
- cmake/JSSTests.cmake
- tools/run_test.sh.in
Previously, we wouldn't include `NSS_LIBRARIES` in `LD_LIBRARY_PATH`, in part because it wasn't always a directory -- sometimes it was a path to a the library.
This fixes sandbox builds when NSS isn't installed on the system, or when the sandboxed NSS otherwise rejects the system NSS's library versions.
> Fix sandbox builds of JSS

- org/mozilla/jss/JSSProvider.java
- org/mozilla/jss/provider/javax/crypto/JSSKeyGeneratorSpi.java
`SecretKeyFactory` previously saw improvements for HMAC/SHA-2, but these
changes were missed for the `KeyGenerator` facility. Add the missing SHA-2
based algorithms in.
> Add support for HMAC/SHA-2 KeyGenerator

- org/mozilla/jss/CRLImportException.java
- org/mozilla/jss/CertDatabaseException.java
- org/mozilla/jss/KeyDatabaseException.java
- org/mozilla/jss/NoSuchTokenException.java
- org/mozilla/jss/asn1/FieldNotPresentException.java
- org/mozilla/jss/crypto/AlreadyInitializedException.java
- org/mozilla/jss/crypto/BadPaddingException.java
- org/mozilla/jss/crypto/InvalidDERException.java
- org/mozilla/jss/crypto/InvalidKeyFormatException.java
- org/mozilla/jss/crypto/KeyAlreadyImportedException.java
- org/mozilla/jss/crypto/NoSuchItemOnTokenException.java
- org/mozilla/jss/crypto/ObjectNotFoundException.java
- org/mozilla/jss/crypto/PQGParamGenException.java
- org/mozilla/jss/crypto/TokenException.java
- org/mozilla/jss/crypto/TokenRuntimeException.java
- org/mozilla/jss/netscape/security/pkcs/EncodingException.java
- org/mozilla/jss/netscape/security/pkcs/ParsingException.java
- org/mozilla/jss/netscape/security/x509/GeneralNamesException.java
- org/mozilla/jss/netscape/security/x509/InvalidIPAddressException.java
- org/mozilla/jss/netscape/security/x509/InvalidNetmaskException.java
- org/mozilla/jss/netscape/security/x509/X509ExtensionException.java
- org/mozilla/jss/pkcs11/PK11Exception.java
- org/mozilla/jss/util/AssertionException.java
- org/mozilla/jss/util/IncorrectPasswordException.java
- org/mozilla/jss/util/InvalidNicknameException.java
- org/mozilla/jss/util/NotImplementedException.java
For all exceptions in JSS, this modernizes them to bring parity with the
exception they drive from. In particular, this adds the form
Exception(String message, Throwable cause)
and
Exception(Throwable cause)
and
Exception(String mesg, Throwable cause,
boolean enableSuppression,
boolean writableStackTrace)
where missing.
Resolves: GitHub issue #264
> Modernize Exception Constructors

- tools/Dockerfiles/ubuntu_jdk8
This should address the issue in CI caused by the older NSS version:
Exception in thread "main" java.lang.RuntimeException: Unknown key type: expected the public key of an EC key to be an PK11ECPublicKey; got: null
at org.mozilla.jss.pkcs11.PK11ECPrivateKey.getParams(PK11ECPrivateKey.java:30)
at org.mozilla.jss.tests.X509CertTest.testKeys(X509CertTest.java:158)
at org.mozilla.jss.tests.X509CertTest.testEC(X509CertTest.java:88)
at org.mozilla.jss.tests.X509CertTest.main(X509CertTest.java:75)
> Migrate from ubuntu:latest to ubuntu:rolling

- org/mozilla/jss/pkcs11/PKCS11Constants.java
- tools/build_pkcs11_constants.py
PKCS#11 includes several constants with the `CK_` prefix, including
`CK_TRUE`, `CK_FALSE`, `CK_INVALID_HANDLE`, and others. With PKCS#11 v3.0 in
draft state, this namespace also includes various SP800-108 (KBKDF)
specific constants. We need a blacklist to handle certain function
pointer macros, but otherwise import all `CK_` constants that we can.
> Support CK_ prefixed PKCS#11 constants

- cmake/JSSCommon.cmake
- cmake/JSSConfig.cmake
`javac` supports parsing options from a file using the `@/path/to/arguments`
syntax. This lets us pass all of our sources to `javac` in a single file
(containing all of the Java files we wish to build in this pass) instead
of passing them individually on the command line. This reduces the size
of the output significantly when there's an error in the build.
> Move javac command to file lists

- .travis.yml
- tools/Dockerfiles/fedora_27
- tools/Dockerfiles/fedora_28
- tools/Dockerfiles/fedora_29
- tools/Dockerfiles/fedora_30
- tools/Dockerfiles/fedora_31
Remove Fedora 29 image and introduce Fedora 31 now that Fedora 29 is end of life.
Also migrates to using the correct COPR repo, though this should be unnecessary except for pulling more recent build dependencies.
> Add Fedora 31 Image

- org/mozilla/jss/crypto/RSAParameterSpec.java
- org/mozilla/jss/pkcs11/PK11KeyPairGenerator.java
Java provides the `java.security.spec.RSAKeyGenParameterSpec` that is the
same as our `RSAParameterSpec`, sans casing on one function call. Update
`RSAParameterSpec` to extend `RSAKeyGenParameterSpec` for backwards
compatibility and let `PK11KeyPairGenerator` use `RSAKeyGenParameterSpec`
instead.
--- 
This gets tested through the existing test cases, so I think it should be fine. Also note that PKI doesn't actually use this class. Go figure.
> Allow `PK11KeyPairGenerator` use of `RSAKeyGenParameterSpec`

- cmake/JSSTests.cmake
- org/mozilla/jss/tests/SymKeyDeriving.java
`SymKeyDeriving` tests `PK11SymmetricKeyDeriver`, which uses
`PK11_Derive(...)`. We remove the old single DES test and re-add it to the
test suite, cleaning it up in the process.
> Cleanup SymKeyDeriving and re-add to test suite

- org/mozilla/jss/util/NativeEnclosure.c
- org/mozilla/jss/util/NativeEnclosure.h
- org/mozilla/jss/util/NativeEnclosure.java
- org/mozilla/jss/util/NativeProxy.java
- org/mozilla/jss/util/StaticVoidPointer.c
- org/mozilla/jss/util/StaticVoidPointer.h
- org/mozilla/jss/util/StaticVoidPointer.java
- org/mozilla/jss/util/java_ids.h
A `NativeEnclosure` is an abstract class which stores a `NativeProxy`
instance and wraps both the pointer and the size of the memory pointed
to by said pointer. When used in combination with `StaticVoidPointer`, a
pointer which isn't tracked and freed like the usual `NativeProxy` is,
this can be used as a form of serialization, especially for converting
parameters to and from the JNI layer.
> Introduce NativeEnclosure and StaticVoidPointer

- lib/jss.map
- org/mozilla/jss/pkcs11/attrs/CKAClass.java
- org/mozilla/jss/pkcs11/attrs/CKAKeyType.java
- org/mozilla/jss/pkcs11/attrs/CKAUsage.java
- org/mozilla/jss/pkcs11/attrs/CKAValueLen.java
- org/mozilla/jss/pkcs11/attrs/CKAttribute.c
- org/mozilla/jss/pkcs11/attrs/CKAttribute.h
- org/mozilla/jss/pkcs11/attrs/CKAttribute.java
The new class `org.mozilla.jss.pkcs11.attrs.CKAttribute` represents a
single PKCS#11 `CK_ATTRIBUTE` in Java. These attributes can be serialized
to the native layer (via `NativeEnclosure`). Each attribute is handled in
a derived class. Currently four types of attributes are supported:
- `CKA_CLASS` in `jss.pkcs11.attrs.CKAClass`
- `CKA_KEY_TYPE` in `jss.pkcs11.attrs.CKAKeyType`
- `CKA_{ENCRYPT,DECRYPT,...}` usage attributes in
`jss.pkcs11.attrs.CKAUsage`
- `CKA_VALUE_LEN` in `jss.pkcs11.attrs.CKAValueLen`
These attributes are useful for constructing key templates for
additional derived keys in PKCS#11's NIST SP800-108 KBKDF interface.
> Add CK_ATTRIBUTE classes

- org/mozilla/jss/JSSProvider.java
- org/mozilla/jss/crypto/Algorithm.c
- org/mozilla/jss/crypto/Algorithm.h
- org/mozilla/jss/crypto/Algorithm.java
- org/mozilla/jss/crypto/KeyGenAlgorithm.java
- org/mozilla/jss/crypto/SymmetricKey.java
- org/mozilla/jss/pkcs11/PK11SymKey.java
- org/mozilla/jss/provider/javax/crypto/JSSSecretKeyFactorySpi.java
Unlike other key types, a `CKK_GENERIC_SECRET` isn't limited to a single
algorithm. This requires support in JSS Provider for such keys.
This also refactors handling of `SecretKey.Type` to map them to
`jss.pkcs11.KeyTypes`.
> Add Generic Secret key type

- .classpath
- README.md
- cmake/JSSConfig.cmake
- docs/dependencies.md
- docs/using_jss.md
- jss.spec
- org/mozilla/jss/netscape/security/pkcs/PKCS12Util.java
- org/mozilla/jss/netscape/security/pkcs/PKCS7.java
- org/mozilla/jss/netscape/security/util/Utils.java
- org/mozilla/jss/tests/ChainSortingTest.java
- org/mozilla/jss/tests/X509CertTest.java
- tools/Dockerfiles/fedora_29_jdk11
- tools/Dockerfiles/fedora_rawhide
- tools/Dockerfiles/fedora_sandbox
Since Base64 is included in the standard library since JDK 8, the
minimum JDK version JSS `master` supports, and we already have hex
encoding in `netscape.security.utils.Utils`, we can drop all of our
dependencies on Apache Commons Codec fairly easily. Doing so reduces the
footprint of the JSS library and otherwise is beneficial since there's
likely to be little need for it in the future.
> Drop Apache Commons Codec Dependency

- org/mozilla/jss/nss/PR.java
- org/mozilla/jss/tests/TestRawSSL.java
`SSLFDProxies` might have additional resources associated with them
besides just the `PRFileDesc` pointer. This form of `PR.Close(...)` will
first close the underlying `PRFileDesc` and then call `fd.close()`
explicitly, to handle any other resources.
@edewata Does this generally look like a sane decision? SSL-wrapped `PRFileDesc`'s otherwise behave like  `PRFileDesc`'s, since they implement the `PRFileDesc` interface thingy; you'd mostly interact with their fd-facing portion with NSPR calls. Only the SSL-specific stuff (cipher types, callbacks, &c) are handled by NSS. We're looking to do something similar, except at a higher level. Since we can't give NSS data to hold (and have a callback process freeing that data when `PR_Close(...)` is called on the underlying socket), we have to attach …
> Support freeing SSLFDProxy resources

- org/mozilla/jss/crypto/KBKDFByteArrayParam.java
When a `KBKDFByteArray` parameter is re-used, it can't be zeroed as this
destroys the value. Instead, add a method to explicitly zero the
parameter when necessary.
> Add method to zero KBKDFByteArray Parameter

- org/mozilla/jss/crypto/HMACAlgorithm.java
This enables the new KBKDF mechanisms to specify the underlying MAC
algorithm by using high-level instances (of `CMACAlgorithm` and
`HMACAlgorithm`). However, all of these need to be PKCS#11 interface and
can't be `SEC_OID`s.
---
Note that `CKM_*_HMAC` were already added to `Algorithm.{c,Java}`, so this just switches over to using it.
> Switch SHA2/HMAC to PKCS#11 interface

- cmake/JSSTests.cmake
NSS currently has partial support for TLS 1.3 in FIPS mode; this is
broken when doing a debug, sandbox build due to various internal
asserts triggering. Disable this test for now.
> Fix FIPS-mode TLS tests with NSS sandbox build

- org/mozilla/jss/netscape/security/pkcs/PKCS7.java
- org/mozilla/jss/netscape/security/util/Utils.java
`jss.netscape.security.util.Utils.base64decode` previously could accept
MIME-encoded Base64 because Apache Commons Codec didn't care about the
difference. In 8de4440c5652f6f1af5b4b923a15730ba84f29e1, support was
erroneously removed. This commit re-introduces support.
> Handle MIME-encoded Base64 in base64decode

- org/mozilla/jss/CryptoManager.c
When the `CryptoManager` fails to initialize, we throw an exception. This
should include the underlying NSS error, when available, so use
`JSS_throwMsgPrErr` instead of `JSS_throwMsg`.
> Pass NSS error on CryptoManager initialization

- org/mozilla/jss/tests/SSLClientAuth.java
TLS 1.3 client authentication is broken in NSS when run under FIPS mode.
Bound the maximum TLS version number to TLS 1.2 until this is fixed.
> Workaround: NSS FIPS-mode TLS 1.3 Client Auth

- lib/jss.map
- org/mozilla/jss/crypto/Policy.c
- org/mozilla/jss/crypto/Policy.java
- org/mozilla/jss/pkcs11/PK11KeyPairGenerator.java
- org/mozilla/jss/tests/JCAKeyWrap.java
- org/mozilla/jss/tests/JCASigTest.java
- org/mozilla/jss/tests/SigTest.java
Note that this doesn't update EC (to support limiting curves) or DSA or DH -- only RSA at this point in time.  One of the issues with DSA is that NSS only supports up to 1024-bit DSA key generation, but policy requires at least 2048 bits! To fix this, we need to switch to the NSS PQG v2 API instead of the v1 API. 
---- 
Add `jss.crypto.Policy` to reflect local policy
This queries NSS for a few policy suggestions so that applications using
JSS can begin obeying local system policy.
----
Update RSA key generation to obey local policy
This uses the newly added `jss.crypto.Policy` class to validate local
parameter selection against what the system policy enforces. In
particular, this allows for validating the exponent (currently a …
> Minimum RSA Key Sizes

- cmake/JSSTests.cmake
When `KeyStoreTest` accesses a NSS DB with another program writing
temporary keys, those keys may not have an ID yet, resulting in an
assertion failure in debug mode.
In order to prevent this from failing the test suite, `KeyStoreTest` needs
to depend on every single other test that accesses the key store, to
prevent concurrent access.
This happens with both `KeyStoreTest` and `JSSProvider`.
> Fix ordering of KeyStoreTest

- .github/workflows/optional.yml
- .github/workflows/required.yml
This fully replaces our `.travis.yml` configuration. After this, we can remove Travis from JSS if we desire.
Thoughts? I didn't look closely at matrix like features (like we have in our Travis script) but we could if desired.
I also didn't look to see if there was a better way to annotate failed (optional) tests. You can see this in the PKCS#11 Constants test: it displays a little warning when you expand the "Build and Run the Docker Image" step, but other than that, there's no obvious way to see that the optional job "failed" (while still reporting it succeeds to GitHub...). These are more informative than required jobs. 
> Add GitHub actions for required jobs

- org/mozilla/jss/ssl/SSLAlertDescription.java
- org/mozilla/jss/ssl/SSLAlertEvent.java
When using `SSLAlertEvents` inside an `SSLEngine`, we need to raise a
`SSLException` of the correct type. There's one issue here though:
While we could add support for telling if this is an inbound or
an outbound alert, we don't know _what_ caused said alert (because
NSS created it) -- an issue on the client or an issue on the server.
This means that we can't report a `SSLKeyException` and only report
`SSLProtocolExceptions`.
Considering NSS is the one sending the alert, and we're just exposing
it happened to the calling `SSLEngine`, this is a fine trade-off.
--- 
Note that most of the time that a `SSLKeyException` would occur, it could've been detected sooner, when the key is provided to the `SSLEngine` itself and raised as an …
> Enable SSLAlertEvent to raise SSLExceptions

- lib/jss.map
- org/mozilla/jss/nss/SSL.c
- org/mozilla/jss/nss/SSL.java
- org/mozilla/jss/nss/SSLFDProxy.c
- org/mozilla/jss/nss/SSLFDProxy.h
- org/mozilla/jss/nss/SSLFDProxy.java
- org/mozilla/jss/tests/TestBufferPRFD.java
- org/mozilla/jss/util/jssutil.c
This PR enables asynchronous access to SSL Alerts events from NSS. When the `JSSL_SSLFDAlertReceivedCallback` callback is triggered, it looks up the `inboundAlerts` member of the `SSLFDProxy` and appends the new alert.
> SSL Alert Handling

- org/mozilla/jss/CryptoManager.c
- org/mozilla/jss/nss/SSLFDProxy.c
- org/mozilla/jss/util/GlobalRefProxy.c
In JSS, a `GlobalRefProxy` stores a JNI global `jobject` reference, to allow
Java to clean it up later. This allows us to pass the ref to a NSS SSL
callback, assuming we promise to clean it up later (and not clean it up
before NSS is done with it!).
This fixes various issues with the handling of global references:
- We needn't clear the value on successful storage, as we intend to
continue using said reference.
- We need to validate that the ref isn't `NULL`, when created.
- We need to validate JSS_javaVM is non-`NULL` (so we can extract a
JNI ENV reference).
-----
Aside: It turns out that handling of inbound/outbound alerts only impact alerts received after the handshake has completed. This is a small subset of fatal alert scenarios …
> Fix handling of global_ref_proxy

- org/mozilla/jss/ssl/javax/JSSParameters.java
`SSLParameters` and `SSLEngine` impose an interesting duality between the
"want client auth" and "need client auth" options: they're mutually
exclusive (and setting one clears the other). This wasn't correctly
handled in `JSSParameters` because NSS has a different notion: requesting
peer auth and requiring peer auth.
Fix `JSSParameters` to align better with Java's expectations.
> Fix client auth handling in JSSParameters

- lib/jss.map
- org/mozilla/jss/nss/SSL.c
- org/mozilla/jss/nss/SSL.java
- org/mozilla/jss/provider/javax/crypto/JSSNativeTrustManager.java
~Opening this as a WIP PR. This PR is fairly self-contained unlike #248.~
This approach assumes we wish to use the already-existing OCSP validation logic in [`JSSL_DefaultCertAuthCallback`](https://github.com/dogtagpki/jss/blob/master/org/mozilla/jss/ssl/callbacks.c#L464). To do so we add a dummy TrustManager class which doesn't do validation, but which we can use in the SSLEngine as a sentinel for using this validation (note that we can use `NULL` to use the default NSS certificate validation, which is again something different, or use `NULL` to choose a sane default and create a separate class for default NSS validation). 
The upside of this PR is that it doesn't involve invoking Java from the NSS callback, which means it is more performant than other solutions. All other solutions …
> Native TrustManager

- org/mozilla/jss/pkcs11/PK11Cipher.java
> Clarify expected vs actual key types in PK11Cipher

- org/mozilla/jss/nss/PR.c
NSPR behaves much like the C standard library's `errno`; unless the value
is cleared, it is hard to tell if an exception occurred in this call.
Because these are relatively unopinionated bindings over NSPR's calls,
clear the error message rather than making the caller do so (and incur
another JNI penalty).
---
Pulled out of #150.
> Clear errors before executing most NSPR calls

- org/mozilla/jss/provider/javax/crypto/JSSKeyManager.java
Expose functionality of `CryptoManager` in `JSSKeyManager`, allowing the
caller to fetch a certificate by alias (NSS DB's nickname).
---
Pulled out of #150.
> Fetch certificate by alias in JSSKeyManager

- org/mozilla/jss/netscape/security/util/Utils.java
Apache Commons Codec's base64 parser will happily return invalid,
nonsensical base64 data. Add logging to `Utils` to catch these inputs,
and return an empty data array. This makes `Utils.base64decode(...)` behave
like Apache Commons Codec (in that it doesn't raise an exception), but
diverges in behavior since Base64 blobs with invalid prefixes will
return empty data, a safer alternative than continuing to parse and
returning garbage.
> Log invalid Base64 and return empty data

- org/mozilla/jss/nss/PR.c
- org/mozilla/jss/nss/SSL.c
- org/mozilla/jss/pkcs11/PK11Cipher.c
- org/mozilla/jss/ssl/javasock.c
Reported by @c42-arthur in #371.
`PK11Cipher`'s `updateContext` leaks a reference to the input byte array, a
potentially highly-used method depending on the application. This fixes
that memory leak and audits the rest of JSS for similar leaks, fixing
two in the NSPR and NSS SSL bindings.
The case in `ssl/javasock.c` is at worst a `memcpy` of a `NULL` variable, which
should fail where it to be hit.
Resolves: #371
> Fix memory leaks around Array handling

- CMakeLists.txt
- cmake/JSSTests.cmake
- docs/build_system.md
Introduces the `TEST_VALGRIND` option to run the entire test suite under
Valgrind. This is exceedingly slow and reports lots of false positives
due to the way the JVM exits (and restrictions on the Cryptographic
Provider interface making shutting down NSS hard).
> Add option to run test suite under Valgrind

- org/mozilla/jss/crypto/Policy.java
- org/mozilla/jss/ssl/SSLVersion.java
- org/mozilla/jss/ssl/SSLVersionRange.java
This lets users inquire about the supported TLS versions of their local
system policy, when applicable. Internally, this will be used by
`SSLEngine` to facilitate compliance with local policy.
When local policy isn't available, default to a range of
`[TLSv1.0, max(SSLVersion)]`.
> Add SSLVersionRange to crypto.Policy

- org/mozilla/jss/crypto/Policy.java
- org/mozilla/jss/pkcs11/PK11KeyPairGenerator.java
Because cdfed4e1e079130eb5fd94c8ff5936007b1668bb was technically a
breaking change for some applications, make its enforcement
configurable. This currently defaults to false; so applications wishing
to enable strict enforcement must opt-in by changing the value of
`org.mozilla.jss.crypto.Policy.ENFORCING_KEY_SIZES` to `true`.
> Make key size enforcement optional

- lib/jss.map
- org/mozilla/jss/ssl/SSLCipher.c
- org/mozilla/jss/ssl/SSLCipher.java
This allows consumers of `SSLCipher` to know whether or not a given
cipher suite is supported in various conditions:
- With TLSv1.3, or
- In FIPS mode, or
- With RSA or ECDSA certificates.
---- 
@edewata This doesn't quite bring full crypto-policies compliance, just FIPS compliance. I'm not sure how to do the former.
> Track SSLCipher supported status

- org/mozilla/jss/pkcs11/PKCS11Constants.java
See also corresponding Mozilla bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1611209
> Swap CKM_AES_CMAC and CKM_AES_CMAC_GENERAL values

- org/mozilla/jss/ssl/javasock.c
Reported by Scott Straw and Andrew Helgeson at Code42.
> Handle OOM in javasoc.c with exception

- org/mozilla/jss/ssl/SSLCipher.c
I've tested this under various policies with #150 and it appears to behave as expected.
- LEGACY
- DEFAULT
- NEXT
- FUTURE
Though there are still a few handshake errors in LEGACY that leave stuff to be desired. 
> Use CipherPolicyGet instead of GetCipherSuiteInfo

- org/mozilla/jss/ssl/SSLVersion.java
This constant was already in `SocketBase`, but wasn't tracked by the `SSLVersion` enum.
> Add SSLv2 to SSLVersion

- org/mozilla/jss/ssl/SSLServerSocket.java
- org/mozilla/jss/ssl/SSLSocket.java
`SSLSocket` and `SSLServerSocket` "mask" the cause of certain exceptions,
which results in less clear error messages.
> Track the root cause of SSLSocket exceptions

- .github/workflows/optional.yml
- tools/Dockerfiles/fedora_latest_jdk11
This'll ensure we're testing with a newer JDK version, as F29 is no longer maintained. 
> Migrate CI from F29 to latest for JDK11 builds

- org/mozilla/jss/ssl/SSLCipher.java
Each `SSLCipher` may only be supported in a restricted subset of
scenarios. This helps with testing and more verbose error messages
from SSLEngine.
Task List: 
The last item likely needs to be done in a container on a non-RHEL/non-Fedora platform to ensure crypto-policies doesn't mess with the results. 
> Expose supported protocol versions in SSLCipher

- org/mozilla/jss/ssl/SSLCipher.c
Mimic the behavior in NSS's `ssl3_config_match_init` to ensure we limit
ourselves to ciphers that NSS will actually negotiate. In particular,
validate that there exists a token that could perform the given
authentication, hash, or key type if it was required of us.
This largely mimics code in NSS's `ssl3con.c`.
> Advanced SSLCipher feature detection

- cmake/JSSCommon.cmake
- cmake/JSSConfig.cmake
With the introduction of proper logging support (and subsequent removal
of the Release/Debug split) and splitting of source lists between those
in the JSS release and those in the JSS tests, we have removed the need
for `JSS_PACKAGES`.
This introduces javadocs for all packages which are part of the shipped
JSS4 JAR.
> Remove JSS_PACKAGES

- docs/usage/kbkdf.md
This adds documentation for KBKDF changes in #306. Both usage and design documentation.
View rendered documentation [here](https://github.com/cipherboy/jss/blob/kbkdf-documentation/docs/usage/kbkdf.md). 
> Add KBKDF Documentation

- org/mozilla/jss/CryptoManager.java
JSS master branch has changed to prefer a dynamic approach to finding
libjss4.so: use the value of -Djava.library.path and then fallback to
hard-coded paths if the native portion of JSS isn't found. Update the
JSS v4.4.x code to follow this behavior.
Resolves: rh-bz#1796642
> Change to dynamic-first libjss4.so linking

- org/mozilla/jss/pkcs11/PK11DSAPrivateKey.java
- org/mozilla/jss/pkcs11/PK11ECPrivateKey.java
- org/mozilla/jss/pkcs11/PK11RSAPrivateKey.java
- org/mozilla/jss/provider/java/security/JSSKeyPairGeneratorSpi.java
- org/mozilla/jss/provider/java/security/JSSSignatureSpi.java
- org/mozilla/jss/provider/javax/crypto/JSSCipherSpi.java
- org/mozilla/jss/provider/javax/crypto/JSSKeyGeneratorSpi.java
- org/mozilla/jss/provider/javax/crypto/JSSMacSpi.java
- org/mozilla/jss/provider/javax/crypto/JSSSecretKeyFactorySpi.java
This enables javadoc generation for these classes. While the JSSProvider
clases lack useful javadocs, their existence helps developers check the
supported interfaces. Additionally, the PKCS#11 `PrivateKey` interfaces
should be made public to mirror their `PublicKey` counterparts, in the
rare instances where they're used instead of the generic Java
interfaces.
> Mark JSS Provider and PKCS#11 classes as public

- org/mozilla/jss/netscape/security/util/Utils.java
In 8de4440c5652f6f1af5b4b923a15730ba84f29e1, the base64 encoder was
changed from `apache-commons-codec` to the Java standard library to drop
a dependency. However, the behavior changed as a result: the Java
standard library doesn't include a final line separator, whereas
`apache-commons-codec` did. This results in malformed CSRs:
> YWRPxyBKvFAOB29fwPwBJLZksrwQ0xAs7sooc+qF-----END NEW CERTIFICATE REQUEST-----
Resolves: https://pagure.io/freeipa/issue/8199
> Fix base64-encoding of CSRs

- org/mozilla/jss/crypto/Algorithm.java
- org/mozilla/jss/crypto/EncryptionAlgorithm.java
- org/mozilla/jss/crypto/IVParameterSpec.java
- org/mozilla/jss/crypto/KeyWrapAlgorithm.java
- org/mozilla/jss/netscape/security/util/WrappingParams.java
- org/mozilla/jss/pkcs11/PK11Cipher.java
- org/mozilla/jss/pkcs11/PK11KeyWrapper.java
- org/mozilla/jss/pkcs12/AuthenticatedSafes.java
- org/mozilla/jss/pkcs7/EncryptedContentInfo.java
- org/mozilla/jss/pkix/cms/EncryptedContentInfo.java
- org/mozilla/jss/pkix/primitive/EncryptedPrivateKeyInfo.java
[`org.mozilla.jss.crypto.IVParameterSpec`](https://dogtagpki.github.io/jss/master/javadocs/org/mozilla/jss/crypto/IVParameterSpec.html) is an artifact from the dark ages when Java didn't support much crypto.
Now there's [`javax.crypto.spec.IvParameterSpec`](https://docs.oracle.com/javase/8/docs/api/javax/crypto/spec/IvParameterSpec.html). We've supported both for a while. To finally deprecate the former, make it inherit from the latter, removing its implementation completely.
There's two commits here:
1. Merge the implementations.
2. Combine all usages of the former into only caring about the latter. 
If you have better one-line commit messages, do tell me, else I could just do it in one commit.
> Merge IVParameterSpec into IvParameterSpec

- org/mozilla/jss/crypto/KeyWrapAlgorithm.java
- org/mozilla/jss/pkcs7/EncryptedContentInfo.java
- org/mozilla/jss/pkix/cms/EncryptedContentInfo.java
- org/mozilla/jss/pkix/primitive/EncryptedPrivateKeyInfo.java
This fixes the KRA .p12 recovery failures we've been seeing in Dogtag. 
This fix is in two parts: 
- Fix swapped parameter names with PBE
- Use specified algorithm for KeyWrap
See each commit message for additional details.
> Fix EncryptedPrivateKeyInfo.createPBE

- org/mozilla/jss/nss/SSL.c
- org/mozilla/jss/nss/SSL.java
- org/mozilla/jss/ssl/SSLProtocolVariant.java
When splitting `JSSEngine` into an abstract class and a reference implementation (in #150), I've left the `SSLFDProxy` instance, `ssl_fd`, in the reference implementation, but moved all the cipher suite configuration to JSSEngine.
This resulted in the need to query default configuration, instead of asking `ssl_fd` how it was configured, though technically this need already existed (as `ssl_fd` could've been `null`, which we largely ignored).
This introduces wrappers for `SSL_CipherPrefSetDefault`, `SSL_CipherPrefGetDefault`, `SSL_VersionRangeGetDefault`, and `SSL_VersionRangeSetDefault`.
> Query and Set Default SSL configuration

- org/mozilla/jss/CryptoManager.java
When loading JSS as part of the default JDK setup, we don't really wish
to spam unsuspecting users with log messages. Move `logger.info` to
`logger.debug` in the `CryptoManager` initialization process.
----
@edewata / @jmagne / @ladycfu -- are there any arguments against this? It makes JSS initialization silent in most cases, which for putting it in `java.security`, I think is a good thing.
> Move CryptoManager logging to debug

- cmake/JSSConfig.cmake
- tools/tests/cmac.c
NSS versions v3.47 to v3.50 included swapped values for `CKM_AES_CMAC` and
`CKM_AES_CMAC_GENERAL`. This adds feature detection to JSS, disabling CMAC
and KBKDF at compile time for the broken NSS versions.
Related: [`moz-bz#1611209`](https://bugzilla.mozilla.org/show_bug.cgi?id=1611209)
---
Note that this doesn't add runtime detection. I'm still debating if that's worth adding, and what our response should be. Runtime detection would have to actually call the CMAC operation, which would likely involve generating a new key. In FIPS mode, that likely requires the token to be logged in already.
> Detect NSS with broken CMACs during configuration

- cmake/JSSCommon.cmake
- cmake/JSSConfig.cmake
- cmake/JSSTests.cmake
- lib/java.security.Provider.in
- org/mozilla/jss/JSSLoader.java
- org/mozilla/jss/JSSProvider.java
- org/mozilla/jss/tests/EnumerationZeroTest.java
- org/mozilla/jss/tests/JCASymKeyGen.java
- org/mozilla/jss/tests/JSSProvider.java
- tools/java.security.in
- tools/jss.cfg.in
- tools/run_test.sh.in
When this works, it will eventually allow us to integrate more closely into the JDK ecosystem. In particular, it'll allow us to replace the providers in `java.security` with our own override list, which means FIPS mode will be more stable.
Eventually, this will also remove some of the need TomcatJSS's initialization logic. In particular, JSS will be already initialized by the JDK prior to starting TomcatJSS, so we can access the JSSProvider's SSLEngine already.
> JSSProvider - java.security based loader

- org/mozilla/jss/pkcs11/PK11Cipher.java
- org/mozilla/jss/pkcs11/PK11KeyWrapper.java
- org/mozilla/jss/pkcs11/PK11MessageDigest.java
Previously we enforced strict token key matching: the primary key used
for the operation must strictly reside on the current PKCS#11 token,
otherwise JSS would bail. However, NSS has the ability to move the key
to whichever token best supports the given operation. This means that
we'd prematurely bail when the operation would succeed if it were
actually executed. By removing these checks, we still leave the ability
to generate keys on a specific token, we just allow them to be used on
whatever token supports the given operation (and the key is allowed to
be moved to).
> Remove token key checks

- .gitignore
- CMakeLists.txt
- cmake/JSSConfig.cmake
- org/mozilla/jss/jssconfig.h.in
- org/mozilla/jss/ssl/SSLCipher.c
`SSLCipher` was the first use of a feature which could appear in a later
version of NSS than we support. Rather than bumping the minimum NSS
version, we chose to use compile-time detection of the NSS version and
limit our code accordingly. However, this sets a precedence for ignoring
the features actually present in the NSS system. Certain downstream
distributions are fond of backporting features, which means our code
could've executed but didn't.
Switching to feature detection (via the `check_struct_has_member` macro)
allows us to be sure we execute this code on as many platforms as
possible.
> Move to proper feature checks

- org/mozilla/jss/pkcs11/PKCS11Constants.java
Includes the CMAC fixes backported to existing Fedora releases.
> Update PKCS11Constants from NSS v3.50

- .github/workflows/optional.yml
- tools/Dockerfiles/centos_7
- tools/Dockerfiles/centos_8
~This will be rebased on top of #440 once that is reviewed and merged.~
----
This adds CentOS 7 and 8 CI to the master branch of JSS, under the optional section. This means it isn't required for merge and if necessary, we can break it. However, adding both CentOS 7 and CentOS 8 should give us a wider range of NSS versions to test on, which I think is a good thing for detecting when we truly need to bump the minimum NSS version in the spec file.
> Add CentOS-based CI

- org/mozilla/jss/JSSProvider.java
- org/mozilla/jss/crypto/Algorithm.c
- org/mozilla/jss/crypto/Algorithm.h
- org/mozilla/jss/crypto/Algorithm.java
- org/mozilla/jss/crypto/SignatureAlgorithm.java
- org/mozilla/jss/netscape/security/x509/AlgorithmId.java
- org/mozilla/jss/pkcs11/KeyType.java
- org/mozilla/jss/pkcs11/PK11Signature.c
- org/mozilla/jss/pkcs11/PK11Signature.java
- org/mozilla/jss/pkcs11/pk11util.h
- org/mozilla/jss/provider/java/security/JSSSignatureSpi.java
- org/mozilla/jss/provider/java/security/RSAPSSAlgorithmParameters.java
- org/mozilla/jss/tests/JCASigTest.java
- org/mozilla/jss/tests/SigTest.java
- org/mozilla/jss/tests/all.pl
- org/mozilla/jss/util/java_ids.h
Provide support for the various SHAxxxwithRSAPSS algorithms.
Supprt for 256, 384, and 512 variants included.
Included test case for SHA256withRSA/PSS.
This fix also requires a corresponding fix to the pki server in
order to exercise this functionality in the context of a pki
ca server.
> JSS RSA-PSS support first cut.

- cmake/JSSTests.cmake
- org/mozilla/jss/JSSProvider.java
- org/mozilla/jss/provider/javax/net/JSSContextSpi.java
- org/mozilla/jss/ssl/javax/JSSEngine.java
- org/mozilla/jss/ssl/javax/JSSEngineReferenceImpl.java
- org/mozilla/jss/ssl/javax/JSSSession.java
- org/mozilla/jss/tests/TestSSLEngine.java
This PR adds necessary features to implement a SSLEngine in JSS. It is placed under `org.mozilla.jss.ssl.javax.JSSEngine`, and exposed via the Mozilla-JSS Provider interface. 
Checklist:
---
OK, this is ready for review. The checklist above is as complete as I'd like it for this initial merge. Note that performance **isn't** a concern for this particular implementation, right now. We'll get there. This is mostly to make sure we have the scaffolding and have _something_ in place to test against TomcatJSS and PKI before we get too excited about making things feature-complete. 
I'm going for clarity here with this. If you have any question, however small, ask it in a comment and I'll try and address it.
> JSSEngine, an SSLEngine implementation

- org/mozilla/jss/nss/SSLChannelInfo.java
- org/mozilla/jss/nss/SSLPreliminaryChannelInfo.java
- org/mozilla/jss/tests/TestRawSSL.java
Marking the data members private allows us to use getters which throw an
exception when the corresponding feature isn't available from NSS. This
gives us a more descriptive error message including how to fix it, if
necessary. It also hides the less descriptive `haveNSS<Version>` fields
from the developer.
---
Alternative to #442. 
@edewata -- if you like this approach better, I can update `SSLPreliminaryChannelInfo`. I think it might be better to use getters in this case, rather than data fields. This makes these two structs different than [`SecurityStatusResult`](https://dogtagpki.github.io/jss/master/javadocs/org/mozilla/jss/nss/SecurityStatusResult.html), but I think that's fine. `SecurityStatusResult` is a combination of a couple …
> Add getters to SSLChannelInfo

- org/mozilla/jss/ssl/javax/JSSEngine.java
- org/mozilla/jss/ssl/javax/JSSEngineReferenceImpl.java
- org/mozilla/jss/ssl/javax/JSSSession.java
- org/mozilla/jss/tests/TestSSLEngine.java
After ~#150~ and ~#432~ are merged, this can be rebased, reviewed, and merged.
This enables `SSLSession` in three commits:
- Moves the `SSLFDProxy` from the specific instances to the `JSSEngine` interface. Also exposes access to it in a coordinated way. (`ssl_fd` is nullable, so callers should always use `getSSLFDProxy()` instead of caching the value).
- Updates `JSSSession` with new values, sets the values from `JSSEngineReferenceImpl`, and adds some NSS-specific tricks.
- Adds some basic tests for SSLSession to the test suite. 
This `SSLSession` implementation is definitely advanced enough for both JSS-specific callers and also generic enough to support Tomcat.
> Enable SSLSession

- org/mozilla/jss/ssl/javax/JSSEngine.java
Certain parameters cannot be modified after the handshake begins. These
are which mode we're using (client/server), cipher suites, and protocol
versions. Throw an exception when these are changed after the handshake
has begun.
----
Discussed in a [comment](https://github.com/dogtagpki/jss/pull/150#discussion_r394689897) on #150. Depends on #434, hence separate PR.
> Prevent post-handshake configuration changes

- org/mozilla/jss/provider/javax/net/JSSContextSpi.java
- org/mozilla/jss/ssl/javax/JSSEngine.java
The default JDK implementation assumes that all `SSLContextSpi`
implementations expose a `SSLSocket`; it doesn't use a `SSLEngine`
when a `SSLSocket` is unavailable, instead throwing an NPE. Lack
of an overridden `SSLParameters` breaks Tomcat.
--- 
An alternative is to enumerate `SSLCipher` and check the `supported` field and use `crypto.Policy` to get the default `SSLVersion` values. Thoughts?
> JSSContext: Default Parameters

- .github/workflows/required.yml
- lib/jss.map
- tools/Dockerfiles/symbolcheck
@edewata reported another issue with JSS, as caught by the PKI CI changes: some functions under `org.mozilla.jss.nss` lacked whitelisting in the version script (`lib/jss.map`). This results in JDK crashes due to missing symbols.
Fix all missing symbols and introduce a CI check to catch this in the future.
> Update Version Script

- .github/workflows/optional.yml
- tools/Dockerfiles/pki_build
This adds an optional CI check that builds JSS and then builds PKI,
installing both sets of RPMs.
----
@SilleBille -- is it possible to execute a PKI job inside this? I'd like to at least spawn a few subsystems, but that requires an init system. Got any thoughts for me?
> Add optional CI to check if PKI build is broken

- jss.spec.in
- org/mozilla/jss/CryptoManager.java
- org/mozilla/jss/JSSProvider.java
- org/mozilla/jss/util/jssver.h
This version offers two improvements over v4.4.8:
- Change to dynamic-first libjss4.so linking, mirroring the behavior of
later JSS releases, and
- Introduces RSA-PSS signature support.
Thanks to Jack Magne for the RSA-PSS code!
> Release JSS v4.4.9

- cmake/JSSTests.cmake
- lib/jss.map
- org/mozilla/jss/tests/TestGlobalReference.java
- org/mozilla/jss/util/GlobalRefProxy.c
- org/mozilla/jss/util/GlobalRefProxy.java
This just adds a test case for `GlobalRefProxy`, since I've been hitting issues with it while trying to address some memory issues in `NativeProxy`. I don't think there is anything wrong with this class, but since I wrote the test, we might as well keep it.
> Add test for GlobalRefProxy

- CMakeLists.txt
- cmake/JSSConfig.cmake
- cmake/JSSTests.cmake
- docs/build_system.md
- tools/Dockerfiles/fedora_rawhide
Enables a new CMake variable, `WITH_INTERNET`, to enable tests which require an internet connection. This currently includes only the BadSSL test, but could include other tests in the future (such as some under `org.mozilla.jss.ssl` currently).
> Enable BadSSL Tests

- lib/jss.map
- org/mozilla/jss/CryptoManager.c
- org/mozilla/jss/CryptoManager.java
- org/mozilla/jss/tests/SetupDBs.java
- org/mozilla/jss/util/NativeProxy.java
- tools/run_test.sh.in
I'm still trying to decide the semantics I want for this and how far we want to go with it.
This pull request enables shutdown of a `CryptoManager` instance, shutting down NSS in the process. This first frees all remaining `NativeProxy` references, since they're (implicitly?) references to NSS values, which won't work after `NSS_Shutdown` is called. The result is that any attempt to use them will likely throw a `NullPointerException` _somewhere_. 
I did this because in #467, I wanted cleaner memory checking. In particular, I wanted to remove all `NativeProxy` references and clean up after NSS, so the only things that remain are true C level leaks.
Thoughts?
> Enable Shutdown of NSS and CryptoManager

- org/mozilla/jss/pkcs11/PK11SymKey.c
In NSS v3.52, support is coming for PKCS#11 v3.0. This deprecates the
`_NETSCAPE_` namespace for PKCS#11 constants in favor of `_NSS_`. The few
remaining `_NETSCAPE_` constants will be moved to `_NSS_`. We only use one,
`CKM_NETSCAPE_PBE_SHA1_DES_CBC`. Add an `#ifdef` for compatibility with the
new preferred name.
See also: [`moz-bz#1603628`](https://bugzilla.mozilla.org/show_bug.cgi?id=1603628)
> Move from _NETSCAPE_ to _NSS_ PKCS#11 constants

- cmake/JSSConfig.cmake
- jss.spec
Since `SSLEngine` is a breaking change introducing significant new
functionality (and strictly requiring NSS v3.44 or greater), move
to a new minor version.
---
v4.6.3 was therefore the last `v4.6.x` release, so I created a new branch off of it and [cherry-picked](https://github.com/dogtagpki/jss/commits/v4.6.x) a few fixes onto it.
> Branch to v4.7.0 beta release 1

- lib/jss.map
When `v4.6.x` was branched off of `v4.6.3`, `jss.map` wasn't updated to
reflect the next version on the master branch.
> Fix latest jss.map entry to v4.7.0

- org/mozilla/jss/CryptoManager.c
In the javadocs for `CryptoManager.setPasswordCallback()`, it says:
> The callback may be `NULL`, in which case password callbacks will
> fail gracefully.
However, `setNativePasswordCallback()` will assert on a `NULL` callback.
Fix this to handle NULL gracefully.
----
Note that there is a workaround: use a [`NullPasswordCallback`](https://dogtagpki.github.io/jss/master/javadocs/org/mozilla/jss/util/NullPasswordCallback.html) instance instead.
> Accept NULL in CryptoManager.setPasswordCallback()

- org/mozilla/jss/pkcs11/PK11PrivKey.c
----
This has impacted tests for a while. I've finally made it optional rather than fixing the ordering of test cases.
> Allow NULL PK11PrivKey identifiers

- lib/jss.map
- org/mozilla/jss/nss/PR.c
- org/mozilla/jss/nss/PR.java
- org/mozilla/jss/nss/PRFDProxy.java
- org/mozilla/jss/nss/SSL.c
- org/mozilla/jss/nss/SSL.java
- org/mozilla/jss/nss/SSLFDProxy.c
- org/mozilla/jss/nss/SSLFDProxy.h
- org/mozilla/jss/nss/SSLFDProxy.java
- org/mozilla/jss/pkcs11/PK11Cert.c
- org/mozilla/jss/pkcs11/PK11Cert.java
- org/mozilla/jss/pkcs11/PK11Cipher.c
- org/mozilla/jss/pkcs11/PK11Cipher.java
- org/mozilla/jss/pkcs11/PK11Key.java
- org/mozilla/jss/pkcs11/PK11MessageDigest.java
- org/mozilla/jss/pkcs11/PK11Module.c
- org/mozilla/jss/pkcs11/PK11PrivKey.c
- org/mozilla/jss/pkcs11/PK11PubKey.c
- org/mozilla/jss/pkcs11/PK11Signature.c
- org/mozilla/jss/pkcs11/PK11Signature.java
- org/mozilla/jss/pkcs11/PK11SymKey.c
- org/mozilla/jss/pkcs11/PK11Token.c
- org/mozilla/jss/ssl/SocketBase.java
- org/mozilla/jss/ssl/common.c
- org/mozilla/jss/util/GlobalRefProxy.c
- org/mozilla/jss/util/GlobalRefProxy.java
- org/mozilla/jss/util/NativeProxy.java
This is built on top of #472.
There are a few new fixes:
- `PK11Cert`, `PK11Cipher`, `PK11Key`, `PK11MessageDigest`, and `PK11Signature` all now have `AutoCloseable` for their internal CertProxies.
- Fix `NativeProxy` registry tracking, candidate for backport.
- Improve `SSLFDProxy`'s `globalRef` access.
- Fix handling of `NULL` pointers in various places.
> Improve Memory Management

- docs/usage/jssprovider.md
- docs/using_jss.md
- org/mozilla/jss/InitializationValues.java
- org/mozilla/jss/InvalidLengthException.java
This begins to document our changes w.r.t. `JSSProviderLoader` &c. 
You can see the rendered documentation [here](https://github.com/cipherboy/jss/blob/add-provider-loader-docs/docs/usage/jssprovider.md).
> Add documentation on the Mozilla-JSS Provider

- org/mozilla/jss/netscape/security/x509/AlgorithmId.java
In cadc299fa69554e2e7ab9226298be639219476ab and `v4.4.x` commit
e1ee07a3c19cd15d7dab1dedf383128a2b83b925, `AlgorithmId` was updated
to unconditionally add an extra space to `toString`, to separate the
algorithm name from the parameters. This suffices in some cases, but
`AlgorithmId.toString()` is used by PKI to compare against a tokenized
list of characters. Removing the extraneous whitespace was the solution
proposed in PKI commit [`dogtagpki/pki@53de7514`](https://github.com/dogtagpki/pki/commit/53de751485b04fe2a1555228342ed642c9a9e347), but
this should really be handled in JSS instead of PKI.
See also: https://github.com/dogtagpki/pki/pull/364
> Remove space from AlgorithmId.toString()

- org/mozilla/jss/netscape/security/util/Utils.java
In 30b3cde147283d32ec2fd902128e18f54252cf4d, allowances were made for
keys without a unique identifier yet. This happens when the key is new
and code is racing to create an identifier for a key held by another
process which is also accessing the NSS DB. Mostly, this occurs in the
JSS test suite process.
As a result of the now-NULL result, `JSSKeyStoreSpi.getAliases` will call
`Utils.HexEncode` with a value of null, raising a NPE. Allow
`Utils.HexEncode` to return an empty string instead of raising an NPE in
this case.
> Fix NPE in Utils.HexEncode

- org/mozilla/jss/netscape/security/x509/AlgorithmId.java
----
Backport of #504.
fyi @jmagne -- I don't think this code is actually used in JSS (in `v4.4.x`) but it is in PKI.
> Fix SHA512withRSA/PSS identifier

- org/mozilla/jss/netscape/security/x509/AlgorithmId.java
PKI's usage of `AlgorithmId.toString()` doesn't handle having the
parameters encoded in the `toString()` representation of the id.
Move `toString()` back to only having the contents of `algName`, and
move parameters to a separate method.
> Add AlgorithmId.toStringWithParams, fix toString

- cmake/JSSConfig.cmake
- jss.spec
This release features improvements over [`v4.6.3`](https://github.com/dogtagpki/jss/releases/tag/v4.6.3):
- Fixed base-64 encoding of CSRs
- Fixed PBE handling
- Detect broken NSS versions with partial CMAC support
- Fix NativeProxy memory leaks present since v4.6.2
Thanks to everyone who contributed to this release!
> Release JSS v4.6.4

- cmake/JSSTests.cmake
- org/mozilla/jss/netscape/security/x509/CertificateChain.java
- org/mozilla/jss/tests/CertificateChainTest.java
The `CertificateChain` class has been modified to use
a `List` instead of a fixed array of `X509Certificates`.
Additional methods will be added later to manipulate
the certificates in the chain.
This allows the `CertificateChain` to be used to compose
new certificate chains based on the issuer's chain.
> Refactored CertificateChain

- org/mozilla/jss/crypto/Policy.java
- org/mozilla/jss/ssl/SSLVersionRange.java
- org/mozilla/jss/ssl/javax/JSSEngine.java
When constructing a new `SSLEngine`, Tomcat will take the supported
ciphers and limit the enabled cipher suites to only ones which are
supported by this `SSLEngine` implementation. Because the list of cipher
suites we returned were allowed by local crypto policy, out result was
compliant. However, other usages of `SSLEngine` aren't guaranteed to
behave the same; make sure we explicitly filter to only supported cipher
suites.
> Comply with crypto-policies outside of Tomcat

- tools/Dockerfiles/debian_jdk11
- tools/Dockerfiles/ubuntu_jdk8
Lately an update for `tzdata` has been breaking CI tests for Ubuntu:
Setting up tzdata (2019c-3ubuntu1) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
Configuring tzdata
------------------
Please select the geographic area in which you live. Subsequent configuration
questions will narrow this down by presenting a list of cities, representing
the time zones in which they are located.
1. Africa      4. Australia  7. Atlantic  10. Pacific  13. Etc
2. America     5. Arctic     8. Europe    11. SystemV
3. Antarctica  6. Asia       9. Indian    12. US
Setting `DEBIAN_FRONTEND=noninteractive` should prevent apt from querying
information from the container image.
`Signed-off-by: …
> Use non-interactive apt installation

- org/mozilla/jss/netscape/security/pkcs/PKCS7.java
- org/mozilla/jss/netscape/security/x509/CertificateChain.java
A new constructor has been added to create a `PKCS7` from
an array of certificates. This can be used to simplify
`CertificateChain.encode()` and some other code in PKI.
> Added PKCS7 constructor

- org/mozilla/jss/netscape/security/x509/CertificateChain.java
- org/mozilla/jss/tests/CertificateChainTest.java
The CertificateChain.sort() has been added to sort the
certificates in the certificate chain.
> Added CertificateChain.sort()

- org/mozilla/jss/ssl/javax/JSSEngineReferenceImpl.java
When `JSSengine.cleanup` is called prematurely, before `ssl_fd` or any
buffers are created, many of the native methods would segfault if
called with `NULL` buffers.
> Handle premature JSSEngine.cleanup()

- org/mozilla/jss/tests/CertificateChainTest.java
The `CertificateChainTest.testGetterMethods()` has been
modified to ignore the exception message since it may
change in different JDK versions.
> Fixed CertificateChainTest.testGetterMethods()

- lib/jss.map
- org/mozilla/jss/nss/SSL.c
- org/mozilla/jss/nss/SSL.java
- org/mozilla/jss/nss/SSLFDProxy.c
- org/mozilla/jss/nss/SSLFDProxy.h
- org/mozilla/jss/nss/SSLFDProxy.java
- org/mozilla/jss/ssl/javax/JSSEngine.java
- org/mozilla/jss/ssl/javax/JSSEngineReferenceImpl.java
- org/mozilla/jss/ssl/javax/JSSSession.java
- org/mozilla/jss/tests/TestSSLEngine.java
This should address some of the certificate issues we've seen in PKI CI. This is in several parts:
- Expose a bunch of new SSL options
- Expose `SSL_ReHandshake` (Necessary for renegotiation in TLS < 1.3)
- Expose `SSL_SendCertificateRequest` (necessary for PHA in TLS >= 1.3). Currently experimental, added in NSS v3.44.
- Expose the "real" handshake completion status in `SSLFDProxy`. Note that `SecurityStatusResult.on` reports `on` before the finish message is sent/received.
- Add support for NSS configuration, PHA in `JSSEngine`/`JSSEngineReferenceImpl`.
- Test everything! :D
> SSLEngine - PostHandshake Authentication / Renegotation

- .github/workflows/optional.yml
- .github/workflows/required.yml
Fedora 33 will ship with OpenJDK 11 by default and packages will be
required to compile with it. Move this to the default section so we
can catch failures with JDK11 support.
> Move JDK11 test to required section

- org/mozilla/jss/nss/PR.c
- org/mozilla/jss/ssl/javax/JSSEngineReferenceImpl.java
- org/mozilla/jss/tests/TestSSLEngine.java
One of the issues I identified when testing JSSEngine in IPA and PKI is handling of calls to wrap/unwrap with large wrap data. Here, large is defined as "exceeding the size of the internal buffers".
This PR is in three parts:
- Add a test case for calls to wrap/unwrap with large buffers. 
- Allow dummy `PR.Write` calls.
- Fix wrapping/unwrapping with large buffers.
- Fix calls to `PR.Write` when entire buffer isn't consumed. 
In particular, this is [consistent](https://github.com/apache/tomcat/blob/master/java/org/apache/tomcat/util/net/openssl/OpenSSLEngine.java#L458-L486) with Tomcat's OpenSSL native SSLEngine.
Note that dummy `PR.Write` calls are consistent with what [NSS does internally](https://github.com/nss-dev/nss/blob/master/lib/ssl/sslcon.c#L138). Sometimes we need to force NSS …
> SSLEngine - Handle Large wrap/unwrap Calls

- index.md
- Add 4.6.x docs to the index page
PS: `*/docs/index.html` is missing
> Update the homepage for gh-pages

- org/mozilla/jss/provider/javax/net/JSSContextSpi.java
Use the default `SunJSSE` provider to implement `getSocketFactory` and
`getServerSocketFactory` rather than returning `null`. This should appease
implementations expecting a `SocketFactory` instance.
> Hack: provide SSLContext's SSLSocket via SunJSSE

- org/mozilla/jss/ssl/javax/JSSEngine.java
This returns a new instance of `JSSParameters` which can be used to clone
the configuration of this `SSLEngine` into another. This is helpful for
implementing `SSLServerSocket`, which must `accept()`, creating a new
`SSLSocket` with the same initial configuration.
----
Only the top commit is new.
- ~Blocked by #526 ; will be rebased once that merges~
- Blocks #532 ; provides a method necessary for SSLServerSocket
> JSSEngine: Add getSSLParameters

- org/mozilla/jss/JSSLoader.java
- org/mozilla/jss/JSSProvider.java
- org/mozilla/jss/tests/TestSSLEngine.java
- tools/jss.cfg.in
--- 
Too many people are utilizing JSS master branch and expecting it to be stable. Remove JSSContextSpi for the time being until SSLEngine performance has been improved and SSLSocket is present.
> Remove JSSContextSpi for the time being

- jss.spec
See: https://pagure.io/packaging-committee/issue/411
See: https://docs.fedoraproject.org/en-US/packaging-guidelines/LicensingGuidelines/
> Switch to using %license macro

- org/mozilla/jss/ssl/javax/JSSSocket.java
- org/mozilla/jss/ssl/javax/JSSSocketChannel.java
Now that we have an `SSLEngine` implementation in hand, various other applications and libaries (such as resteasy) expect `SSLSocket`  as well. The issue is that our existing `SSLSocket` (under `org.mozilla.jss.ssl.SSLSocket`) doesn't conform at all to the `javax.net.ssl.SSLSocket` abstract class. 
Even if we hacked a `javax`-conforming `SSLSocket` out of a `jss.ssl.SSLSocket`, we'd still need to figure out how to allocate sockets correctly and close the existing one -- but immediate reuse might not be possible!
So, implement `SSLSocket` using our new `SSLEngine`. 
TODO:
> SSLSocket from SSLEngine

- org/mozilla/jss/ssl/javax/JSSServerSocket.java
- org/mozilla/jss/ssl/javax/JSSServerSocketChannel.java
Based off of #532. Will be rebased once this is merged.
---
There are three major functionalities in SSLContext:
- `SSLEngine` -- merged in #150.
- `SSLSocketFactory`
- `SSLServerSocketFactory`
#532 and this PR introduce the underlying `JSSSocket` and `JSSServerSocket` implementations these factories will return. Note that while `SSLSocketFactory` doesn't explicitly return a `SSLSocket` -- but its javadocs say that it does. Many places (including in OpenJDK itself!) blindly cast the Socket resulting from a `SSLSocketFactory` to `SSLSocket` without checking if it is possible. This makes returning the existing `org.mozilla.jss.ssl.SSLSocket` impossible, unless it is extended to implement the `javax.net.ssl.SSLSocket` interface.
> JSSServerSocket to JSSSocket

- org/mozilla/jss/ssl/javax/JSSServerSocketChannel.java
Since we won't return the `JSSServerSocketChannel` in situations where the
wrapped socket lacks a channel, it is highly unlikely that this method
will ever be called when the parent channel is `null`. Simplify the logic
and throw an exception in this case instead of returning an accepted
socket channel. Note that, while calling `accept()` on the parent socket will
allows return a non-null socket, it isn't guaranteed to have a
`SocketChannel`.
> Simplify JSSServerSocketChannel.accept()

- org/mozilla/jss/provider/javax/net/JSSContextSpi.java
- org/mozilla/jss/ssl/javax/JSSEngineReferenceImpl.java
- org/mozilla/jss/ssl/javax/JSSServerSocketFactory.java
- org/mozilla/jss/ssl/javax/JSSSocketFactory.java
- org/mozilla/jss/tests/BadSSL.java
- tools/run_test.sh.in
This is the remaining work: add our `SSLSocketFactory` and `SSLServerSocketFactory` implementations and then switch to them in `JSSContextSpi`. Introduces a single, minor test case, which adds the new `JSSSocket` to our existing `BadSSL` tests.
> Finish JSSContext - Switch to JSS-provided SSLSocket

- org/mozilla/jss/tests/TestSSLEngine.java
- tools/run_test.sh.in
This improves the test by reusing buffers between tests, reducing the load on the allocator and garbage collector. 
This doesn't explicitly improve the speed though.
> SSLEngine - Test improvements

- org/mozilla/jss/pkcs11/PK11Cert.java
- org/mozilla/jss/ssl/javax/JSSEngine.java
- org/mozilla/jss/ssl/javax/JSSEngineReferenceImpl.java
Concretely, this gives us a performance improvement from:
```
73/77 Test #53: SSLEngine_RSA .....................................   Passed   39.81 sec
Start 54: SSLEngine_ECDSA
74/77 Test #54: SSLEngine_ECDSA ...................................   Passed    5.10 sec
Start 72: SSLEngine_RSA_FIPSMODE
75/77 Test #72: SSLEngine_RSA_FIPSMODE ............................   Passed   35.63 sec
Start 73: SSLEngine_ECDSA_FIPSMODE
76/77 Test #73: SSLEngine_ECDSA_FIPSMODE ..........................   Passed    4.54 sec
```
to:
```
73/77 Test #53: SSLEngine_RSA .....................................   Passed   22.16 sec
Start 54: SSLEngine_ECDSA
74/77 Test #54: SSLEngine_ECDSA ...................................   Passed    4.05 sec
Start 72: SSLEngine_RSA_FIPSMODE
75/77 Test #72: SSLEngine_RSA_FIPSMODE …
```
> Cache SSL Server Sockets

- org/mozilla/jss/nss/SSL.java
- org/mozilla/jss/ssl/SSLServerSocket.java
- org/mozilla/jss/ssl/javax/JSSEngine.java
- org/mozilla/jss/ssl/javax/JSSEngineReferenceImpl.java
- org/mozilla/jss/ssl/javax/JSSSocketChannel.java
There's two bugs found by #558: 
- JSSSocket waiting-on-close takes a long time and doesn't work in all scenarios (e.g., wget won't send closure notifications so the socket will remain open forever). This also happens, e.g., with siege.
- Session cache creation can race, causing the JVM to segfault in NSS code. We use an `AtomicBoolean` to avoid this potential and ensure we only initialize the session cache once.
We also add one refactoring commit:
- Throw `SSLException`s instead of `RuntimeException`s during `JSSEngine` initialization. 
We should probably merge this ahead of #558 merging.
> Remove JSSSocket wait-on-close, fix session cache creation

- docs/usage/benchmarksslsocket.md
- org/mozilla/jss/tests/BenchmarkSSLSocket.java
This benchmark supports three providers:
1. org.mozilla.jss.ssl.SSLSocket, named JSS.legacy
2. org.mozilla.jss.ssl.javax.JSSSocket, named JSS.SSLSocket
3. the JDK's SunJSSE provider's SSLSocket, named SunJSSE.SSLSocket
----
This is the results from siege [0] ran via:
```bash
$ siege -c 100 -b -t 5m https://localhost:8443
```
with the benchmarker set to send a faked 1024-byte message:
```bash
$ ./run_test.sh org.mozilla.jss.tests.BenchmarkSSLSocket JSS.legacy Server_RSA 8443 1024
```
The server certificate is 4096-bits. The selection of cipher suite and
protocol is left at their defaults. This is on a Lenovo Thinkpad P50
with a `Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz` and 32GB of RAM. Each
request gets spun off and handled by a new …
> Add SSLSocket benchmark

- org/mozilla/jss/pkcs11/PK11MessageDigest.c
- org/mozilla/jss/pkcs11/PK11MessageDigest.java
In my company we've seen very bad memory leaks and one place we've tracked this down to is handling of the ref counted symmetric key in hmac initialization.
The problem stems from the assumption about `PK11_CopySymKeyForSigning` that if it returns a non-null pointer that it was copied. The actual implementation will return the exact same pointer if the key is already in the current slot and `CKA_SIGN` can be added to it.
```
/* first just try to set this key up for signing */
PK11_SETATTRS(&setTemplate, CKA_SIGN, &ckTrue, sizeof(ckTrue));
pk11_EnterKeyMonitor(originalKey);
crv = PK11_GETTAB(slot)->C_SetAttributeValue(originalKey->session,
originalKey->objectID, &setTemplate, 1);
pk11_ExitKeyMonitor(originalKey);
if (crv == CKR_OK) {
return PK11_ReferenceSymKey(originalKey);
}
```
The …
> HMAC initialization can leak ref counted symmetric key

- docs/usage/jssengine.md
---
This complements PR #150 and adds usage and design documentation about the SSLEngine.
This is still WIP because its missing documentation on:
View the documentation [here](https://github.com/cipherboy/jss/blob/jss-engine-docs/docs/usage/jssengine.md).
> Add documentation about JSSEngine usage and design

- org/mozilla/jss/CryptoManager.java
- org/mozilla/jss/JSSLoader.java
- org/mozilla/jss/JSSProvider.java
- tools/jss.cfg.in
When using `JSSLoader` to initialize `JSSProvider` from the `java.security`
list, sometimes `CryptoManager.getInstance()` will fail. Usually this is
because instance is still null, even though
Security.getProvider("Mozilla-JSS") != null
The error message will usually be something like:
FINE: CryptoManager: loading JSS library
FINE: CryptoManager: loaded JSS library from java.library.path
Exception in thread "main" org.mozilla.jss.NotInitializedException
at org.mozilla.jss.CryptoManager.getInstance(CryptoManager.java:365)
at org.mozilla.jss.tests.SigTest.main(SigTest.java:52)
Allow `JSSLoader` to return the new CryptoManager object, let `JSSProvider`
store it, so that in this case, `CryptoManager.getInstance()` will return
an initialized instance.
`Signed-off-by: Alexander Scheel …
> Fix loading of CryptoManager in JSSLoader scenario

- org/mozilla/jss/nss/PRFDProxy.java
- org/mozilla/jss/nss/SSL.c
- org/mozilla/jss/ssl/javax/BufferPRFD.c
- org/mozilla/jss/ssl/javax/JSSEngineReferenceImpl.java
- org/mozilla/jss/ssl/javax/JSSSession.java
- org/mozilla/jss/ssl/javax/JSSSocket.java
- org/mozilla/jss/ssl/javax/JSSSocketChannel.java
- org/mozilla/jss/tests/BadSSL.java
This is currently a work in progress to fix various issues @edewata has reported with SSLEngine in the context of ACME.
The list of fixes include:
- Reduce the number of calls to `JSSSession.refreshData` -- this will help ensure certificates get queried less and reduce calls through the JNI layer.
- Use try-with-resources pattern in `BadSSL` to make sure we close our sockets.
- Make sure the `SSLEngine` explicitly gets freed when the socket is closed in `JSSSocket`, `JSSSocketChannel`
- Fix our implementation of `BufferPRFD`, cleaning up leaks &c.
- Free in `JSS_NewSecurityStatusResult`, though this function is unused currently because we rely on other, more advanced methods for getting Channel information.
- Properly implement `PRFDProxy.releaseNativeResources`.
While good changes, none …
> SSLEngine - Bug fixes and performance improvements

- cmake/JSSTests.cmake
- org/mozilla/jss/tests/SSLClientAuth.java
- Removes SHA-1 in accordance with [crypto-policies changes](https://gitlab.com/redhat-crypto/fedora-crypto-policies/-/commit/b298a9e107b7e9699b36879eca031d1900ded1c4)
- Removes DSS because it is old, unused, and only supports SHA-1 signatures too. 
This should fix Fedora Rawhide builds.
> Remove more legacy algos

- org/mozilla/jss/ssl/javax/JSSEngineReferenceImpl.java
- org/mozilla/jss/ssl/javax/JSSSocketChannel.java
We should handle `BUFFER_UNDERFLOW` events by attempting to read more data from the underlying socket.
In `JSSSocketChannel` we can handle this mostly safely by bringing the socket read into the try/catch loop. While `readBuffer` is still of a fixed size, we can now query the client for more data. This lets us claim `BUFFER_UNDERFLOW` is a supported event. However, we still would need to handle resizing the buffer in the event `readBuffer` isn't sufficiently large for this. This gets a little complicated, because we still need to maintain `src` as a view over `readBuffer` because we can't otherwise bound the size of the read on a blocking socket.
Tomcat however, already handles this case. When `unwrap` returns `BUFFER_UNDERFLOW`, it will exit the read loop it was previously stuck in and …
> Fix Tomcat by handling BUFFER_UNDERFLOW events

- org/mozilla/jss/tests/TestSSLEngine.java
The `SSLEngine.getSupportedProtocols()` on Fedora returns at least
2 protocols in FIPS mode, but on RHEL it returns only 1. The
`TestSSLEngine` has been changed such that it works with 1 protocol.
> Fixed TestSSLEngine

- org/mozilla/jss/nss/SSL.c
- org/mozilla/jss/pkcs11/PK11Cert.java
- org/mozilla/jss/provider/javax/crypto/JSSTokenKeyManager.java
- org/mozilla/jss/ssl/javax/JSSEngineReferenceImpl.java
- org/mozilla/jss/ssl/javax/JSSSession.java
- org/mozilla/jss/ssl/javax/JSSSocket.java
- org/mozilla/jss/ssl/javax/JSSSocketChannel.java
This fixes two memory leaks in SSLEngine, and reduces memory pressure by handling certain other cases.
1. Leaked `PRFDProxy` in `JSSEngineReferenceImpl.createBufferFD()`.
When `SSL_ImportFD` is called, NSS merges the second argument into the return value, by way of pushing a NSPR on top of the argument. This layer is the SSL layer and the second argument is "consumed" by the SSL `PRFileDesc *`. Java doesn't know about this, so we need to manually clear (not close!!) the `PRFDProxy` instance and set it to `null` to avoid leaking it. (Otherwise, `NativeProxy` retains a reference to it, preventing the Java object from being garbage collected).
2. Leaked `TokenProxy` in `JSSTokenKeyManager`.
When the `CryptoManager` returns the new `PK11Cert` instance, it contains a `CertProxy` and a …
> Fix SSLEngine memory leaks

- org/mozilla/jss/ssl/javax/BufferPRFD.c
- org/mozilla/jss/tests/TestBufferPRFDSSL.c
This introduces more memory fixes for JSSEngine:
1. Fix missing destructor call in the `PR_Close` implementation for NSPR PR/IO layers. This meant the `BufferPRFD` layer leaked.
2. Various small leak fixes in native (C) test case for `BufferPRFDSSL`. Not an issue in production.
~Additional fixes include~
- ~Allow duplication of `PK11Cert`, `PK11PrivKey` objects, to take ownership of new copies.~
- ~Make SSLEngine take ownership of certs, keys, and then release memory when cleanup occurs.~
----
I've decided not to include the latter two fixes. This makes the PR smaller and we can figure out how to deal with copying certs&keys later.
> More JSSEngine Memory Leak Fixes

- .github/workflows/informational.yml
- org/mozilla/jss/nss/SSLFDProxy.c
- org/mozilla/jss/ssl/javax/JSSEngineReferenceImpl.java
- org/mozilla/jss/tests/TestBufferPRFDSSL.c
In the previous commit, 76396ae47adf740aac0db38f143d959e5d6c39ec, by
calling the destructor on BufferPRFD layer, we finally clean it up
properly. However, this resulted in multiple calls to `closeInbound` or
`closeOutbound` resulting in a use-after-free.
> Prevent usage of ssl_fd after closing

- jss.spec
Fedora 33 has introduced the following change proposal:
https://fedoraproject.org/wiki/Changes/CMake_to_do_out-of-source_builds
This makes CMake do out-of-source builds by default. However, Fedora has
opted to use the %{_vpath_builddir} macro as the location of the default
build directory, instead of the more standard (in the CMake community)
build/ directory. %{_vpath_builddir} expands to %{_target_platform},
giving a per-architecture build directory.
Replace build/ references with %{_vpath_builddir} in the RPM spec. In
the future, we could move %{__make} to %cmake_build instead.
Signed-off-by: Alexander Scheel <ascheel@redhat.com>
> Fix build with CMake out-of-source build change

- lib/jss.map
- org/mozilla/jss/nss/SSL.c
- org/mozilla/jss/nss/SSL.java
- org/mozilla/jss/ssl/javax/JSSEngineReferenceImpl.java
- org/mozilla/jss/util/NativeProxy.java
This fixes a memory leak caused by `NativeProxy` maintaining strong references to all pointer objects. By switching them to `WeakReferences`, the registry is ignored in the GC reference count, and we can again allow items to be freed. 
Moving to `WeakReference` wasn't immediately possible due to a bug in SSLEngine: SSLEngine's server template didn't clear the underlying `PRFileDesc` pointer, meaning that -- when GC was again possible -- it would get freed, invaliding the model unintentionally. This resulted in SSLEngine tests failing. So, make `SSL.ImportFD` clear the consumed pointer.
> NativeProxy: Use Weak References 

- cmake/JSSCommon.cmake
- tools/Dockerfiles/debian_jdk11
- tools/Dockerfiles/fedora_rawhide
PKCS9 javadocs included bad HTML5 elements. Remove them, making the output look less pretty, but not requiring us to use any CSS styling.
> Fix PKCS9 javadocs

- org/mozilla/jss/netscape/security/util/Utils.java
While a nice idea in theory, this generates a ton of spurious messages
right now. We should eventually fix this and re-enable logging, but for
now we'll remove it.
> Remove invalid Base64 logging

- .github/workflows/informational.yml
- .github/workflows/known_failures.yml
At this point in time, Rawhide is doing a mass rebuild. This brings in
filesystem, which always fails to update. Since this is a known failure
outside of our control, move it to a separate CI section for the time
being.
> Move rawhide tests to known failures

- org/mozilla/jss/netscape/security/pkcs/PKCS9Attribute.java
This should make javadoc compatible with JDK 8 and JDK 11.
> Switch from summary="" to <caption> elements

- org/mozilla/jss/ssl/SSLServerSocket.c
- org/mozilla/jss/ssl/SSLSocket.c
- org/mozilla/jss/ssl/common.c
When `SSLSocket` is closed, the underlying pointer will be immediately
freed and `NULL`ed. This means that any future calls into the native
library could result in a `NULL` pointer dereference in NSS. This broke
IPA integration tests:
Stack trace of thread 32848:
----
Related: https://pagure.io/dogtagpki/issue/3198 
I'm not yet sure what changed between this and N-1 builds.
> Fix SSLSocket NULL pointer deference after close

- lib/jss.map
- org/mozilla/jss/nss/BadCertHandler.java
- org/mozilla/jss/nss/SSL.c
- org/mozilla/jss/nss/SSL.java
- org/mozilla/jss/nss/SSLErrors.c
- org/mozilla/jss/nss/SSLErrors.java
- org/mozilla/jss/nss/SSLFDProxy.c
- org/mozilla/jss/nss/SSLFDProxy.h
- org/mozilla/jss/nss/SSLFDProxy.java
- org/mozilla/jss/ssl/javax/JSSEngineReferenceImpl.java
This PR improves JCA compatibility by bypassing NSS's hostname verification on client `SSLEngine` connections, to mirror the behavior of SunJSSE.
We use the approach suggested by Bob Relyea, which is to hook the bad cert handler and check for a specific error. Because hostname verification is guaranteed to be the last thing NSS does (regardless of whether or not we use NSS's default handler or libpkix verification), this should be safe. This has the added benefit of also working with our custom cert authentication callbacks. 
Eventually, we'll expose this method to all JSSEngine instances, and allow the caller a chance to override other errors if they'd like, in an asynchronous manner.
> Fix hostname verification and improve JCA compatibility

- org/mozilla/jss/ssl/SSLSocket.java
- org/mozilla/jss/ssl/SocketBase.java
- org/mozilla/jss/ssl/common.c
- org/mozilla/jss/ssl/javax/JSSEngine.java
- org/mozilla/jss/ssl/jssl.h
This PR fixes two additional issues:
- We disable Fallback SCSV. While used by browsers, it isn't present in the cipher suites negotiated by SunJSSE by default. Since we're striving to be compatible with that, drop SCSV.
- Add PHA to SSLSocket. This addresses the failure in https://github.com/dogtagpki/pki/pull/537 and https://github.com/dogtagpki/pki/pull/543, with one additional patch.
@edewata / @jmagne -- should we make PHA default in the legacy SSLSocket? We added TLSv1.3 support to it a while ago, but TLSv1.3's behavior differs from TLSV1.2's behavior, probably why we had issues with SCSV and TLSv1.2 pinned as maximum in Dogtag PKI. If we enable PHA, TLSv1.2 and TLSv1.3 will mostly be compatible.
If so, we could avoid the need for a strict dependency on a newer JSS version.
> [v4.7.3] Disable Fallback SCSV and add PHA to legacy SSLSocket

- org/mozilla/jss/CryptoManager.java
- org/mozilla/jss/JSSLoader.java
- org/mozilla/jss/JSSProvider.java
- org/mozilla/jss/ssl/javax/JSSEngineReferenceImpl.java
Backport of #631.
QE (thanks @PsOverflow and @snehaveeranki1!) found a bug where `JSSEngine` stalled on certain PKI commands. This was ultimately caused by `JSSEngine` reporting that the size of `app_data` (as returned by `unwrap()`) was one byte larger than was actually written into the `ByteBuffer`. This meant that certain libraries (like Apache HTTP components) added an extra `NULL` byte into the data stream between HTTP requests, breaking the parsing code and stalling the connection.
- Add `CryptoManager.isInitialized()` to fix another stack trace found while trying to reproduce the bug. The `JSSProvider` security provider attempted to load itself again, causing recursion that the Security Provider interface prevented, printing a stack trace when debugging was enabled. This is …
> Fix JSSEngine Stalling - Backport to v4.7.x

- org/mozilla/jss/CryptoManager.java
- org/mozilla/jss/JSSLoader.java
- org/mozilla/jss/JSSProvider.java
- org/mozilla/jss/ssl/callbacks.c
- org/mozilla/jss/ssl/javax/JSSEngineReferenceImpl.java
- org/mozilla/jss/tests/TestSSLEngine.java
QE (thanks @PsOverflow and @snehaveeranki1!) found a bug where `JSSEngine` stalled on certain PKI commands. This was ultimately caused by `JSSEngine` reporting that the size of `app_data` (as returned by `unwrap()`) was one byte larger than was actually written into the `ByteBuffer`. This meant that certain libraries (like Apache HTTP components) added an extra `NULL` byte into the data stream between HTTP requests, breaking the parsing code and stalling the connection.
We do a few things in this PR:
-  Forward port a fix from v4.7.x around `BAD_CERT_DOMAIN` handling in our JSS cert checking handler. This matches NSS behavior. Not a candidate for backport.
- Add additional inline documentation to the `JSSEngine`. Made while looking for the bug, not a candidate for backport.
- Add …
> Fix JSSEngine stalling

- org/mozilla/jss/crypto/KBKDF.c
- org/mozilla/jss/pkcs11/PK11PrivKey.c
- org/mozilla/jss/pkcs11/PK11PubKey.c
- org/mozilla/jss/pkcs11/PK11Token.c
Slots in NSS are reference counted; it is important to release our copy
of the reference when we're done using it. This fixes various instances
of slots either not being released or being released in the wrong order.
This should help to address [`rh-bz#676083`](https://bugzilla.redhat.com/show_bug.cgi?id=676083). It should be tested with additional subsystems to ensure it doesn't break Dogtag. 
> Finish releasing slots after use

- org/mozilla/jss/netscape/security/x509/OIDMap.java
- org/mozilla/jss/provider/javax/crypto/JSSTrustManager.java
I was getting a very strange error in JSSTrustManager certificate
validation.  The leaf certificate was (wrongly) being rejected for
not having the id-kp-serverAuth EKU.
I traced the error to X509CertImpl.getExtensionValue(); in
particular its catch block.  Upon exception it discards the
exception and returns null.  (This is not unreasonable when e.g. the
extension data cannot be parsed).  I added some debug logging.  The
exception thrown was:
```
java.security.cert.CertificateParsingException: Invalid root of
attribute name, expected [x509], received [ExtendedKeyUsageExtension]
at ...X509CertImpl.get(X509CertImpl.java:499)
at ...X509CertImpl.getExtensionValue(X509CertImpl.java:1014)
```
From here I traced it to the OIDMap and the String names.  Whereas
most extension names in the OIDMap …
> Fix missing OIDMap mappings for X.509 extensions

- org/mozilla/jss/CryptoManager.java
---
This was helpful in debugging @jmagne's issue, so I think we should include it. In particular, when `libjss4.so` is linked incorrectly, all three loads will fail, but only the second one will contain useful information.
> Log exceptions when libjss4.so failed to load

- org/mozilla/jss/nss/PR.c
- org/mozilla/jss/ssl/javax/JSSSocketChannel.java
```
5e223293 (Fraser Tweedale, 17 minutes ago)
JSSSocketChannel.read(): deliver all data from buffer fd
JSSSocketChannel.read() returns 0 when the underlying socket does not yield
any new data.  But in the case of small output buffers, earlier invocations
of read() may result in more decrypted data sitting in the unwrapped side
of the j_buffer, never to be delievered to the application.
To resolve this issue, continue on to unwrap() even when the underlying
socket does not yield new data.
However, only do this after the handshake has been completed. Empirically,
calling unwrap() at early stages of the handshake with empty buffers breaks
/something/, causing no data to ever be read from the socket.  (I do not
understand the exact cause.)
As part of this change, also refactor how the remote …
```
> JSSSocketChannel.read(): deliver all data from buffer fd

- cmake/JSSConfig.cmake
- jss.spec
This version of JSS has a few minor improvements over v4.7.x series:
- Porting from Apache Commons Lang 2 to 3
- A few memory fixes
- Two contributions from Fraser Tweedale:
- Fix missing OIDMap mappings for X.509 extensions
- `JSSSocketChannel.read()`: deliver all data from buffer fd
Thanks to everyone who contributed to this release!
> Release JSS v4.8.0

- org/mozilla/jss/pkcs11/PK11RSAPrivateKey.java
- org/mozilla/jss/pkcs11/PK11Store.java
Per discussion with Andrew Hughes in #java, JCA takes `RSAPrivateKey` to mean that the private exponent is extractable. Because the JCA is careful to use Key most places, we might get away with making `PK11RSAPrivateKey` not implement `RSAPrivateKey` and instead only implement `RSAKey` -- signalling to other providers that the private exponent isn't extractable.
This patch requires careful testing with SunJSSE and Dogtag PKI to ensure we don't rely on `PK11RSAPrivateKey` implementing `RSAPrivateKey` somewhere.
----
This patch targets v4.6.x branch -- I'm torn whether or not we should fix v4.7.x+ as we replace the SunJSSE TLS implementation with our own.
> Replace RSAPrivateKey with RSAKey

- jss.spec
This version of JSS requires apache-commons-lang3 and shouldn't be used
with older version of pki-core as a result.
As reported by @flo-renaud
> Bump tomcatjss, pki-core conflicts due to lang3

- cmake/JSSTests.cmake
Recent errors with PKCS11Constants have shown that we shouldn't be
running these tests on release builds for backports: only for
pre-release content. Only run them when the beta bit is set.
> Only check PKCS11Constants on beta builds -- v4.6.x backport

- cmake/JSSTests.cmake
Recent errors with PKCS11Constants have shown that we shouldn't be
running these tests on release builds for backports: only for
pre-release content. Only run them when the beta bit is set.
> Only check PKCS11Constants on beta builds

- cmake/JSSTests.cmake
Recent errors with PKCS11Constants have shown that we shouldn't be
running these tests on release builds for backports: only for
pre-release content. Only run them when the beta bit is set.
> Only check PKCS11Constants on beta builds -- v4.7.x backport

- org/mozilla/jss/pkcs11/PK11Signature.c
- org/mozilla/jss/tests/DigestTest.java
- org/mozilla/jss/tests/JCASigTest.java
- org/mozilla/jss/tests/SigTest.java
Our rawhide sandboxed CI image is currently failing with the cryptic:
Exception in thread "main" org.mozilla.jss.crypto.TokenException: Unable to create signing context
at org.mozilla.jss.pkcs11.PK11Signature.initSigContext(Native Method)
at org.mozilla.jss.pkcs11.PK11Signature.engineInitSign(PK11Signature.java:114)
at org.mozilla.jss.crypto.Signature.initSign(Signature.java:55)
at org.mozilla.jss.tests.SigTest.main(SigTest.java:88)
Switch JSS_throwMsg to JSS_throwMsgPrErr so we can get the underlying
error code from these calls.
----
This turned out to be caused by MD4 and MD5 being disabled. I've proactively removed some usage of SHA-1 as well as that is likely next on the chopping block.
These algorithms are still exposed in JSS's …
> Disable MD4, MD5 and SHA-1 algorithms in test suite

- org/mozilla/jss/pkcs11/PK11RSAPrivateKey.java
- org/mozilla/jss/pkcs11/PK11Store.java
- org/mozilla/jss/provider/javax/crypto/JSSMacSpi.java
In `JSSCipherSpi`, if a key from another provider is passed in, we first
attempt to export it and then import it into NSS. Only when this fails
do we raise an exception. This fixes a failure in JDK8 272-b10 when
JSS is used in conjunction with SunJSSE:
javax.net.ssl.SSLHandshakeException: Could not generate secret
at sun.security.ssl.ECDHKeyExchange$ECDHEKAKeyDerivation.t13DeriveKey(ECDHKeyExchange.java:479)
at sun.security.ssl.ECDHKeyExchange$ECDHEKAKeyDerivation.deriveKey(ECDHKeyExchange.java:419)
at sun.security.ssl.ServerHello$T13ServerHelloProducer.produce(ServerHello.java:596)
at sun.security.ssl.SSLHandshake.produce(SSLHandshake.java:421)
at sun.security.ssl.ClientHello$T13ClientHelloConsumer.goServerHello(ClientHello.java:1152)
at …
> Attempt to use SecretKeyFactory to rewrite keys prior to failing JSSMacSpi

- .github/workflows/required.yml
- tools/Dockerfiles/fedora_32
- tools/Dockerfiles/fedora_33
This is a little newer than what we'd prefer, but F30 image isn't working any more.
**Note**: As of the time of this PR, F31 is still supported for 7 more days. F33 introduces changes to RPM Spec file building (out-of-source directories, as if we weren't already doing that...)  that break v4.6.x's spec file. I'd prefer not to backport those changes, so I went with F31/F32.
> Update CI to use Fedora 31, 32

- org/mozilla/jss/crypto/SignatureAlgorithm.java
- org/mozilla/jss/netscape/security/x509/AlgorithmId.java
Three more minor bug fixes for PSS support in v4.6.x. The AlgorithmId.toString() bug was holding up gating and breaks PKI.
> Backport three additional patches

- org/mozilla/jss/tests/BadSSL.java
- org/mozilla/jss/tests/KeyFactoryTest.java
- In KeyFactoryTest, we were still creating 512-bit RSA/DSA keys. Remove DSA, remove references to IBM, and rely on policy to decide keysize.
- Small changes to BadSSL. Note that the test still doesn't pass with strict OCSP validation due to https://bugzilla.redhat.com/show_bug.cgi?id=1861495
> Fix more issues with old tests

- org/mozilla/jss/netscape/security/pkcs/PKCS10Attribute.java
- org/mozilla/jss/netscape/security/x509/ChallengePassword.java
- org/mozilla/jss/netscape/security/x509/ExtensionsRequested.java
- org/mozilla/jss/netscape/security/x509/OIDMap.java
This patch, together with the fix for Bug1664435 Error instantiating class for challenge_password with SCEP request, addresses the issue where  the class PasswordChallenge cannot be loaded due to Class Loader differences.
jss is installed in the common CL (/usr/share/pki/server/common/lib/jss4.jar)
the servlet classes are in webapp CL (/usr/share/pki/server/webapps/pki/WEB-INF/lib/pki-cms.jar)
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1664435
> Bug1908541-jss broke SCEP - missing PasswordChallenge class

- CMakeLists.txt
- jss.spec
This includes the `LINK_OPTIONS` flag to `try_compile`, allowing us to
detect features of NSS (such as OAEP).
> Set CMake required version to 3.14

- org/mozilla/jss/netscape/security/util/Cert.java
The `Cert.mapCertFromPKCS7()` has been modified to chain
the original exception to help troubleshooting.
> Fix exception handling in Cert.mapCertFromPKCS7()

- org/mozilla/jss/netscape/security/pkcs/PKCS7.java
- org/mozilla/jss/netscape/security/x509/CertificateChain.java
The `CertificateChain` class has been modified to support importing/exporting certificates from/to a series of PEM certificates or PKCS #7 data. This is needed for https://github.com/dogtagpki/pki/pull/3459.
Note: The some of the CI tests are failing due to an existing issue.
> Add CertificateChain converters

- cmake/JSSConfig.cmake
The `BETA` flag in `JSSConfig.cmake` has been set to `1` to
enable some pre-release tests.
> Enable BETA flag

- tools/run_container.sh
Per @cipherboy's suggestion the `tools/run_container.sh` has
been modified to use `docker` instead of `buildah`/`podman`
if available.
> Fix build preference in tools/run_container.sh

- org/mozilla/jss/crypto/KeyPairGeneratorSpi.java
- org/mozilla/jss/pkcs11/PK11KeyPairGenerator.java
The `KeyPairGeneratorSpi.Usage` class has been converted into
an enumeration that defines the same elements. These elements
store the values of the corresponding PKCS #11 constants.
The `getVal()` method has been deprecated, but it will continue
to work as before for backward compatibility.
The `opFlags` and `opFlagsMask` fields in `PK11KeyPairGenerator`
have been converted to `long` to match the PKCS #11 constants.
The values will be down-casted to `int` whenever needed.
The `opFlagForUsage` array in `PK11KeyPairGenerator` has become
redundant since the PKCS #11 constants can be obtained from
the enumeration elements, so it has been removed.
> Convert KeyPairGeneratorSpi.Usage into enumeration

- org/mozilla/jss/crypto/KeyPairGeneratorSpi.java
- org/mozilla/jss/crypto/SymmetricKey.java
- org/mozilla/jss/pkcs11/PK11KeyGenerator.java
- org/mozilla/jss/pkcs11/PK11KeyWrapper.java
The `SymmetricKey.Usage` class has been converted into an
enumeration that defines the same elements. These elements
store the corresponding PKCS #11 `CKF_` and `CKA_` values
although the `CKA_` values are not actually used.
The `getVal()` and `getPKCS11Constant()` method have been
deprecated, but they will continue to work as before for
backward compatibility.
The `opFlags` field in `PK11KeyGenerator` has been converted
to `long` to match the PKCS #11 value. The value will be
downcasted to `int` whenever needed.
The `opFlagForUsage` array in `PK11KeyGenerator` has become
redundant since the PKCS #11 value can be obtained from
the enumeration elements, so it has been removed.
> Convert SymmetricKey.Usage into enumeration

- .github/workflows/pki-tests.yml
- .gitignore
- Dockerfile
- tests/bin/ds-artifacts-save.sh
- tests/bin/ds-create.sh
- tests/bin/ds-remove.sh
- tests/bin/pki-artifacts-save.sh
- tests/bin/runner-init.sh
A `Dockerfile` has been added to define the builder image and test
runner image for JSS. The builder image is used to install the
build dependencies and then build JSS. The test runner image is
used to install JSS with its runtime dependencies then run tests.
A new test has been added to install DS and CA with the newly
built JSS packages.
Some scripts have been added to initialize the test runner, to
create and remove DS, and to save the test artifacts.
> Add CA installation test

- cmake/JSSConfig.cmake
`man javac` has the following to say about `-sourcepath`:
> Specifies the source code path to search for class or interface
> definitions.
In particular, the way the CMake step is constructed, the test paths are
specified via file (hence `@${JAVA_TEST_SOURCES_FILE}` as an argument to
`javac`), but the compiling the tests still needs knowledge of the main
JSS source.
In this case, `sourcepath` (for test compilation) was incorrectly updated
to point back at the list of sources we already provided (or, the
directory containing the sources we already provided) instead of
pointing at the path of the main JSS code.
Prior to this change, compilation depended on order steps were executed
and could fail with the following error (if tests were attempted to be
built prior to main sources finishing …
> Fix -sourcepath for java test compilation

- .github/workflows/required-v4.4.x.yml
- .gitignore
There is no CI for this branch.
**Edit:** Apparently there are CI tests in this branch, but they run under a specific [branch name](https://github.com/dogtagpki/jss/blob/v4.4.x/.github/workflows/required-v4.4.x.yml#L5-L9) only. Thanks to @cipherboy, I've updated the workflow to run under all branch names, and dropped the outdated tests.
> Update .gitignore for JSS 4.4

- .github/workflows/maven-tests.yml
- .gitignore
- pom.xml
This PR adds a basic `pom.xml` to build JSS and run the unit tests using Maven on Java 11.
A GitHub workflow is added to execute the build and the tests automatically on every check-in.
There is an existing PR (#636) by @cipherboy but it's not ready to be merged as is. Basically we're breaking it into smaller PRs and incrementally incorporate the elements from that PR. Once all elements are merged we can close it too.
> Add pom.xml and test for Maven

- .github/workflows/build.yml
- pom.xml
Create a new CI job called "build" which builds from source using Maven,
then runs the Sonar analysis job. The quality gate is set to be advisory
only so it never fails, to prevent error fatigue. The intended use is
"free robotic review" of code quality, rather than any enforcement.
> Enable SonarCloud checking of new code

- src/main/java/org/mozilla/jss/ssl/javax/JSSServerSocket.java
- src/main/java/org/mozilla/jss/ssl/javax/JSSSocket.java
Due to the new `@Override` method, Sonar has caught missing synchronized
keywords on several `JSSSocket` and `JSSServerSocket` methods.
> Make this method "`synchronized`" to match the parent class
> implementation.
>
> When `@Overrides` of `synchronized` methods are not themselves
> `synchronized`, the result can be improper synchronization as callers
> rely on the thread-safety promised by the parent class.
`Signed-off-by: Alexander Scheel <alex.scheel@canonical.com>`
> Add missing synchronized keywords to Sockets

- src/main/java/org/mozilla/jss/ssl/javax/JSSSocketChannel.java
Sonar reports the following on the (now removed) return statement:
> Remove this return statement from this finally block.
>
> Using `return`, `break`, `throw`, and so on from a `finally` block suppresses
> the propagation of any unhandled `Throwable` which was thrown in the
> `try` or `catch` block.
Re-do the logic to fix this bug.
`Signed-off-by: Alexander Scheel <alex.scheel@canonical.com>`
---
Note that this is likely a popular path as most sockets we construct will be `Socket` instances and not `SocketChannel`s.
> Fix return from finally in JSSSocketChannel

- src/main/java/org/mozilla/jss/util/NativeErrcodes.java
A comment here declares Fortezza deprecated, but the Javadoc deprecation
only applies to the first constant, so deprecate the rest too.
> Deprecate constants in NativeErrcodes

- .github/workflows/required.yml
- tools/Dockerfiles/ubuntu_jdk11
I used some Java 11 syntax and this test failed (correctly, of course).
We should update this workflow to use OpenJDK11 so we can make use of new language features
> Bump ubuntu_jdk8 -> 11 in github CI workflows

- tools/Dockerfiles/fedora_33
- tools/build_pkcs11_constants.py
The `build_pkcs11_constants.py` has been modified to send log messages to the screen instead of storing them in the output file. This way the output file will remain constant regardless how the tool was executed, and the log messages can be viewed without
having to open the output file which will make it easier to troubleshoot issues.
> Add logger for build_pkcs11_constants.py

- tools/Dockerfiles/fedora_34
- tools/build_pkcs11_constants.py
This PR depends on PR #740.
Currently the PKCS #11 constants test is failing on Fedora 34 and Rawhide:
```
/tmp/tmp-jss-pkcs11constants-zbw7io_w/test.c: In function ‘main’:
/tmp/tmp-jss-pkcs11constants-zbw7io_w/test.c:6:17: error: ‘CKF_EC_FP’ undeclared (first use in this function); did you mean ‘CKF_EC_F_P’?
6 |             if (CKF_EC_FP != 0x00100000) {
|                 ^~~~~~~~~
|                 CKF_EC_F_P
/tmp/tmp-jss-pkcs11constants-zbw7io_w/test.c:6:17: note: each undeclared identifier is reported only once for each function it appears in
main()
File "/home/sandbox/jss/./tools/build_pkcs11_constants.py", line 806, in main
check_references(objs)
File "/home/sandbox/jss/./tools/build_pkcs11_constants.py", line 610, in check_references
obj.check_output(nss_args)
File …
```
> Add PKCS11Constants test for Fedora 34

- Dockerfile
- jss.spec
The `jss.spec` has been modified to drop `git` dependency so it's no longer required for building the official binaries, but `git` is still needed during development to call `build.sh --with-commit-id`.
> Drop git dependency

- CMakeLists.txt
- cmake/JSSConfig.cmake
- jss.spec
The installation script in `jss.spec` has been converted into CMake script.
The `make` invocations have been modified to make it easier to read the output.
> Convert RPM install script into CMake script

- CMakeLists.txt
- cmake/JSSCommon.cmake
- cmake/JSSConfig.cmake
- cmake/JSSTests.cmake
- docs/build_system.md
- docs/building.md
- docs/dependencies.md
- docs/legacy_building.md
- docs/usage/capabilities_list.md
- docs/using_jss.md
- examples/pom.xml
- jss.spec
- pom.xml
- src/main/java/org/mozilla/jss/CryptoManager.java
- src/test/java/org/mozilla/jss/tests/JSSPackageTest.java
- src/test/java/org/mozilla/jss/tests/JSS_SelfServClient.java
- src/test/java/org/mozilla/jss/tests/JSS_SelfServServer.java
- src/test/java/org/mozilla/jss/tests/TestBuffer.java
- src/test/java/org/mozilla/jss/tests/TestBufferPRFD.java
- src/test/java/org/mozilla/jss/tests/TestPRFD.java
- src/test/java/org/mozilla/jss/tests/TestRawSSL.java
Recently JSS 4.9 was modified to require Java 11. However, older platforms that use JSS 4.8 might have other libraries that will not work with Java 11, so it will not be able to be upgraded to JSS 4.9.
To address the problem, the current JSS 4.9 has been renamed into JSS 5.0 which will only work on newer platforms, and a new JSS 4.9 branch will be created from JSS 4.8 to provide updates for older platforms.
The binaries have also been renamed to `jss.jar` and `libjss.so` to simplify future upgrades.
> Update version number to 5.0.0-alpha1

- README.md
- build.sh
- docs/building.md
- jss.spec
The `build.sh` script has been modified to provide a `dist` and `install` targets to build and install JSS binaries without creating RPM packages. The `jss.spec` has been modified to call `build.sh` instead of calling CMake directly.
> Add build.sh dist and install targets

- .github/workflows/pki-tests.yml
The CA test has been update to match the CA test in PKI:
https://github.com/dogtagpki/pki/blob/master/.github/workflows/ca-tests.yml#L60-L160
This can be used to reproduce issue #781 and test the fix when it becomes available.
> Update PKI CA test

- .gitlab-ci.yml
- docs/development/Synchronizing-GitLab-Branch.adoc
The `.gitlab-ci.yml` has been added to define a job that
can be scheduled to synchronize a branch from upstream
repository to GitLab.
Doc: https://github.com/edewata/jss/blob/gitlab/docs/development/Synchronizing-GitLab-Branch.adoc
> Add GitLab synchronization job

- .github/workflows/pkcs11-tests.yml
- .github/workflows/pki-tests.yml
- tests/bin/init-workflow.sh
The `init-workflow.sh` has been added to configure the test
matrix based on the `BASE64_MATRIX` variable. The test matrix
needs to be base64-encoded since otherwise GitHub will mask
the value rendering it unusable.
https://github.com/dogtagpki/jss/wiki/Configuring-Test-Matrix
> Add init-workflow.sh

- .github/workflows/pkcs11-tests.yml
- .github/workflows/pki-tests.yml
- tests/bin/init-workflow.sh
The `init-workflow.sh` has been modified to load the test
repository from `BASE64_REPO` variable. The test repository
will be configured in the runner image so all tests using
the same image will automatically use the same repository.
https://github.com/dogtagpki/jss/wiki/Configuring-Test-Repository
> Add test repository configuration

- .github/workflows/pkcs11-tests.yml
- .github/workflows/pki-tests.yml
- tests/bin/init-workflow.sh
The `init-workflow.sh` has been modified to test
against the latest Fedora version by default.
> Update default test matrix

- docs/changes/v5.0.0/API-Changes.adoc
- src/main/java/org/mozilla/jss/netscape/security/x509/CertAndKeyGen.java
https://github.com/edewata/jss/blob/deprecation/docs/changes/v5.0.0/API-Changes.adoc
> Drop deprecated methods in CertAndKeyGen

- docs/changes/v4.9.1/API-Changes.adoc
- src/main/java/org/mozilla/jss/netscape/security/x509/RevocationReasonAdapter.java
https://github.com/edewata/jss/blob/v4.9.x-deprecation/docs/changes/v4.9.1/API-Changes.adoc
> Deprecate RevocationReasonAdapter in JSS 4

- .github/workflows/pki-tests.yml
- .github/workflows/required.yml
- Dockerfile
- tools/Dockerfiles/fedora_33
- tools/Dockerfiles/fedora_34
- tools/Dockerfiles/fedora_34_jdk11
- tools/Dockerfiles/pki_build
- tools/Dockerfiles/stylecheck
- tools/Dockerfiles/symbolcheck
JSS 4.9 is only supported up to Fedora 34 for PKI 10.12, so the Fedora container has been changed to `fedora:34` and the  COPR repository has been changed to `@pki/10.12`.
> Update Fedora container and COPR repository

- src/main/java/org/mozilla/jss/crypto/Algorithm.java
- src/main/java/org/mozilla/jss/crypto/DigestAlgorithm.java
- src/main/java/org/mozilla/jss/crypto/HMACAlgorithm.java
- src/main/java/org/mozilla/jss/crypto/KeyGenAlgorithm.java
- src/main/java/org/mozilla/jss/crypto/PBEAlgorithm.java
- src/main/java/org/mozilla/jss/crypto/PKCS11Algorithm.java
- src/main/java/org/mozilla/jss/crypto/SignatureAlgorithm.java
- src/main/java/org/mozilla/jss/crypto/SymmetricKey.java
- src/main/java/org/mozilla/jss/netscape/security/x509/AlgorithmId.java
- src/main/java/org/mozilla/jss/pkcs11/KeyType.java
- src/main/java/org/mozilla/jss/pkcs12/AuthenticatedSafes.java
- src/main/java/org/mozilla/jss/provider/java/security/JSSMessageDigestSpi.java
- src/main/java/org/mozilla/jss/provider/java/security/JSSSignatureSpi.java
- src/main/java/org/mozilla/jss/provider/javax/crypto/JSSKeyGeneratorSpi.java
- src/main/java/org/mozilla/jss/provider/javax/crypto/JSSMacSpi.java
- src/main/java/org/mozilla/jss/provider/javax/crypto/JSSSecretKeyFactorySpi.java
- src/main/java/org/mozilla/jss/ssl/SSLSignatureScheme.java
* Fixed "since" version to `5.0.1`
> Deprecated all SHA-1 constants, classes and enum entries.

- src/main/java/org/mozilla/jss/JSSProvider.java
- src/main/java/org/mozilla/jss/netscape/security/util/CertPrettyPrint.java
- src/main/java/org/mozilla/jss/pkcs7/SignerInfo.java
- src/main/java/org/mozilla/jss/pkix/cms/SignerInfo.java
- src/test/java/org/mozilla/jss/tests/DigestTest.java
- src/test/java/org/mozilla/jss/tests/EnumerationZeroTest.java
* Start by deprecating "SHA", "SHA-1", "SHA_1" and SHA1"
> Override Provider.getService() to log use of deprecated algorithms 

- src/main/java/org/mozilla/jss/JSSProvider.java
* These algorithms are weak/deprecated and their use should be
discontinued in favour of more secure algorithms such as SHA-256
> Add MD2, MD4 and MD5 to JSSProvider DEPRECATED_ALGORITHMS

- azure-pipelines.yml
The build tests in Azure pipelines have been updated to provide `docker` in the container for installing the dependencies as `root`, so it's no longer necessary to use `sudo`.
Resolves: #820
> Fix Azure pipelines

- src/main/java/org/mozilla/jss/util/jssutil.c
Found an issue which was causing the need to add the "explicitness" flag
to the cknfracstrc file.
With this fix that flag will no longer be required.
> Related: Bug 1964176 - KRA PKCS12 support for nCipher sw v12.72+

- symkey/CMakeLists.txt
The symkey library includes dependencies into JSS; this requires that
the JSS classes have already been built (which occurs during the
`generate_java` build target). However, because there was no dependency
between symkey and jss projects, a highly parallel CMake backend like
ninja (or make, given enough cores) would fail to build JSS with import
errors due to missing JSS classes. Adding a dependency on the
`generate_java` build target fixes the ordering.
`Signed-off-by: Alexander Scheel <alexander.m.scheel@gmail.com>`
> Fix symkey/jss parallel build issues

- src/main/java/org/mozilla/jss/CryptoManager.java
If threads are dynamically created and destroyed and
CryptoManager.setThreadToken() is called, a Hashtable will hold onto
references of Threads long after they should be garbage collected.
> Don't hold onto threads after they're gone

- src/main/java/org/mozilla/jss/CryptoManager.java
- src/main/java/org/mozilla/jss/JSSProvider.java
- src/test/java/org/mozilla/jss/tests/JSSPackageTest.java
* Also modify constructor to use non-deprecated superclass constructor.
> Drop SHA-1 references from JSSProvider

- src/main/java/org/mozilla/jss/nss/SSLFDProxy.java
- src/main/java/org/mozilla/jss/ssl/javax/JSSEngineReferenceImpl.java
- src/main/java/org/mozilla/jss/util/GlobalRefProxy.java
Each TLS connection is leaking a bunch of data that isn't in the heap
and so after 25k requests Tomcat uses about 2.5GB resident memory.
There are large number of relationships that point at each other and we
need to break the cycle so JSSEngineReferenceImpl's finalizer can run
and clear all the native resources these point at.
The lowest impact place to break the cycle was at SSLAlertEvent.engine.
This relationship doesn't seem to be used anywhere.  Once the cycle is
broken, JSSEngineReferenceImpl can be garbage collected and the
finalizer can run.
Signed-off-by: Chris Kelley <ckelley@redhat.com>
> Fix memory leak on each TLS connection

- jss.spec
This was fixed on master already, but didn't make it into this branch.
> Use %{_jvmdir} macro when defining java_home

- src/main/java/org/mozilla/jss/netscape/security/pkcs/PKCS12Util.java
- src/main/java/org/mozilla/jss/netscape/security/util/Cert.java
- src/main/java/org/mozilla/jss/netscape/security/util/CertPrettyPrint.java
- src/main/java/org/mozilla/jss/provider/javax/crypto/JSSTrustManager.java
- src/test/java/org/mozilla/jss/tests/BenchmarkSSLSocket.java
- src/test/java/org/mozilla/jss/tests/ChainSortingTest.java
- src/test/java/org/mozilla/jss/tests/ListCerts.java
The `X509Certificate.getSubjectDN()` and `getIssuerDN()` have been replaced with `getSubjectX500Principal()` and `getIssuerX500Principal()`, respectively, except where the values are converted into `X500Name`.
> Replace deprecated X509Certificate.getSubjectDN() and getIssuerDN()

- src/main/java/org/mozilla/jss/netscape/security/x509/X509CertImpl.java
The original `X509CertImpl.getSubjectDN()` and `getIssuerDN()` would get the subject name and issuer name (which are `X500Name` objects) then downcast them into `Principal` objects.
Since these methods are deprecated, new `getSubjectName()` and `getIssuerName()` methods have been added as replacements. These methods will return the subject name and issuer name directly as `X500Name` objects. They can be used to fix some deprecation warnings in PKI.
> Add X509CertImpl.getSubjectName() and getIssuerName()

- build.sh
- jss.spec
The `build.sh` has been modified to provide options such that the RPM build can be done according to the RPM specification.
It will also set the environment variables for CMake as defined in `/usr/lib/rpm/macros.d/macros.cmake`.
> Add build.sh options for RPM build

- src/main/java/org/mozilla/jss/netscape/security/x509/CRLDistributionPoint.java
* Use try-with-resources in `CRLDistributionPoint`
* Put array designator on the type in `main` method
* Fix potential infinite loop by checking whether stream is empty.
> Fix bugs identified by Sonar in x509 classes

- .copr/Makefile
The `.copr/Makefile` has been updated to fix COPR build failure caused by changes in Git 2.35.2:
```
fatal: unsafe repository (<current dir> is owned by someone else)
```
https://stackoverflow.com/questions/71901632/fatal-unsafe-repository-home-repon-is-owned-by-someone-else
> Fix COPR build failure

- tests/bin/ds-create.sh
The latest OpenLDAP clients no longer have the `-h` option so the the tests have been updated to use the `-H` option instead.
https://github.com/dogtagpki/pki/wiki/DS-Installation
> Update OpenLDAP clients to use -H option

- .github/workflows/build-tests.yml
- .github/workflows/maven-tests.yml
- README.md
- azure-pipelines.yml
- cmake/JSSConfig.cmake
- cmake/Java.cmake
- pom.xml
- src/main/java/org/mozilla/jss/netscape/security/x509/X509CRLImpl.java
- tools/Dockerfiles/fedora_rawhide
* Reorder modifiers to match the JLS
* Rename static constant to match JLS
* Remove commented out code
* Use pattern matching with instanceof
* Remove unnecessary else clauses
* Use ternary operator where appropriate
* Put array designator on the type not the variable
* Remove unnecessary negation in logic of parse() method
> Tidy up X509CRLImpl

- .github/workflows/code-analysis-pull.yml
- .github/workflows/code-analysis.yml
Sonarcloud plug-in for maven allows to publish analyses without token if the project accept anonymous users. This allows to perform analysis on pull request from fork repository but have a side effect. Actions run in the fork can update analysis on Sonarcloud. As an example, the list of branch in Sonarcloud projects includes some branches from fork repository.
User could update also the analysis on master branch working in the fork.
Configuration on Sonarcloud is updated to avoid this behaviour and the change in this PR will work allows to work with PR from fork repositories.
> Sonarcloud token

- .github/workflows/code-analysis-pull.yml
- .github/workflows/code-analysis.yml
After the PR #869 maven build does not work if the CMake build is not
execute before. This is due to properly generate the header for the native
code.
Since Sonarcloud is configured with maven build and it does not check c
code for the moment, the native module has been disabled for the code
analysis.
> Fix the compilation error on Sonarclod with maven

- base/src/main/java/org/mozilla/jss/SecretDecoderRing/package.html
- base/src/main/java/org/mozilla/jss/asn1/package.html
- base/src/main/java/org/mozilla/jss/crypto/package.html
- base/src/main/java/org/mozilla/jss/package.html
- base/src/main/java/org/mozilla/jss/pkcs10/package.html
- base/src/main/java/org/mozilla/jss/pkcs12/package.html
- base/src/main/java/org/mozilla/jss/pkcs7/package.html
- base/src/main/java/org/mozilla/jss/pkix/cert/package.html
- base/src/main/java/org/mozilla/jss/pkix/cmc/package.html
- base/src/main/java/org/mozilla/jss/pkix/cmmf/package.html
- base/src/main/java/org/mozilla/jss/pkix/cms/package.html
- base/src/main/java/org/mozilla/jss/pkix/crmf/package.html
- base/src/main/java/org/mozilla/jss/pkix/primitive/package.html
- base/src/main/java/org/mozilla/jss/ssl/package.html
Missing elements identified by Sonarcloud in html files.
Actually, these files are manipulated by javadoc so it should not be needed!
> Add doctype and missing html tags

- .github/workflows/code-analysis-pull.yml
- .github/workflows/code-analysis.yml
- pom.xml
According to sonarcloud documentation the project id should not go
anymore in the pom.xml but it is derived or can be provided in the
command line.
The definition in the pom.xml generate an error
> Sonarclout project name changes

- base/src/main/java/org/mozilla/jss/asn1/BIT_STRING.java
Promotion bugs appen when a signed byte is converted to a signed int if
the upper bits are not masked.
See
https://wiki.sei.cmu.edu/confluence/display/java/NUM52-J.+Be+aware+of+numeric+promotion+behavior
and
http://findbugs.sourceforge.net/bugDescriptions.html#BIT_IOR_OF_SIGNED_BYTE
> Fix promotion bugs

- base/src/main/java/org/mozilla/jss/util/UTF8Converter.java
An if condition was never accessed because equal of a previous one.
> Fix UTF-8 conversion

- .github/workflows/code-analysis.yml
Currently the job fails because of a few warnings, but should be quick to fix in a separate PR.
> Run shellcheck in JSS CI

- tests/bin/tomcat-start-wait.sh
A partial reversion which preserves the test while still allowing `shellcheck` to not issue warnings.
> Fix test failure introduced by efforts to fix shellcheck warnings

- .github/workflows/code-analysis-pull.yml
- .github/workflows/code-analysis.yml
In case of commits to different branches the rebase has to be performed against the base branch of the PR. However, the code analysis execute in a `workflow_run` event and it has no information of the PR base, as in the [docuemtnation](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#webhook-payload-example-51).
The available options are:
- to store the base branch during the original PR event and retrieve this information during the workflow run
- to retrieve the base branch using some javascript code interacting with GitHab rest API.
The former is followed here.
Of course, in order to work Sonarcloud in all the branch these have to include the relative workflows but this is required in any case to perform the analysis of them.
> Make the base branch generic

- jss.spec
JSS doesn't seem to be working well with NSS 3.81:
https://github.com/dogtagpki/jss/issues/882
As a temporary workaround the RPM spec has been updated to require an older NSS version. Once the issues are resolved this limitation should be removed.
> Workaround for NSS 3.81 issues

- jss.spec
This should fix problems in Fedora copr repos where the `nss-devel` version was still 3.81, and subsequently refuses to install `nss`.
https://copr.fedorainfracloud.org/coprs/g/pki/master/build/4686508/
> Fix BuildRequires typos so fix Fedora JSS build issues

- jss.spec
The workaround has been reverted since it was causing build issues in COPR:
```
Error:
Problem 1: cannot install both nss-tools-3.81.0-1.fc36.x86_64 and nss-tools-3.77.0-1.fc36.x86_64
- cannot install the best candidate for the job
- conflicting requests
Problem 2: cannot install both nss-devel-3.81.0-1.fc36.x86_64 and nss-devel-3.77.0-1.fc36.x86_64
- cannot install the best candidate for the job
```
> Revert workaround for NSS 3.81 due to COPR issues

- jss.spec
This way we only build on archs that Java builds on.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2104064
> Replace exclusion of i686 with new %{java_arches} macro

- base/src/main/java/org/mozilla/jss/ssl/javax/JSSEngine.java
- base/src/main/java/org/mozilla/jss/ssl/javax/JSSSession.java
On low latency networks (LAN), large posts or file uploads would hang near the end of the transfer and report socket timeout exceptions.
On slower networks (VPN), large HTTP requests could silently fail with the input truncated.
I created large.jsp as an example for testing largish posts.  It usually only takes 11kB to 30kB to see this issue.
https://gist.github.com/uplogix-mmcclain/8c7d796b08e55c7fc21e3b38677df7d3
My first attempt at fixing this was #837.  @cipherboy created #838 in response.  The first commit in this series is one of the commits from #838.  The second commit sizes the application buffer to reduce TLS record fragmenting and eliminates the annoying message from Tomcat about resizing buffers beyond what it thinks is maximal: message is triggered by the first commit.
> Socket timeout on large post

- base/src/main/java/org/mozilla/jss/asn1/CountingStream.java
- base/src/main/java/org/mozilla/jss/ssl/SSLServerSocket.java
Some extended class overload synchronized methods with not synchronized methods. This in theory could generate error although it is not the case as [discussed here](https://wiki.sei.cmu.edu/confluence/display/java/TSM00-J.+Do+not+override+thread-safe+methods+with+methods+that+are+not+thread-safe).
Actually, some of these methods overload methods of the class `Vector` and it is not clear to me if the synchronized is really required. If it is required then we have to add, otherwise it could be better to replace with  `ArrayList` as suggested in the java documentation.
> Fix synchronized overload

- jss.spec
`java_arches` macro is only available on newer platforms, so the spec file has been modified to use `ExcludeArch` on older platforms.
This will fix COPR builds on older Fedora versions and RHEL.
> Use ExcludeArch on older platforms

- .github/workflows/build-tests.yml
Currently if a build job fails on e.g. Fedora, the Ubuntu job will cancel. This makes it hard to see whether the other jobs are afflicted with a similar issue, so add continue-on-error so all jobs run to completion.
> Allow other build tests to continue if one fails

- CMakeLists.txt
- symkey/CMakeLists.txt
```
RPM build warnings:
absolute symlink: /usr/lib64/jss/jss-symkey.jar -> /usr/lib/java/jss-symkey.jar
absolute symlink: /usr/lib64/jss/jss.jar -> /usr/lib/java/jss.jar
```
> Fix RPM build warnings due to absolute links

- revert_update_version.sh
- update_version.sh
A new script update_version.sh is introduced, to start to reduce some of the manual burden of building packages. Usage is as:
./update_version.sh <major> <minor> <update> <phase>
...where phase is optional.
In this first iteration, it does the following:
* Updates the spec version to the new version provided
* Commits that change
* Creates a tag based on the new version provided
* Creates a source tarball based on the new version provided
A companion script is also included to revert the version update, if required.
> Introduce new scripts to automate the build process

- base/src/test/java/org/mozilla/jss/tests/GenerateTestCert.java
- base/src/test/java/org/mozilla/jss/tests/SSLClientAuth.java
Certificate generated for the test are not valid when _RSA_ is used because the signature algorithm in the `signature` field of `TBSCertificate` section is different from the `signatureAlgorithm` field. The last was including an empty parameter not presenti in the first.
I have added the empty parameter and now the certificate are the valid.
Fix  #882
> Fix certificate signature algorithm not valid

- .github/workflows/build-tests.yml
- .github/workflows/code-analysis-pull.yml
- .github/workflows/code-analysis.yml
- .github/workflows/known_failures.yml
- .github/workflows/pkcs11-tests.yml
- .github/workflows/pki-tests.yml
- .github/workflows/tomcat-tests.yml
- tests/bin/init-workflow.sh
Some action are using [Node.js v12 and this has been deprecated by GitHub](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/).
Additionally, the use of [`set-state` and `set-output` has been deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
Therefore the workflows are updated to the new version of the actions.
> Update workflows to use not deeprecated actions

- tests/bin/runner-init.sh
Systemd has some problem to run in docker container if the host uses only cgroups2.
This could make the run container failing with the error:
Failed to create /init.scope control group: Read-only file system Failed to allocate manager object: Read-only file system [!!!!!!] Failed to allocate manager object.
Exiting PID 1...
A possible solution is fo use docker.slice as proposed here: https://serverfault.com/questions/1053187/systemd-fails-to-run-in-a-docker-container-when-using-cgroupv2-cgroupns-priva
> Modify container cgroup

- base/src/main/java/org/mozilla/jss/JSSProvider.java
- base/src/main/java/org/mozilla/jss/crypto/Algorithm.java
- base/src/main/java/org/mozilla/jss/crypto/HMACAlgorithm.java
- base/src/main/java/org/mozilla/jss/crypto/KeyGenAlgorithm.java
- base/src/main/java/org/mozilla/jss/crypto/PBEKeyGenParams.java
- base/src/main/java/org/mozilla/jss/pkcs11/PK11KeyGenerator.java
- base/src/main/java/org/mozilla/jss/pkcs12/AuthenticatedSafes.java
- base/src/main/java/org/mozilla/jss/pkcs12/MacData.java
- base/src/main/java/org/mozilla/jss/pkcs12/PFX.java
- base/src/main/java/org/mozilla/jss/pkcs7/EncryptedContentInfo.java
- base/src/main/java/org/mozilla/jss/pkix/primitive/PBES2Params.java
- base/src/main/java/org/mozilla/jss/pkix/primitive/PBKDF2Params.java
- base/src/main/java/org/mozilla/jss/provider/javax/crypto/JSSKeyGeneratorSpi.java
- native/src/main/native/org/mozilla/jss/crypto/Algorithm.c
- native/src/main/native/org/mozilla/jss/crypto/Algorithm.h
- native/src/main/native/org/mozilla/jss/pkcs11/PK11KeyGenerator.c
The validation of pk12 file with certificate in `:pkcs7-encryptedData` fails because the ASN1 decode work only for PBES1. 
See https://bugzilla.redhat.com/show_bug.cgi?id=2115765.
With this PR the decode does not work but there are problem with the key generation but can be managed in a separate PR/task.
> Add ASN1 decoding of encrypted data using PBES2 algorithm

- .dockerignore
- .github/workflows/build.yml
The build job has been modified to cache the runtime and build dependencies.
> Cache jss-deps and jss-builder-deps images

- .github/workflows/publish.yml
A new job has been added to publish JSS images to GH Packages after the build job in the master branch is complete.
In my repo the publish job worked like this:
https://github.com/edewata/jss/actions/runs/3729493851
and published the following packages:
https://github.com/edewata?tab=packages&repo_name=jss
> Add publish job

- .github/workflows/pki-tests.yml
- .github/workflows/publish.yml
- Dockerfile
- tests/bin/init-workflow.sh
The GitHub workflows have been modified to no longer use a COPR repo by default. Instead, it will install packages from GitHub Packages. The Azure Pipelines still have a dependency on COPR. It will be removed separately later.
> Drop default COPR repo

- .dockerignore
- .github/workflows/build.yml
- .github/workflows/publish.yml
- Dockerfile
The CI has been modified to store the RPMs in an Alpine-based image and publish it to GH Packages to reduce the size of the distribution.
> Add jss-dist image

- .github/workflows/build.yml
- .github/workflows/init.yml
- .github/workflows/pkcs11-tests.yml
- .github/workflows/pki-tests.yml
- .github/workflows/publish.yml
- .github/workflows/tomcat-tests.yml
- tests/bin/init-workflow.sh
Previously the `BASE64_MATRIX` parameter provided a mechanism to test against multiple Fedora versions at once. However, since the test resources are limited and only one of the versions is eventually published, the parameter has been replaced with a new `BASE64_OS` parameter which only supports a single Fedora version.
https://github.com/dogtagpki/pki/wiki/Configuring-Test-OS
> Replace BASE64_MATRIX with BASE64_OS

- .github/workflows/init.yml
- .github/workflows/publish.yml
- tests/bin/init-workflow.sh
The publish job has been modified to support container registry configuration and will only run if the registry is configured. The job will also no longer publish the runner image since it's only used internally.
https://github.com/dogtagpki/pki/wiki/Configuring-Container-Registry
> Add support for container registry configuration

- native/src/main/native/org/mozilla/jss/pkcs11/PK11KeyPairGenerator.c
The error stop the building only with debug enabled and all warning enabled. This is not a problem but it blocks the `sandbox-test` which exit with error.
The error is arise only in fedora rawhide and not in fedora 37.
The current logic of the application does not change.
> Fix warning for accessing `-Werror=maybe-uninitialized`

- .github/workflows/external-application-connection-tests.yml
- base/src/test/java/org/mozilla/jss/tests/JSSConnectionPostgres.java
The test to verify the communication with postgresql deploy the ACME subsystem with the DB as back-end and ssl enabled.
A new test has been written to perform a simple communication with postgresql using the only JSS.
The previous test could be deleted or moved to pki to test ACME with external DB.
> Add test for connection with postgresql

- base/src/main/java/org/mozilla/jss/asn1/OBJECT_IDENTIFIER.java
- base/src/main/java/org/mozilla/jss/netscape/security/extensions/GenericASN1Extension.java
- base/src/main/java/org/mozilla/jss/netscape/security/pkcs/PKCS10Attributes.java
- base/src/main/java/org/mozilla/jss/netscape/security/x509/AVA.java
- base/src/main/java/org/mozilla/jss/netscape/security/x509/CRLExtensions.java
- base/src/main/java/org/mozilla/jss/netscape/security/x509/CertificateExtensions.java
- base/src/main/java/org/mozilla/jss/netscape/security/x509/Extensions.java
- base/src/main/java/org/mozilla/jss/netscape/security/x509/RDN.java
- base/src/main/java/org/mozilla/jss/netscape/security/x509/X500Name.java
- base/src/main/java/org/mozilla/jss/provider/java/security/KeyFactorySpi1_2.java
- base/src/main/java/org/mozilla/jss/util/Base64InputStream.java
The method `toString()` does never return `null` and the subclasses should maintain its original behaviour. Similarly, some syncronized methods were overrided without the `syncronize` modifier.
Finally, some conditions were not possible.
> Fix some Sonar Cloud issues

- base/src/main/java/org/mozilla/jss/netscape/security/extensions/ExtendedKeyUsageExtension.java
- base/src/main/java/org/mozilla/jss/netscape/security/pkcs/PKCS8Key.java
- base/src/main/java/org/mozilla/jss/netscape/security/util/CertPrettyPrint.java
- base/src/main/java/org/mozilla/jss/netscape/security/util/CrlPrettyPrint.java
- base/src/main/java/org/mozilla/jss/netscape/security/util/ExtPrettyPrint.java
- base/src/main/java/org/mozilla/jss/netscape/security/util/PubKeyPrettyPrint.java
- base/src/main/java/org/mozilla/jss/netscape/security/util/Utils.java
- base/src/main/java/org/mozilla/jss/netscape/security/x509/CRLDistributionPointsExtension.java
- base/src/main/java/org/mozilla/jss/netscape/security/x509/ExtensionsRequested.java
- base/src/main/java/org/mozilla/jss/netscape/security/x509/FreshestCRLExtension.java
- base/src/main/java/org/mozilla/jss/netscape/security/x509/OIDMap.java
- base/src/main/java/org/mozilla/jss/netscape/security/x509/X509CertImpl.java
- base/src/main/java/org/mozilla/jss/netscape/security/x509/X509CertInfo.java
- base/src/main/java/org/mozilla/jss/netscape/security/x509/X509Key.java
- base/src/main/java/org/mozilla/jss/pkcs12/PFX.java
The `printStackTrace()` output should not be used in production because it can leak information and cannot be disabled.
The method is deleted or converted to log.
Note: some tests and client code still use the method
> Removde printStackTrace()

- base/src/main/java/org/mozilla/jss/netscape/security/pkcs/PKCS9Attribute.java
- base/src/main/java/org/mozilla/jss/ssl/javax/JSSSocketChannel.java
Some `switch` cases are not closed by a break.
Actually, it is not a problem because following cases are safe or not possible but `break` is added and exception in case of not reachable case.
> Fix switch issue

- cmake/Java.cmake
- symkey/CMakeLists.txt
The `javac()` function in CMake has been modified to provide an option to specify where to generate the native header files. The `symkey` module has been modified to use this option.
> Update javac() to support HEADER_DIR

- .github/workflows/pki-tests.yml
- .github/workflows/pki-tools-test.yml
A new test has been added to test AES key using PKI tools which can be used to validate JSS symmetric key library. Tests for other types of key may be added later.
> Add PKI tools test

- .github/workflows/build-tests.yml
- jss.spec
- pom.xml
- symkey/pom.xml
A `pom.xml` has been added to define Maven module for symkey. The build test has been added to compare the `jss-symkey.jar` created by CMake and by Maven to ensure that they contain the same files.
For now Maven will only build symkey Java code and SonarCloud will ignore symkey native code.
The `jss.spec` has been updated to use Maven dependencies.
> Add Maven module for symkey

- native/pom.xml
Running `mvn install` generate error for messing package name. Investigating and checking the code the artificatId has to be the same of the library generated.
https://stackoverflow.com/questions/25138413/java-jni-maven-native-maven-plugin-how-to-set-shared-library-final-name https://github.com/mojohaus/maven-native/blob/master/native-maven-plugin/src/main/java/org/codehaus/mojo/natives/plugin/NativeInitializeMojo.java
The install phase is relevant to deploy in the artificat in the local database and use the artifact as dependency
> Fix native filename

- pom.xml
When parent version is managed with a `revision` property in the submodules the generated artificats will have the `version` field not updated do they cannot be consumed by other projects. The solution is to add a plugin transforming the `pom.xml` for the artifact.
References:
- https://maven.apache.org/maven-ci-friendly.html#install-deploy
- https://jeanchristophegay.com/en/posts/maven-unique-version-multi-modules-build/
> Make maven artifcat usabale

- CMakeLists.txt
- build.sh
- symkey/CMakeLists.txt
New options have been added into `build.sh` to support building Java and native binaries separately.
> Add build.sh --without-java and --without-native

- base/src/main/java/org/mozilla/jss/pkix/cert/Certificate.java
- base/src/main/java/org/mozilla/jss/pkix/cert/CertificateInfo.java
- base/src/main/java/org/mozilla/jss/pkix/cmmf/CertRepContent.java
- base/src/main/java/org/mozilla/jss/pkix/cms/DigestInfo.java
- base/src/main/java/org/mozilla/jss/pkix/crmf/CertReqMsg.java
- base/src/main/java/org/mozilla/jss/pkix/primitive/SubjectPublicKeyInfo.java
The main issuees fixed are:
- override of equals and and hash code, (they should be done both)
- check byde read from stream
- removed not possible exceptions
- syntax compliant to Java best practice
> Fix some bugs in org.mozilla.jss.pkix

- .github/workflows/build-tests.yml
- .github/workflows/publish.yml
- base/pom.xml
- examples/pom.xml
- native/pom.xml
- pom.xml
- symkey/pom.xml
A new job has been added to build JSS with Maven and publish the artifacts to GitHub Maven registry. Currently the native and symkey modules have to be disabled due to a build issue. The group ID and artifact ID have been renamed to follow a more commonly used pattern.
Once merged, the packages will look like the following:
https://github.com/edewata?tab=packages&repo_name=jss
> Publish to GitHub Maven registry

- src/main/java/org/mozilla/jss/netscape/security/x509/OIDMap.java
The "Authority Info Access" extension was not included in the oid
extension  map so it was not correctly printed.
This add AIA extension to the oid map.
> [v4.9.x] Fix AIA externsion print

- .classpath
- .github/workflows/build-tests.yml
- azure-pipelines.yml
- base/pom.xml
- base/src/test/java/org/mozilla/jss/tests/PrintableConverterTest.java
- base/src/test/java/org/mozilla/jss/tests/TestRunner.java
- cmake/JSSConfig.cmake
- cmake/JSSTests.cmake
- jss.spec
This is the first junit test converted to junit 5.
In order to run the test also a new runner class is introduced. 
Here the migration documentation: https://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4
The remaining tests make use of junit 4 or makes use of a custom  approach. All of them could be converted to junit 5.
At compile time there is a warning with `org.apiguardian.api.API$Status` which seems related to a library problem in junit 5 but it can be ignored according to many post (e.g. https://stackoverflow.com/questions/46702273/warning-unknown-enum-constant-status-stable).
> Convert tests to JUnit5 (PrintableConverterTest)

- base/src/main/java/org/mozilla/jss/JSSProvider.java
Algorithms such as SHA-1 and MD5 are deprecated but they still have valid uses and in certain cases cannot be replaced easily. The problem is currently code that uses these algorithms generates warnings that can undermine user's confidence in the code. To avoid the problem, the warnings have been converted into regular debug messages which will only appear in debug mode.
> Suppress warnings for deprecated algorithms

- base/src/main/java/org/mozilla/jss/pkcs11/PK11KeyPairGenerator.java
Previously the `Enum.ordinal()` was used to determine the EC curve code which is not reliable since the position of the constants in the enumeration is not guaranteed. A new field has been added into `ECCure_Code` to store a permanent curve code regardless of constant position.
> Replace ECCurve_Code.ordinal() with code()

- base/src/main/java/org/mozilla/jss/pkix/crmf/CertTemplate.java
* Use ternary operator where appropriate
* Document empty constructor
* Put array designator on the type
* Remove unused indent variable, and subsequently unused vars/args
* Remove exception that cannot be thrown from print()
* Use pattern-matching instanceof
> Code clean up in CertTemplate

- base/src/main/java/org/mozilla/jss/pkcs11/PK11KeyPairGenerator.java
The `PK11KeyPairGenerator.getCurveCodeByName()` has been modified to use `ECCurve_Code.valueOf()` to translate the curve name into the curve code instead of using a separate `Hashtable`. If the curve name is not defined in `ECCurve_Code`, the `valueOf()` will throw an `IllegalArgumentException`.
> Refactor PK11KeyPairGenerator.getCurveCodeByName()

- base/src/main/java/org/mozilla/jss/pkcs11/PK11KeyPairGenerator.java
Previously the `PK11KeyPairGenerator.getECCurve()` was using a separate `Hashtable` to store the OIDs of EC curves. To simplify the code the OIDs have been moved into the `ECCurve_Code` enum and the `getECCurve()` has been modified to get the OID from the enum.
> Refactor PK11KeyPairGenerator.getECCurve()

- base/src/main/java/org/mozilla/jss/pkcs11/PK11KeyPairGenerator.java
- base/src/main/java/org/mozilla/jss/util/ECOIDs.java
The EC curve OID constants in `PK11KeyPairGenerator` have been consolidated into `ECOIDs`.
> Consolidate EC curve OIDs

- base/src/main/java/org/mozilla/jss/pkcs11/PK11Token.java
The `PK11Token.generateCertRequest()` has been modified to generate a CSR with the header and footer described in RFC 7468.
See also:
* https://datatracker.ietf.org/doc/html/rfc7468#section-7
* https://github.com/dogtagpki/pki/issues/3843
> Drop legacy CSR header/footer

- src/main/java/org/mozilla/jss/netscape/security/x509/OIDMap.java
Subject Info Access extension  was not included in the oid map and printed correctly.
> [v4.9.x] Fix SIA externsion print

- base/src/main/java/org/mozilla/jss/ssl/javax/JSSEngineReferenceImpl.java
- base/src/main/java/org/mozilla/jss/ssl/javax/JSSSession.java
The SSLEngine session "JSSSession" has been extended to container the IP addresses of the client and the server. These are used for the audit and have not other use in the protocol. By design the SSLEngine should be unaware of the underlying communication but this is need to keep the original audit format required for the certification.
> Add IPs address to the session

- .classpath
- docs/changes/v5.5.0/Packaging-Changes.adoc
- jss.spec
- pom.xml
- tomcat-9.0/pom.xml
- tomcat-9.0/src/main/java/org/dogtagpki/jss/tomcat/JSSContext.java
- tomcat-9.0/src/main/java/org/dogtagpki/jss/tomcat/JSSImplementation.java
- tomcat-9.0/src/main/java/org/dogtagpki/jss/tomcat/JSSUtil.java
- tomcat/pom.xml
- tomcat/src/main/java/org/dogtagpki/jss/tomcat/Http11NioProtocol.java
- tomcat/src/main/java/org/dogtagpki/jss/tomcat/IPasswordStore.java
- tomcat/src/main/java/org/dogtagpki/jss/tomcat/JSSListener.java
- tomcat/src/main/java/org/dogtagpki/jss/tomcat/PlainPasswordFile.java
- tomcat/src/main/java/org/dogtagpki/jss/tomcat/TomcatJSS.java
To simplify package maintenance, the code from Tomcat JSS master branch has been imported into `tomcat` and `tomcat-9.0` modules which will be distributed as `jss-tomcat` RPM package:
https://github.com/edewata/jss/blob/tomcatjss/docs/changes/v5.5.0/Packaging-Changes.adoc
Later PKI will need to be updated to depend on `jss-tomcat` instead of `tomcatjss`, then `tomcatjss` can be deprecated.
> Import Tomcat JSS project

- .github/workflows/build-tests.yml
The RPM test has been updated to compare JAR files from RPM packages (which were built using XMvn) against JAR files built directly using Maven.
> Update RPM test

- .github/workflows/build-tests.yml
- base/src/main/java/org/mozilla/jss/asn1/SET.java
They were failing because the `rawhide` image in Docker registry is from an old compose, and we are pulling shiny packages from the latest compose, which was causing `dnf`/`dnf5` compat issues. We can prevent this going forward by running images from quay.io, which is updated with every successful `rawhide` compose. 
I did some code clean up in my fork to trigger the CI, so I figure we may as well keep it. It was supposed to be minor but apparently Eclipse saw fit to tidy up some whitespace on-save so apologies about the diff pollution :smile:
> Fix the build tests

- .github/workflows/external-application-connection-tests.yml
The PostgreSQL test has been updated to use LDAP SDK and PKI packages from Quay instead of COPR since it is generally more reliable and older packages will not expire.
> Update PostgreSQL test

- .github/workflows/build-tests.yml
- CMakeLists.txt
- azure-pipelines.yml
- build.sh
- docs/changes/v5.5.0/Packaging-Changes.adoc
- jss.spec
- tests/CMakeLists.txt
A new package has been added for distributing test scripts and binaries.
https://github.com/edewata/jss/blob/build/docs/changes/v5.5.0/Packaging-Changes.adoc
> Add jss-tests package

- base/src/main/java/org/mozilla/jss/crypto/CryptoStore.java
- base/src/main/java/org/mozilla/jss/pkcs11/PK11Store.java
- lib/jss.map
- native/src/main/native/org/mozilla/jss/pkcs11/PK11Store.c
Currently none of the cert import methods provided by JSS works like `certutil -A` since they call different NSS functions so in some cases it's necessary to call this external command from Java which could be problematic and does not work well with HSM.
To address the problem the `PK11Store.importCert()` has been added to call the same NSS functions used by `certutil -A` so it's no longer necessary to call this external command from Java.
https://github.com/dogtagpki/nss/blob/master/cmd/certutil/certutil.c#L102-L182
> Add PK11Store.importCert()

- .github/workflows/build-tests.yml
- .github/workflows/build.yml
- .github/workflows/external-application-connection-tests.yml
- .github/workflows/pkcs11-tests.yml
- .github/workflows/pki-build-test.yml
- .github/workflows/pki-ca-test.yml
- .github/workflows/pki-tools-test.yml
- .github/workflows/pki-tps-test.yml
- .github/workflows/publish.yml
- .github/workflows/tomcat-tests.yml
- azure-pipelines.yml
- tests/bin/runner-init.sh
- tools/Dockerfiles/stylecheck
The tests in GitHub and Azure DevOps have been modified to run using the latest Fedora by default, but it can be changed using the `BASE_IMAGE` param.
The GitHub tests have also been updated to reuse the images created by the build workflow. The build workflow has also been modified to store the images in a single cache instead of separate caches.
The `runner-init.sh` has been modified to use a positional argument to specify the container name and use `jss-runner` image by default.
https://github.com/dogtagpki/pki/wiki/Configuring-Test-OS
> Fix BASE_IMAGE param

- native/src/main/native/org/mozilla/jss/ssl/SSLCipher.c
The `kea_alg_defs` array in `SSLCipher.c` has been updated to match the one defined in NSS 3.97. The assertion that compares the size of the array with `ssl_kea_size` has also been removed. These changes will allow JSS to work with the newer NSS 3.97 on Fedora Rawhide as well as the older NSS versions on other platforms.
Resolves: https://github.com/dogtagpki/jss/issues/991
Note: With these changes the build now works on Rawhide and most tests pass too. There are some failures, but they don't seem to be related so they need to be investigated separately:
* https://github.com/edewata/jss/actions/runs/7821129758/job/21337674464#step:11:559
* https://github.com/edewata/jss/actions/runs/7821129726/job/21337673840#step:7:2220
> Update kea_alg_defs to match NSS 3.97

- .github/workflows/pkcs11-tests.yml
- tools/build_pkcs11_constants.py
The PKCS #11 constants test failed on Fedora 40 since it uses NSS 3.97 that provides some new PKCS #11 constants. As a workaround the new constants need to be excluded until NSS 3.97 becomes available on all supported platforms.
The test has also been modified to reuse the `jss-builder` image which already has the build dependencies.
Resolves: https://github.com/dogtagpki/jss/issues/993
> Fix PKCS #11 constants test

- Dockerfile
- jss.spec
The RPM spec has been updated to use Java 21 on Fedora 40 or later and Java 17 on other platforms.
The `Dockerfile` has been modified to remove any Java packages pulled by the existing JSS package to ensure that the build will be done using the correct Java version.
> Update Java dependencies

- base/src/main/java/org/mozilla/jss/netscape/security/extensions/ExtendedKeyUsageExtension.java
- base/src/main/java/org/mozilla/jss/netscape/security/extensions/InhibitAnyPolicyExtension.java
- base/src/main/java/org/mozilla/jss/netscape/security/extensions/OCSPNoCheckExtension.java
- base/src/main/java/org/mozilla/jss/netscape/security/util/ExtPrettyPrint.java
- base/src/main/java/org/mozilla/jss/netscape/security/x509/OIDMap.java
Pretty print some additional OID:
OCSP No Check - id-pkix-ocsp-nocheck { 1.3.6.1.5.5.7.48.1.5} Inhibit Any Policy {2.5.29.54}
Extended Key Usage:
- serverAuth {1 3 6 1 5 5 7 3 1}
- clientAuth {1 3 6 1 5 5 7 3 2}
- codeSigning {1 3 6 1 5 5 7 3 3}
- emailProtection {1 3 6 1 5 5 7 3 4}
> Fix missing OID mappings

- build.sh
- docs/changes/v5.6.0/Packaging-Changes.adoc
- jss.spec
- tools/CMakeLists.txt
- tools/src/main/native/p7tool/CMakeLists.txt
- tools/src/main/native/p7tool/NSPRerrs.h
- tools/src/main/native/p7tool/SECerrs.h
- tools/src/main/native/p7tool/SSLerrs.h
- tools/src/main/native/p7tool/p7tool.c
- tools/src/main/native/p7tool/pppolicy.c
- tools/src/main/native/p7tool/secerror.c
- tools/src/main/native/p7tool/secerror.h
- tools/src/main/native/p7tool/secpwd.c
- tools/src/main/native/p7tool/secutil.c
- tools/src/main/native/p7tool/secutil.h
The `p7tool` command has been moved from `pki-tools` to `jss-tools`.
https://github.com/edewata/jss/blob/tools/docs/changes/v5.6.0/Packaging-Changes.adoc
**Note:** Some tests are failing due to conflicts. They need to be rerun after PKI PR [#4700](https://github.com/dogtagpki/pki/pull/4700) is merged.
> Add p7tool

- base/src/main/java/org/mozilla/jss/pkcs12/PFX.java
Previously the `PFX.verifyAuthSafes()` discarded the original exception and simply returned a generic error message which was usually insufficient to determine the cause of the issue.
To help troubleshooting, the `PFX.verifyAuthSafes()` has been modified to throw the exception so the original error message and the stack trace are preserved.
> Update exception handling in PFX.verifyAuthSafes()

- docs/changes/v5.6.0/Parameter-Changes.adoc
- native/src/main/native/org/mozilla/jss/ssl/common.c
- tomcat/src/main/java/org/dogtagpki/jss/tomcat/Http11NioProtocol.java
- tomcat/src/main/java/org/dogtagpki/jss/tomcat/TomcatJSS.java
Currently certificates can be validated only using OCSP with a configured responder or using the AIA certificate extension. If the responder cannot be used verification is not possible. This is the case for the startup certificates of the responder.
The new policy add a verification using the CRL-DP extension defined in the certificate. If this extension is defined it has precedence over the OCSP and if it pass no other check are performed. If CRL cannot be retrieved then the OCSP responder is used. This new method takes place when OCSP is configured without a default responder and the PKIX verification method is adopted (with the policy OCSP_LEAF_AND_CHAIN_POLICY).
At least a verification method has to return success to accept the certificate.
Additionally, the connector parameter …
> Enabling certificate verification using CRL-DP extension

- docs/changes/v5.6.0/API-Changes.adoc
- tomcat/src/main/java/org/dogtagpki/jss/tomcat/PasswordStore.java
- tomcat/src/main/java/org/dogtagpki/jss/tomcat/PlainPasswordFile.java
- tomcat/src/main/java/org/dogtagpki/jss/tomcat/TomcatJSS.java
The `PasswordStore` has been added to replace `IPasswordStore`. The `IPasswordStore` has been deprecated and will be removed in the future.
https://github.com/edewata/jss/blob/deprecation/docs/changes/v5.6.0/API-Changes.adoc
> Replace IPasswordStore with PasswordStore

- src/main/java/org/mozilla/jss/ssl/common.c
When CRLSign key usage is not present NSS crl check will consider the CRL source not present and skip the test. This is against the policy we want to implement.
This change force the need for the information source and the certificate will be marked as revoked if CRLSign is not present.
> Fix CRL check when CA miss CRLSign key usage

- base/src/main/java/org/mozilla/jss/netscape/security/x509/OIDMap.java
OIDMap was not correctly mapping EKU when decoding a certificate to an X509CertImpl object because the name should include the full path from the Root element.
This partially revert the pr #997  where OIDs were reorganised and resolve the error with third party when the certificate verification is not totally delegated to NSS code.
> Fix EKU decoding

- base/src/main/java/org/mozilla/jss/ssl/javax/JSSEngineReferenceImpl.java
Certificates are included in the SSL session also in case of handshake failure. If certificate are not available there are no exception and or error reported beside the one creating the failure.
Certificate information are needed in case of event audits.
> Include certificate information in SSL session

- base/src/test/java/org/mozilla/jss/tests/TestRawSSL.java
With the nss update to >= 3.101 the nss context gets initialised after the CryptoManager instance is retrieved so this step is added before the test.
The original error was in this NSS line: https://github.com/nss-dev/nss/blob/4b0cca5ba45b3713e279f9d528dfa01dd886cea8/lib/nss/nssinit.c#L1002
All the other tests were working because the use of the CryptoManager before performing and operation involving NSS.
Additionally, the ssl option test for get and set has been modified to enable/disable ssl cache since the ssl3 option is policy dependent and do not always work. 
Fix #1010 
Note about the options: running the test with NSS released on fedora using SSL3 option was not working but using my build (I have included debug options) the test works. Looking at the code SSL3 cannot be enabled if …
> Fix test 17 error on build

- .github/workflows/publish.yml
- pom.xml
Previously JSS's Maven artifacts were published to [GitHub Packages](https://github.com/orgs/dogtagpki/packages?repo_name=jss) which is a private repository so it's difficult to use.
To resolve the problem, the `pom.xml` has been modified to publish the artifacts to a publicly accessible [dogtagpki/repo](https://github.com/dogtagpki/repo) instead.
https://github.com/dogtagpki/repo/wiki
https://github.com/dogtagpki/repo/wiki/Development-Guide
Once this PR is merged, the artifacts will be pushed into the `maven` branch like this:
https://github.com/edewata/repo/tree/maven
https://github.com/edewata/repo/commits/maven
Then I'll create a PR for LDAP SDK and PKI to use this repository.
> Publish Maven artifacts to dogtagpki/repo

- base/src/main/java/org/mozilla/jss/ssl/SSLSocket.java
- base/src/main/java/org/mozilla/jss/ssl/javax/JSSSocket.java
- docs/changes/v5.6.0/API-Changes.adoc
`SSLSocket` is an older code based on the plain Java `Socket`. `JSSSocket` is a newer code based on Java `SSLEngine` and should eventually replace `SSLSocket`.
To help the transition, `SSLSocket` has been modified to extend `javax.net.ssl.SSLSocket` and `JSSSocket` has been modified to extend `SSLSocket`. Once everything is migrated to `JSSSocket`, the `SSLSocket` can be deprecated and eventually dropped.
https://github.com/edewata/jss/blob/socket/docs/changes/v5.6.0/API-Changes.adoc
> Refactor SSLSocket and JSSSocket

- base/src/main/java/org/mozilla/jss/crypto/InternalCertificate.java
- base/src/main/java/org/mozilla/jss/crypto/TokenCertificate.java
- base/src/main/java/org/mozilla/jss/crypto/X509Certificate.java
- base/src/main/java/org/mozilla/jss/pkcs11/PK11Cert.java
To improve interoperability with standard Java classes, the `org.mozilla.jss.crypto.X509Certificate` interface has been converted into a class that extends `java.security.cert.X509Certificate` and also implements `InternalCertificate` and `TokenCertificate`. The `PK11Cert` class has been modified to extend this class.
> Refactor X509Certificate

- base/src/main/java/org/mozilla/jss/provider/javax/crypto/JSSTrustManager.java
The `JSSTrustManager` has been modified to take an optional `hostname` attribute. If provided, it will be used to validate the SAN extension or the cert subject DN.
> Add hostname validation for JSSTrustManager

- base/src/test/java/org/mozilla/jss/tests/TestKeyGen.java
Fix JSS self tests to not use DSA and generate < 2048 bit RSA keys
Remove / modify JSS self test code that previously generated DSA key pairs and RSA key pairs of < 2048 bit sizes. Also remove tests generating RSA key pairs with smaller than the minimum exponent sizes.
> Fix Red Hat Certificate SystemRHCS-5261:  Fix JSS self tests to not use DSA and generate < 2048 bit RSA keys

- .github/workflows/pki-ca-test.yml
The PKI CA test has been updated to run PKI CLI using blocking and non-blocking socket factories to perform cert validations for variety of cases including self-signed user cert.
Currently there are inconsistencies in the SSL alerts generated by these factories. They will be investigated separately later.
> Add test for self-signed user cert validation

- base/src/main/java/org/mozilla/jss/nss/SSLFDProxy.java
- base/src/main/java/org/mozilla/jss/ssl/SSLHandshakeCompletedEvent.java
- native/src/main/native/org/mozilla/jss/nss/SSLFDProxy.c
- native/src/main/native/org/mozilla/jss/nss/SSLFDProxy.h
- native/src/main/native/org/mozilla/jss/util/java_ids.h
Previously `SSLFDProxy.c` was accessing the fields in `SSLFDProxy` class directly using JNI to update `handshakeComplete` and add SSL alert events into `inboundAlerts` and `outboundAlerts`.
To make it easier to investigate SSL alert issues, `SSLFDProxy` has been updated to implement `SSLSocketListener` then `SSLFDProxy.c` will call `SSLSocketListener` methods to perform the above operations.
> Update SSLFDProxy to implement SSLSocketListener

- .github/workflows/pki-ca-test.yml
- .github/workflows/pki-tps-test.yml
PKI CA and TPS tests have been updated to use DS container from Quay instead of DS packages from Fedora to avoid JSS issue #994.
Resolves: https://github.com/dogtagpki/jss/issues/994
> Fix TPS test failure

- native/src/main/native/org/mozilla/jss/nss/SSLFDProxy.c
The method was used to get SSLSoecketEvent but the mechanism has been modified in the following commit and this is method is not used.
Update SSLFDProxy to implement SSLSocketListener (0f352ecb0848ff549cf6bc255d102e1077bb1eaa)
The problem has been identified and reported as side effect of PR #1024 by @siteshwar
> Remove the unused method JSS_NSS_getEventArrayList()

- .github/workflows/build-tests.yml
- .github/workflows/external-application-connection-tests.yml
- .github/workflows/pki-build-test.yml
- .github/workflows/pki-ca-test.yml
- .github/workflows/pki-tools-test.yml
- .github/workflows/pki-tps-test.yml
- .github/workflows/tomcat-tests.yml
- Dockerfile
- build.sh
Required in Fedora 42.
https://fedoraproject.org/wiki/Changes/Unify_bin_and_sbin
> Make sbin install dir configurable

- .github/workflows/pki-ca-test.yml
- base/src/main/java/org/mozilla/jss/ssl/javax/JSSEngineReferenceImpl.java
When trust manager fails to validate the certificate the generated SSL exception does not trigger any alert. To fix the problem the SSL alert are always verified during the wrap operation.
> Fix missing SSL Alert

- .github/workflows/tomcat-tests.yml
The TLS 1.2 is supported and enabled in the crypto policy so it is enabled in tomcat by default.
> Fix tomcat CI

- .github/workflows/tomcat-https-ciphers-test.yml
- .github/workflows/tomcat-tests.yml
A new GH workflow has been added to test HTTPS in Tomcat with specific ciphers.
> Add test for HTTPS with specific ciphers

- .github/workflows/pki-ca-test.yml
To work properly the JSSTrustManager has to enable the revocation check. This is in the PR [pki#4968](https://github.com/dogtagpki/pki/pull/4968) so this has to wait the merge.
> Add test for reveked check in JSSTrustManager

- .github/workflows/pki-tps-test.yml
The TPS test has been updated to configure the new TPS param added recently which is required for token enrollment: https://github.com/dogtagpki/pki/commit/847ddbc9e146603d11e917609411fde03e301778
> Fix token enrollment failure in TPS test

- .github/workflows/pki-ca-test.yml
- base/src/main/java/org/mozilla/jss/ssl/javax/JSSSocket.java
Invoking multiple times the close() method generate an exception because it calls the init() which tries to access closed channels.
The close() method is defined in Closeable interface and it has to be idempotent so it should be possible to call again without errors.
This is a problem with third party libraries not checking if the socket has been closed but call multiple times the close() method generating error.
An example of the error is in [this test](https://github.com/fmarco76/pki/actions/runs/13988696953/job/391679594390. The socket is closed by the server and and the client gets a notify which will close also the client side. Then the httpclient will close again the socket generating the error.
> Make JSSSocket close() idempotent

- base/src/main/java/org/mozilla/jss/provider/java/security/KeyFactorySpi1_2.java
- base/src/main/java/org/mozilla/jss/util/ECCurve.java
EC key size has been moved into the ECCurve Enum. The key byte arrays are handled with System.arraycopy instead of custom for loops. New private method to convert BigInteger to byte array has been documented.
> Cleanup EC public key generation

- base/pom.xml
- build.sh
- cmake/JSSConfig.cmake
- examples/pom.xml
- jss.spec
- native/pom.xml
- pom.xml
- symkey/pom.xml
- tomcat-9.0/pom.xml
- tomcat/pom.xml
- update_version.sh
The build scripts have been modified to generate RPM version numbers more compliant with Fedora Packaging Guidelines.
https://docs.fedoraproject.org/en-US/packaging-guidelines/Versioning
> Update version number to 5.9.0-alpha1

- CMakeLists.txt
- cmake/JSSConfig.cmake
Note that we still need jss.spec to differentiate NSS versions to decide whether to set ENABLE_NSS_VERSION_PQC_DEF to on or off.
Fix as part of the build task:
https://issues.redhat.com/browse/IDM-2360
> Adding option for ENABLE_NSS_VERSION_PQC_DEF

- CMakeLists.txt
- cmake/JSSConfig.cmake
- jss.spec
- native/src/main/native/org/mozilla/jss/ssl/SSLCipher.c
Fix build failure caused by updated NSS version with new pqc defs int auth_alg_defs[]
For reference, this change corresponds to an NSS patch that currently exists on CentOS 10 only:
https://gitlab.com/redhat/centos-stream/rpms/nss/-/blob/c10s/nss-3.112-add-ml-dsa-ssl-support.patch?ref_type=heads#L965
* Adding option for ENABLE_NSS_VERSION_PQC_DEF (#1053)
* cognizant of the os version.
fixes https://issues.redhat.com/browse/IDM-2428
> Add matching PQC algs to auth_alg_defs[] with NSS
