MPL-1.1.txt
gpl.txt
jss.spec.in
lgpl.txt

A spec template has been added based on the latest JSS spec file.
The license files have been added as well.
https://pagure.io/jss/issue/6

Added JSS spec template and license files

---

org/mozilla/jss/provider/java/security/JSSKeyStoreSpi.java

The JSSKeyStoreSpi.engineAliases() has been modified to return
all aliases from all tokens if the keystore token is not set,
and only aliases from the keystore token if it's set.
https://pagure.io/jss/issue/10

Fixing JSSKeyStoreSpi

---

coreconf/nsinstall/pathsub.c

Address https://pagure.io/jss/issue/21

Strncpy truncation warning

---

org/mozilla/jss/pkcs11/PK11Store.c
org/mozilla/jss/provider/java/security/JSSKeyStoreSpi.c

Addresses https://pagure.io/jss/issue/22

Fix warning: assignment discards ‘const’ qualifier from pointer target type

---

.travis.yml
tools/Dockerfiles/fedora_27
tools/Dockerfiles/fedora_28
tools/Dockerfiles/stylecheck
tools/Dockerfiles/ubuntu_jdk8

- Adds style check / validator stage to check perl and
script styles
- Uses Dockerfiles to perform all tests
- Adds check to ensure Ubuntu build is successful

Update travis.yml to check style and use stages

---

tools/test_perl_style.sh
tools/test_shell_style.sh

Make test scripts exit on first error

---

.travis.yml
tools/run_container.sh
tools/test_shell_style.sh

Makes our infrastructure agnostic of choice of container provider and simplifies our Travis scripts.

Add tool to run container images

---

org/mozilla/jss/pkix/cms/SignedData.java

This is a backport of PR #39 to the `v4.4.x` branch.

Fix docstring for org.mozilla.jss.pkix.cms.SignedData

---

README.md
docs/build_system.md
docs/building.md
docs/ci.md
docs/contributing.md
docs/dependencies.md
docs/legacy_building.md
docs/pkcs11_constants.md
docs/using_jss.md

The last two headers make this RFC, namely, the contribution guide and placing these in the `gh-pages` branch.
Updates to various pieces of documentation and the addition of new documentation.
In particular: 
- We update the build system documentation to reflect the new `html` target and remove the environment variable introduced by @emaldona for building on Debian as it is no longer used.
- We update the documentation on using JSS in a downstream project to reflect the new JAXB dependency.
- We add new documentation on our dependencies, clarifying which are build time / test suite / runtime dependencies.
- We save the old build instructions to a file called `legacy_building.md` in case anyone wishes to refer to them still. 
- Add documentation on PKCS11 Constants. 
- Update the CI …

[RFC] Docs update

---

README.md
docs/build_system.md
docs/building.md
docs/dependencies.md
docs/using_jss.md

Includes various documentation on CMake, updating the in-tree versions.
Acceptance Criteria:

cmake - documentation

---

docs/pkcs11_constants.md

Address: https://pagure.io/jss/issue/31

Update docs/pkcs11constants.md according to new build system

---

cmake/JSSConfig.cmake
jss.spec

Bump version number to v4.5.2

---

README.md

`make check` -> `make test` in README.md

---

org/mozilla/jss/netscape/security/util/Utils.java

- This is an effort to move duplicate code from PKI code
base to JSS code base
- This chunk of code was originally introduced in PKI
code: https://github.com/dogtagpki/pki/pull/131
- This PR is a joined effort of:
https://github.com/dogtagpki/pki/pull/122
Signed-off-by: Dinesh Prasanth M K <dmoluguw@redhat.com>

Add exec method to execute shell commands with input

---

cmake/JSSTests.cmake

Fix parallel ctest execution

---

.classpath
cmake/JSSTests.cmake
org/mozilla/jss/netscape/security/util/Cert.java
org/mozilla/jss/tests/ChainSortingTest.java

A new ChainSortingTest has been added to validate
Cert.sortCertificateChain().

Added ChainSortingTest

---

.copr/Makefile

Add dnf install -y git

---

.copr/Makefile

Use --with-timestamp and --with-commit-id for COPR

---

org/mozilla/jss/CryptoManager.java
org/mozilla/jss/PK11Finder.c
org/mozilla/jss/ssl/callbacks.c
org/mozilla/jss/ssl/common.c
org/mozilla/jss/ssl/jssl.h
org/mozilla/jss/util/java_ids.h

This is a forward port of #121 and #126. For more information, see those corresponding PRs.
@jmagne, what's the testing plan for this look like?

CC: Enable AIA OCSP cert checking for entire certificate chain

---

org/mozilla/jss/CryptoManager.java
org/mozilla/jss/PK11Finder.c
org/mozilla/jss/ssl/callbacks.c
org/mozilla/jss/ssl/common.c
org/mozilla/jss/ssl/jssl.h
org/mozilla/jss/util/java_ids.h

See #166 for discussion; this is a forward port of #121 and #126.

[v4.5.x] CC: Enable AIA OCSP cert checking for entire certificate chain

---

.travis.yml
tools/Dockerfiles/fedora_30

[Fedora 30](https://fedoramagazine.org/announcing-fedora-30/) was released! Let's use it in the CI system. :)

Update CI: Fedora 30

---

.travis.yml
tools/Dockerfiles/fedora_30

Backport of #172 to v4.5.x branch.

[v4.5.x] Update CI: Fedora 30

---

jss.spec

Sync with Fedora spec file

---

cmake/JSSConfig.cmake

Add org.mozilla.jss.nss to javadoc ouput

---

org/mozilla/jss/provider/java/security/JSSKeyStoreSpi.java

~Depends on #158, will be rebased once that merges.~
This updates our [`KeyStoreSpi`](https://docs.oracle.com/javase/8/docs/api/java/security/KeyStoreSpi.html) implementation, [`JSSKeyStoreSpi`](https://dogtagpki.github.io/jss/javadoc/org/mozilla/jss/provider/java/security/JSSKeyStoreSpi.html), to return [`PK11Cert`](https://dogtagpki.github.io/jss/javadoc/org/mozilla/jss/pkcs11/PK11Cert.html)s instead of encoding and decoding into a [`java.security.cert.X509Certificate`](https://docs.oracle.com/javase/8/docs/api/java/security/cert/X509Certificate.html). 

Update provider to expose PK11Certs - 5:2

---

org/mozilla/jss/asn1/ASN1Header.java
org/mozilla/jss/asn1/OBJECT_IDENTIFIER.java
org/mozilla/jss/asn1/SET.java
org/mozilla/jss/ssl/SSLClient.java
org/mozilla/jss/ssl/SSLTest.java
org/mozilla/jss/ssl/SSLVersionRange.java
org/mozilla/jss/tests/JSSE_SSLClient.java
org/mozilla/jss/tests/JSS_SelfServServer.java
org/mozilla/jss/util/NativeProxy.java

The scope is this patch is very narrow.

Fix some trivial deprecation warnings #33

---

org/mozilla/jss/util/Password.java

The Password class has been modified to store the location where
it was created initially. If the Password object is garbage
collected without being cleared first, it will display a warning
message showing the location of the offending code.
For example:
```
$ pki pkcs12-cert-find --pkcs12-file output.p12 --pkcs12-password-file password.txt
WARNING: Uncleared Password object
at org.mozilla.jss.crypto.PBEKeyGenParams.<init>(PBEKeyGenParams.java:37)
at org.mozilla.jss.pkcs12.MacData.<init>(MacData.java:118)
at org.mozilla.jss.pkcs12.PFX.verifyAuthSafes(PFX.java:156)
at org.mozilla.jss.netscape.security.pkcs.PKCS12Util.loadFromByteArray(PKCS12Util.java:835)
at org.mozilla.jss.netscape.security.pkcs.PKCS12Util.loadFromFile(PKCS12Util.java:824)
at …
```

Added uncleared password warning

---

org/mozilla/jss/pkcs12/MacData.java

The MacData has been modified to call PBEKeyGenParams.clear()
in a finally block to ensure that the password is cleared.

 Fixing uncleared password in MacData

---

cmake/JSSConfig.cmake
docs/build_system.md

- Documents existing and newly-added options.
- Documents how to add a test case.

CMake: Documentation Updates

---

tools/Dockerfiles/fedora_sandbox

Add python-unversioned-command to fedora_sandbox

---

org/mozilla/jss/ssl/common.c

When the Leaf and Chain OCSP checking policy is enabled in
CryptoManager, JSS will switch to alternative certificate verification
logic in `JSSL_DefaultCertAuthCallback`. In this method, the root
certificate was incorrectly trusted without being verified to exist in
the trust store.
This patch cleans up the logic in `JSSL_verifyCertPKIX` and makes it
more explicit in addition to fixing the error.
Fixes: [CVE-2019-14823](https://nvd.nist.gov/vuln/detail/CVE-2019-14823)

CVE-2019-14823: Fix root certificate validation

---

cmake/JSSConfig.cmake
org/mozilla/jss/ssl/common.c
org/mozilla/jss/tests/BadSSL.java
tools/common_roots.sh
tools/run_test.sh.in

See also: #284 and #285. After this, I'll cut a new v4.5.x release.

Backport CVE-2019-14823 to v4.5.x

---

org/mozilla/jss/tests/BadSSL.java
tools/common_roots.sh

BadSSL test case for v4.4.x

---

org/mozilla/jss/ssl/common.c

Backport CVE-2019-14823 to v4.4.x

---

org/mozilla/jss/pkcs11/PKCS11Constants.java

Minor update in prep for KBKDF updates.

Update PKCS#11 files based on NSS 3.47

---

org/mozilla/jss/crypto/SymmetricKey.java
org/mozilla/jss/pkcs11/KeyType.java

Add CMAC, SHA2/HMAC to PKCS#11 KeyTypes

---

org/mozilla/jss/nss/SecurityStatusResult.java
org/mozilla/jss/tests/TestRawSSL.java

This aids logging in the JSSEngine.

Add toString to SecurityStatusResult

---

org/mozilla/jss/nss/SSL.c

Clear NSPR Errors prior to SSL calls

---

lib/jss.map
org/mozilla/jss/nss/PRErrors.c
org/mozilla/jss/nss/PRErrors.java

Add SOCKET_SHUTDOWN_ERROR to PRErrors

---

org/mozilla/jss/provider/javax/crypto/JSSTrustManager.java

@edewata I'm using this in the test suite of #150 currently. This is because the JSS test suite doesn't currently add extended key usage to certificates it generates. I'm going to see how hard it is to added them first, before I accept this route.

Configure extendedKeyUsage in JSSTrustManager

---

org/mozilla/jss/nss/PR.c

When using SSL on certain systems, NSS will indicate it only has a
single byte of data to read, when in fact it has more data than that.
This is due to a bug in the TLS record parsing logic, forcing the caller
to issue another `PR_Read` call.
This hangs up our SSLEngine implementation. Bypass this bug by detecting
if the underlying socket is non-blocking, and if so, call `PR_Read` until
we get a `PR_WOULD_BLOCK_ERROR`.

Workaround NSS PR_Read bug

---

tools/Dockerfiles/pkcs11check

Add diff to pkcs11check installation list

---

jss.spec

Add zip, unzip to BuildRequires

---

cmake/JSSConfig.cmake
org/mozilla/jss/ssl/SSLAlertDescription.java
tools/Dockerfiles/fedora_rawhide

Add unchecked exceptions to debug build tests

---

org/mozilla/jss/pkcs11/PK11Signature.c
org/mozilla/jss/pkcs11/pk11util.h
org/mozilla/jss/provider/java/security/RSAPSSAlgorithmParameters.java

This fixes:
- The uninitialized variable warning I thought was a false positive when merging the original patch,
- Freeing of Arena, shadowing of public key pointer. 
- DERs with Trailer parameter.

PSS - Assorted Fixes

---

cmake/JSSConfig.cmake
docs/dependencies.md
docs/nss.md
jss.spec
org/mozilla/jss/pkcs11/PK11PrivKey.c

Document known NSS incompatibilities

---

.github/workflows/optional.yml
.github/workflows/required.yml

Enable GitHub Actions on v4.6.x

---

lib/jss.map
org/mozilla/jss/nss/PR.c
org/mozilla/jss/nss/PR.java
org/mozilla/jss/nss/PRFDProxy.java
org/mozilla/jss/nss/SSL.c
org/mozilla/jss/nss/SSL.java
org/mozilla/jss/nss/SSLFDProxy.c
org/mozilla/jss/nss/SSLFDProxy.h
org/mozilla/jss/nss/SSLFDProxy.java
org/mozilla/jss/pkcs11/PK11Cert.c
org/mozilla/jss/pkcs11/PK11Module.c
org/mozilla/jss/pkcs11/PK11PrivKey.c
org/mozilla/jss/pkcs11/PK11Signature.c
org/mozilla/jss/pkcs11/PK11SymKey.c
org/mozilla/jss/pkcs11/PK11Token.c
org/mozilla/jss/ssl/SocketBase.java
org/mozilla/jss/ssl/common.c
org/mozilla/jss/util/GlobalRefProxy.c
org/mozilla/jss/util/GlobalRefProxy.java
org/mozilla/jss/util/NativeProxy.java

This is a backport of #473, picking and choosing as necessary.

Backport Memory Fixes to v4.6.x

---

.github/workflows/optional.yml
.github/workflows/required.yml

Use matrix strategy to avoid redundant code. Easier to read and maintain CI code.
I wasn't sure if "test" was the right job name. But, let me know if you come up with a better name :wink: 
`Signed-off-by: Dinesh Prasanth M K <dmoluguw@redhat.com>`

Minor improvement to GH actions

---

org/mozilla/jss/netscape/security/x509/AlgorithmId.java

Fix SHA512withRSA/PSS identifier

---

org/mozilla/jss/ssl/javax/JSSEngineReferenceImpl.java

When the read end of the logging socket is full, writing also tends to
hang. Drain the read end of both sockets before attempting any writes
to help ensure nothing hangs.

Consume all input bytes in logging sockets

---

tools/run_test.sh.in

---
Helps with manual testing when something breaks. :-)

Enable debug logging with run_test.sh

---

.github/workflows/optional.yml
.github/workflows/required.yml

Always run workflows regardless of branch

---

org/mozilla/jss/crypto/SignatureAlgorithm.java
org/mozilla/jss/netscape/security/x509/AlgorithmId.java

Various typos resolved  to result  in this algorithm being able to function correctly.

More SHA256withRSA/PSS algorithm fixes. 

---

org/mozilla/jss/crypto/SignatureAlgorithm.java
org/mozilla/jss/netscape/security/x509/AlgorithmId.java

---
Forward port of #541 for master branch.

Fix RSA/PSS with SHA-512 signature algorithm

---

org/mozilla/jss/ssl/javax/JSSSocketChannel.java

An important part of the TLS protocol is the ability to detect whether
or not the peer closed the connection or if an attacker terminated the
connection prematurely. In order to do this, both sides send a
`CLOSE_NOTIFY` event. When this event isn't detected, raise an `IOException`
to inform the application about it.

SSLSocket: detect failure to recieve CLOSE_NOTIFY

---

org/mozilla/jss/JSSProvider.java

Enable JSS-Provided SSLEngine

---

org/mozilla/jss/netscape/security/util/Cert.java

Add PSS cases to algorithm name translating method.

Related: Bug 1710105 - JSS: add RSA PSS support

---

org/mozilla/jss/tests/BenchmarkSSLSocket.java

Add concurrency limit on BenchmarkSSLSocket

---

org/mozilla/jss/ssl/javax/JSSEngineReferenceImpl.java

Close outbound when inbound side is closed

---

org/mozilla/jss/tests/TestSSLEngine.java

Adds a couple of tests from the JDK test suite to our SSLEngine tests.

Add jdk tests

---

org/mozilla/jss/pkcs11/PKCS11Constants.java

Update PKCS#11 Constants off of NSS v3.54

---

.github/workflows/required.yml
tools/Dockerfiles/fedora_27
tools/Dockerfiles/fedora_28
tools/Dockerfiles/fedora_29
tools/Dockerfiles/fedora_29_jdk11
tools/Dockerfiles/fedora_30
tools/Dockerfiles/fedora_31
tools/Dockerfiles/fedora_32
tools/Dockerfiles/fedora_33
tools/Dockerfiles/fedora_latest_jdk11
tools/Dockerfiles/fedora_rawhide
tools/Dockerfiles/fedora_sandbox
tools/Dockerfiles/pkcs11check
tools/Dockerfiles/pki_build
tools/Dockerfiles/stylecheck
tools/Dockerfiles/symbolcheck
tools/run_container.sh

Add Fedora 33 to CI

---

lib/jss.map
org/mozilla/jss/nss/BadCertHandler.java
org/mozilla/jss/nss/SSL.c
org/mozilla/jss/nss/SSL.java
org/mozilla/jss/nss/SSLErrors.c
org/mozilla/jss/nss/SSLErrors.java
org/mozilla/jss/nss/SSLFDProxy.c
org/mozilla/jss/nss/SSLFDProxy.h
org/mozilla/jss/nss/SSLFDProxy.java
org/mozilla/jss/ssl/javax/JSSEngineReferenceImpl.java

A backport of #625. See description there.

Backport fix hostname verification

---

org/mozilla/jss/ssl/SSLSocket.java
org/mozilla/jss/ssl/SocketBase.java
org/mozilla/jss/ssl/common.c
org/mozilla/jss/ssl/javax/JSSEngine.java
org/mozilla/jss/ssl/jssl.h

Disable FALLBACK_SCSV and enable PHA

---

lib/jss.map
org/mozilla/jss/nss/SSLErrors.c

Fix JNI function misname

---

docs/usage/cryptomanager.md
org/mozilla/jss/CryptoManager.java
org/mozilla/jss/JSSLoader.java

Per IRC discussions, likely an interesting read. :-) LMK if you still have questions or have suggestions for updates or more material.

Add documentation about CryptoManager/JSSProvider

---

cmake/JSSConfig.cmake
jss.spec

Release JSS v4.7.3

---

cmake/JSSConfig.cmake
jss.spec
org/mozilla/jss/netscape/security/pkcs/PKCS12Util.java
org/mozilla/jss/netscape/security/util/Cert.java
org/mozilla/jss/netscape/security/x509/RevocationReasonAdapter.java
org/mozilla/jss/provider/java/security/JSSKeyStoreSpi.java
org/mozilla/jss/tests/UTF8ConverterTest.java
tools/Dockerfiles/debian_jdk11
tools/Dockerfiles/fedora_29_jdk11
tools/Dockerfiles/fedora_latest_jdk11
tools/Dockerfiles/fedora_rawhide
tools/Dockerfiles/fedora_sandbox
tools/Dockerfiles/ubuntu_jdk8

Credits: Fabio "decathorpe" Valentini
Resolves: #621

Port from Apache Commons Lang 2 -> 3

---

cmake/JSSConfig.cmake
jss.spec

Bump JSS version to v4.8.0 alpha 1

---

README.md

Resolves: #645 reported by @cosarara
---
Technically this also applies to `v4.7.x` branch but I'm unlikely to backport.

Update minimum NSS version in README

---

README.md

Add distribution packages to README

---

org/mozilla/jss/pkcs11/PK11RSAPrivateKey.java
org/mozilla/jss/pkcs11/PK11Store.java
org/mozilla/jss/provider/javax/crypto/JSSMacSpi.java

Backport of Attempt to use SecretKeyFactory to rewrite keys prior to failing JSSMacSpi

---

org/mozilla/jss/pkcs11/PK11KeyWrapper.c

NSS doesn't generally allow keys to be imported in FIPS mode. However,
for portability with other JCA providers, we sometimes need to import
keys from byte arrays. Do this in the JNI layer by executing a PKCS#11
encrypt and then unwrap using the same key. This lets us effectively
"import" a key into a token, if the token supports using the given
mechanism for both encryption and unwrapping operations. Some HSMs are
getting stricter about this and forbid using the same key for encrypt
and unwrap operations.
Resolves: #334

Encrypt & unwrap symmetric key in FIPS mode

---

src/test/java/org/mozilla/jss/tests/ClassServer.java
src/test/java/org/mozilla/jss/tests/GenerateTestCert.java
src/test/java/org/mozilla/jss/tests/JSSE_SSLClient.java
src/test/java/org/mozilla/jss/tests/JSS_FileUploadClient.java
src/test/java/org/mozilla/jss/tests/JSS_SelfServClient.java
src/test/java/org/mozilla/jss/tests/JSS_SelfServServer.java
src/test/java/org/mozilla/jss/tests/SSLClientAuth.java

Replace deprecated Integer constructors

---

src/main/java/org/mozilla/jss/pkix/cms/ContentInfo.java
src/main/java/org/mozilla/jss/pkix/cms/DigestInfo.java
src/main/java/org/mozilla/jss/pkix/cms/DigestedData.java
src/main/java/org/mozilla/jss/pkix/cms/EncapsulatedContentInfo.java
src/main/java/org/mozilla/jss/pkix/cms/EncryptedContentInfo.java
src/main/java/org/mozilla/jss/pkix/cms/EncryptedData.java
src/main/java/org/mozilla/jss/pkix/cms/EnvelopedData.java
src/main/java/org/mozilla/jss/pkix/cms/IssuerAndSerialNumber.java
src/main/java/org/mozilla/jss/pkix/cms/RecipientInfo.java
src/main/java/org/mozilla/jss/pkix/cms/SignedAndEnvelopedData.java
src/main/java/org/mozilla/jss/pkix/cms/SignedData.java
src/main/java/org/mozilla/jss/pkix/cms/SignerIdentifier.java
src/main/java/org/mozilla/jss/pkix/cms/SignerInfo.java

Add missing annotations to org.mozilla.jss.pkix.cms

---

src/main/java/org/mozilla/jss/provider/javax/net/JSSContextSpi.java

Add missing annotations in org.mozilla.jss.provider.javax.net

---

src/main/java/org/mozilla/jss/provider/java/security/IvAlgorithmParameters.java
src/main/java/org/mozilla/jss/provider/java/security/JSSKeyPairGeneratorSpi.java
src/main/java/org/mozilla/jss/provider/java/security/JSSKeyStoreSpi.java
src/main/java/org/mozilla/jss/provider/java/security/JSSMessageDigestSpi.java
src/main/java/org/mozilla/jss/provider/java/security/JSSSecureRandomSpi.java
src/main/java/org/mozilla/jss/provider/java/security/JSSSignatureSpi.java
src/main/java/org/mozilla/jss/provider/java/security/KeyFactorySpi1_2.java
src/main/java/org/mozilla/jss/provider/java/security/RC2AlgorithmParameters.java

Add missing annotations to org.mozilla.jss.provider.java.security

---

src/main/java/org/mozilla/jss/pkix/primitive/AVA.java
src/main/java/org/mozilla/jss/pkix/primitive/AlgorithmIdentifier.java
src/main/java/org/mozilla/jss/pkix/primitive/Attribute.java
src/main/java/org/mozilla/jss/pkix/primitive/DirectoryString.java
src/main/java/org/mozilla/jss/pkix/primitive/EncryptedPrivateKeyInfo.java
src/main/java/org/mozilla/jss/pkix/primitive/Name.java
src/main/java/org/mozilla/jss/pkix/primitive/PBEParameter.java
src/main/java/org/mozilla/jss/pkix/primitive/PrivateKeyInfo.java
src/main/java/org/mozilla/jss/pkix/primitive/RDN.java
src/main/java/org/mozilla/jss/pkix/primitive/SubjectPublicKeyInfo.java

Add missing annotations to org.mozilla.jss.pkix.primitive

---

src/main/java/org/mozilla/jss/provider/javax/crypto/JSSCipherSpi.java
src/main/java/org/mozilla/jss/provider/javax/crypto/JSSKeyGeneratorSpi.java
src/main/java/org/mozilla/jss/provider/javax/crypto/JSSKeyManagerFactory.java
src/main/java/org/mozilla/jss/provider/javax/crypto/JSSMacSpi.java
src/main/java/org/mozilla/jss/provider/javax/crypto/JSSSecretKeyFactorySpi.java
src/main/java/org/mozilla/jss/provider/javax/crypto/JSSTokenKeyManager.java
src/main/java/org/mozilla/jss/provider/javax/crypto/JSSTrustManagerFactory.java

Add missing annotations to org.mozilla.jss.provider.javax.crypto

---

src/main/java/org/mozilla/jss/netscape/security/util/ASN1CharsetProvider.java
src/main/java/org/mozilla/jss/netscape/security/util/BigInt.java
src/main/java/org/mozilla/jss/netscape/security/util/BitArray.java
src/main/java/org/mozilla/jss/netscape/security/util/ByteArrayLexOrder.java
src/main/java/org/mozilla/jss/netscape/security/util/ByteArrayTagOrder.java
src/main/java/org/mozilla/jss/netscape/security/util/DerInputBuffer.java
src/main/java/org/mozilla/jss/netscape/security/util/DerOutputStream.java
src/main/java/org/mozilla/jss/netscape/security/util/DerValue.java
src/main/java/org/mozilla/jss/netscape/security/util/ExtPrettyPrint.java
src/main/java/org/mozilla/jss/netscape/security/util/IA5Charset.java
src/main/java/org/mozilla/jss/netscape/security/util/IA5CharsetDecoder.java
src/main/java/org/mozilla/jss/netscape/security/util/IA5CharsetEncoder.java
src/main/java/org/mozilla/jss/netscape/security/util/ObjectIdentifier.java
src/main/java/org/mozilla/jss/netscape/security/util/PrettyPrintResources.java
src/main/java/org/mozilla/jss/netscape/security/util/PrintableCharset.java
src/main/java/org/mozilla/jss/netscape/security/util/PrintableCharsetDecoder.java
src/main/java/org/mozilla/jss/netscape/security/util/PrintableCharsetEncoder.java
src/main/java/org/mozilla/jss/netscape/security/util/UniversalCharset.java
src/main/java/org/mozilla/jss/netscape/security/util/UniversalCharsetDecoder.java
src/main/java/org/mozilla/jss/netscape/security/util/UniversalCharsetEncoder.java

Add missing annotations for org.mozilla.jss.netscape.security.util

---

src/main/java/org/mozilla/jss/SecretDecoderRing/Encoding.java

Add missing annotations in org.mozilla.jss.SecretDecoderRing

---

src/main/java/org/mozilla/jss/pkix/cmmf/CertOrEncCert.java
src/main/java/org/mozilla/jss/pkix/cmmf/CertRepContent.java
src/main/java/org/mozilla/jss/pkix/cmmf/CertResponse.java
src/main/java/org/mozilla/jss/pkix/cmmf/CertifiedKeyPair.java
src/main/java/org/mozilla/jss/pkix/cmmf/GetCRL.java
src/main/java/org/mozilla/jss/pkix/cmmf/IssuerAndSubject.java
src/main/java/org/mozilla/jss/pkix/cmmf/PKIStatusInfo.java
src/main/java/org/mozilla/jss/pkix/cmmf/RevRepContent.java
src/main/java/org/mozilla/jss/pkix/cmmf/RevRequest.java

Add missing annotations to org.mozilla.jss.pkix.cmmf

---

src/main/java/org/mozilla/jss/netscape/security/pkcs/ContentInfo.java
src/main/java/org/mozilla/jss/netscape/security/pkcs/PKCS10.java
src/main/java/org/mozilla/jss/netscape/security/pkcs/PKCS10Attribute.java
src/main/java/org/mozilla/jss/netscape/security/pkcs/PKCS10Attributes.java
src/main/java/org/mozilla/jss/netscape/security/pkcs/PKCS7.java
src/main/java/org/mozilla/jss/netscape/security/pkcs/PKCS8Key.java
src/main/java/org/mozilla/jss/netscape/security/pkcs/PKCS9Attribute.java
src/main/java/org/mozilla/jss/netscape/security/pkcs/PKCS9Attributes.java
src/main/java/org/mozilla/jss/netscape/security/pkcs/SignerInfo.java

Add missing annotations to org.mozilla.jss.netscape.security.pkcs

---

src/main/java/org/mozilla/jss/netscape/security/provider/CMS.java
src/main/java/org/mozilla/jss/netscape/security/provider/DSAKeyFactory.java
src/main/java/org/mozilla/jss/netscape/security/provider/DSAParameters.java
src/main/java/org/mozilla/jss/netscape/security/provider/DSAPrivateKey.java
src/main/java/org/mozilla/jss/netscape/security/provider/DSAPublicKey.java
src/main/java/org/mozilla/jss/netscape/security/provider/RSAPublicKey.java
src/main/java/org/mozilla/jss/netscape/security/provider/X509CertificateFactory.java

Add missing annotations to org.mozilla.jss.netscape.security.provider

---

src/main/java/org/mozilla/jss/pkcs7/Attribute.java
src/main/java/org/mozilla/jss/pkcs7/ContentInfo.java
src/main/java/org/mozilla/jss/pkcs7/DigestInfo.java
src/main/java/org/mozilla/jss/pkcs7/DigestedData.java
src/main/java/org/mozilla/jss/pkcs7/EncryptedContentInfo.java
src/main/java/org/mozilla/jss/pkcs7/EncryptedData.java
src/main/java/org/mozilla/jss/pkcs7/EnvelopedData.java
src/main/java/org/mozilla/jss/pkcs7/IssuerAndSerialNumber.java
src/main/java/org/mozilla/jss/pkcs7/RecipientInfo.java
src/main/java/org/mozilla/jss/pkcs7/SignedAndEnvelopedData.java
src/main/java/org/mozilla/jss/pkcs7/SignedData.java
src/main/java/org/mozilla/jss/pkcs7/SignerInfo.java

Add missing annotations to org.mozilla.jss.pkcs7

---

src/main/java/org/mozilla/jss/pkix/cmc/BodyPartReference.java
src/main/java/org/mozilla/jss/pkix/cmc/CMCCertId.java
src/main/java/org/mozilla/jss/pkix/cmc/CMCStatusInfo.java
src/main/java/org/mozilla/jss/pkix/cmc/CMCStatusInfoV2.java
src/main/java/org/mozilla/jss/pkix/cmc/DecryptedPOP.java
src/main/java/org/mozilla/jss/pkix/cmc/EncryptedPOP.java
src/main/java/org/mozilla/jss/pkix/cmc/ExtendedFailInfo.java
src/main/java/org/mozilla/jss/pkix/cmc/GetCert.java
src/main/java/org/mozilla/jss/pkix/cmc/IdentityProofV2.java
src/main/java/org/mozilla/jss/pkix/cmc/LraPopWitness.java
src/main/java/org/mozilla/jss/pkix/cmc/OtherInfo.java
src/main/java/org/mozilla/jss/pkix/cmc/OtherMsg.java
src/main/java/org/mozilla/jss/pkix/cmc/OtherReqMsg.java
src/main/java/org/mozilla/jss/pkix/cmc/PKIData.java
src/main/java/org/mozilla/jss/pkix/cmc/PendInfo.java
src/main/java/org/mozilla/jss/pkix/cmc/PopLinkWitnessV2.java
src/main/java/org/mozilla/jss/pkix/cmc/ResponseBody.java
src/main/java/org/mozilla/jss/pkix/cmc/RevokeRequest.java
src/main/java/org/mozilla/jss/pkix/cmc/TaggedAttribute.java
src/main/java/org/mozilla/jss/pkix/cmc/TaggedCertificationRequest.java
src/main/java/org/mozilla/jss/pkix/cmc/TaggedContentInfo.java
src/main/java/org/mozilla/jss/pkix/cmc/TaggedRequest.java

Add missing annotations to org.mozilla.jss.pkix.cmc

---

src/main/java/org/mozilla/jss/pkcs12/AuthenticatedSafes.java
src/main/java/org/mozilla/jss/pkcs12/CertBag.java
src/main/java/org/mozilla/jss/pkcs12/MacData.java
src/main/java/org/mozilla/jss/pkcs12/PFX.java
src/main/java/org/mozilla/jss/pkcs12/PasswordConverter.java
src/main/java/org/mozilla/jss/pkcs12/SafeBag.java
src/main/java/org/mozilla/jss/pkcs12/SecretBag.java

Add missing annotations to org.mozilla.jss.pkcs12

---

src/main/java/org/mozilla/jss/netscape/security/extensions/AuthInfoAccessExtension.java
src/main/java/org/mozilla/jss/netscape/security/extensions/CertificateRenewalWindowExtension.java
src/main/java/org/mozilla/jss/netscape/security/extensions/CertificateScopeEntry.java
src/main/java/org/mozilla/jss/netscape/security/extensions/CertificateScopeOfUseExtension.java
src/main/java/org/mozilla/jss/netscape/security/extensions/ExtendedKeyUsageExtension.java
src/main/java/org/mozilla/jss/netscape/security/extensions/GenericASN1Extension.java
src/main/java/org/mozilla/jss/netscape/security/extensions/InhibitAnyPolicyExtension.java
src/main/java/org/mozilla/jss/netscape/security/extensions/KerberosName.java
src/main/java/org/mozilla/jss/netscape/security/extensions/NSCertTypeExtension.java
src/main/java/org/mozilla/jss/netscape/security/extensions/OCSPNoCheckExtension.java
src/main/java/org/mozilla/jss/netscape/security/extensions/PresenceServerExtension.java
src/main/java/org/mozilla/jss/netscape/security/extensions/SubjectInfoAccessExtension.java

Add missing annotations to org.mozilla.jss.netscape.security.extensions

---

src/main/java/org/mozilla/jss/pkcs11/attrs/CKAClass.java
src/main/java/org/mozilla/jss/pkcs11/attrs/CKAKeyType.java
src/main/java/org/mozilla/jss/pkcs11/attrs/CKAUsage.java
src/main/java/org/mozilla/jss/pkcs11/attrs/CKAValueLen.java

Add missing annotations in org.mozilla.jss.pkcs11.attrs

---

src/main/java/org/mozilla/jss/pkcs10/CertificationRequest.java
src/main/java/org/mozilla/jss/pkcs10/CertificationRequestInfo.java

Add missing annotations in org.mozilla.jss.pkcs10

---

src/main/java/org/mozilla/jss/pkix/cert/Certificate.java
src/main/java/org/mozilla/jss/pkix/cert/CertificateInfo.java
src/main/java/org/mozilla/jss/pkix/cert/Extension.java
src/main/java/org/mozilla/jss/pkix/cert/SubjectKeyIdentifier.java

Add missing annotations to org.mozilla.jss.pkix.cert

---

src/main/java/org/mozilla/jss/asn1/ANY.java
src/main/java/org/mozilla/jss/asn1/BIT_STRING.java
src/main/java/org/mozilla/jss/asn1/BMPString.java
src/main/java/org/mozilla/jss/asn1/BOOLEAN.java
src/main/java/org/mozilla/jss/asn1/CHOICE.java
src/main/java/org/mozilla/jss/asn1/CharacterString.java
src/main/java/org/mozilla/jss/asn1/CountingStream.java
src/main/java/org/mozilla/jss/asn1/ENUMERATED.java
src/main/java/org/mozilla/jss/asn1/EXPLICIT.java
src/main/java/org/mozilla/jss/asn1/Form.java
src/main/java/org/mozilla/jss/asn1/GeneralizedTime.java
src/main/java/org/mozilla/jss/asn1/IA5String.java
src/main/java/org/mozilla/jss/asn1/INTEGER.java
src/main/java/org/mozilla/jss/asn1/InvalidBERException.java
src/main/java/org/mozilla/jss/asn1/NULL.java
src/main/java/org/mozilla/jss/asn1/OBJECT_IDENTIFIER.java
src/main/java/org/mozilla/jss/asn1/OCTET_STRING.java
src/main/java/org/mozilla/jss/asn1/PrintableString.java
src/main/java/org/mozilla/jss/asn1/SEQUENCE.java
src/main/java/org/mozilla/jss/asn1/SET.java
src/main/java/org/mozilla/jss/asn1/Tag.java
src/main/java/org/mozilla/jss/asn1/TeletexString.java
src/main/java/org/mozilla/jss/asn1/TimeBase.java
src/main/java/org/mozilla/jss/asn1/UTCTime.java
src/main/java/org/mozilla/jss/asn1/UTF8String.java
src/main/java/org/mozilla/jss/asn1/UniversalString.java

Add missing annotations to org.mozilla.jss.asn1

---

src/main/java/org/mozilla/jss/nss/BadCertHandler.java
src/main/java/org/mozilla/jss/nss/BufferProxy.java
src/main/java/org/mozilla/jss/nss/CertAuthHandler.java
src/main/java/org/mozilla/jss/nss/PRFDProxy.java
src/main/java/org/mozilla/jss/nss/SSLChannelInfo.java
src/main/java/org/mozilla/jss/nss/SSLPreliminaryChannelInfo.java
src/main/java/org/mozilla/jss/nss/SecurityStatusResult.java

Add missing annotations to org.mozilla.jss.nss

---

src/main/java/org/mozilla/jss/crypto/Algorithm.java
src/main/java/org/mozilla/jss/crypto/CryptoToken.java
src/main/java/org/mozilla/jss/crypto/EncryptionAlgorithm.java
src/main/java/org/mozilla/jss/crypto/JSSOAEPParameterSpec.java
src/main/java/org/mozilla/jss/crypto/KBKDFByteArrayParam.java
src/main/java/org/mozilla/jss/crypto/KBKDFCounterParams.java
src/main/java/org/mozilla/jss/crypto/KBKDFDKMLengthParam.java
src/main/java/org/mozilla/jss/crypto/KBKDFDerivedKey.java
src/main/java/org/mozilla/jss/crypto/KBKDFFeedbackParams.java
src/main/java/org/mozilla/jss/crypto/KBKDFIterationVariableParam.java
src/main/java/org/mozilla/jss/crypto/KBKDFOptionalCounterParam.java
src/main/java/org/mozilla/jss/crypto/KBKDFParameterSpec.java
src/main/java/org/mozilla/jss/crypto/KBKDFPipelineParams.java
src/main/java/org/mozilla/jss/crypto/KeyGenAlgorithm.java
src/main/java/org/mozilla/jss/crypto/PBEKeyGenParams.java
src/main/java/org/mozilla/jss/crypto/PrivateKey.java
src/main/java/org/mozilla/jss/crypto/SecretKeyFacade.java
src/main/java/org/mozilla/jss/crypto/Signature.java
src/main/java/org/mozilla/jss/crypto/SymmetricKey.java

Add missing annotations to org.mozilla.jss.crypto

---

src/main/java/org/mozilla/jss/ssl/SSLAlertEvent.java
src/main/java/org/mozilla/jss/ssl/SSLClient.java
src/main/java/org/mozilla/jss/ssl/SSLInputStream.java
src/main/java/org/mozilla/jss/ssl/SSLOutputStream.java
src/main/java/org/mozilla/jss/ssl/SSLSecurityStatus.java
src/main/java/org/mozilla/jss/ssl/SSLServer.java
src/main/java/org/mozilla/jss/ssl/SSLServerSocket.java
src/main/java/org/mozilla/jss/ssl/SSLSocket.java
src/main/java/org/mozilla/jss/ssl/SocketProxy.java
src/main/java/org/mozilla/jss/ssl/TestCertApprovalCallback.java
src/main/java/org/mozilla/jss/ssl/TestClientCertificateSelectionCallback.java

Add missing annotations in org.mozilla.jss.ssl

---

src/main/java/org/mozilla/jss/util/Base64InputStream.java
src/main/java/org/mozilla/jss/util/Base64OutputStream.java
src/main/java/org/mozilla/jss/util/ConsolePasswordCallback.java
src/main/java/org/mozilla/jss/util/GlobalRefProxy.java
src/main/java/org/mozilla/jss/util/NativeEnclosure.java
src/main/java/org/mozilla/jss/util/NativeErrcodes.java
src/main/java/org/mozilla/jss/util/NativeProxy.java
src/main/java/org/mozilla/jss/util/NullPasswordCallback.java
src/main/java/org/mozilla/jss/util/Password.java
src/main/java/org/mozilla/jss/util/StaticVoidPointer.java

Add missing annotations to org.mozilla.jss.util

---

src/main/java/org/mozilla/jss/CertificateUsage.java
src/main/java/org/mozilla/jss/CryptoManager.java
src/main/java/org/mozilla/jss/JSSProvider.java

Add missing annotations in org.mozilla.jss

---

src/main/java/org/mozilla/jss/ssl/javax/JSSEngine.java
src/main/java/org/mozilla/jss/ssl/javax/JSSEngineReferenceImpl.java
src/main/java/org/mozilla/jss/ssl/javax/JSSParameters.java
src/main/java/org/mozilla/jss/ssl/javax/JSSServerSocket.java
src/main/java/org/mozilla/jss/ssl/javax/JSSServerSocketChannel.java
src/main/java/org/mozilla/jss/ssl/javax/JSSServerSocketFactory.java
src/main/java/org/mozilla/jss/ssl/javax/JSSSession.java
src/main/java/org/mozilla/jss/ssl/javax/JSSSocket.java
src/main/java/org/mozilla/jss/ssl/javax/JSSSocketChannel.java
src/main/java/org/mozilla/jss/ssl/javax/JSSSocketFactory.java

Add missing annotations to org.mozilla.jss.ssl.javax

---

src/main/java/org/mozilla/jss/pkcs11/CipherContextProxy.java
src/main/java/org/mozilla/jss/pkcs11/KeyProxy.java
src/main/java/org/mozilla/jss/pkcs11/KeyType.java
src/main/java/org/mozilla/jss/pkcs11/ModuleProxy.java
src/main/java/org/mozilla/jss/pkcs11/PK11Cert.java
src/main/java/org/mozilla/jss/pkcs11/PK11Cipher.java
src/main/java/org/mozilla/jss/pkcs11/PK11DSAPrivateKey.java
src/main/java/org/mozilla/jss/pkcs11/PK11DSAPublicKey.java
src/main/java/org/mozilla/jss/pkcs11/PK11ECPrivateKey.java
src/main/java/org/mozilla/jss/pkcs11/PK11ECPublicKey.java
src/main/java/org/mozilla/jss/pkcs11/PK11InternalCert.java
src/main/java/org/mozilla/jss/pkcs11/PK11InternalTokenCert.java
src/main/java/org/mozilla/jss/pkcs11/PK11Key.java
src/main/java/org/mozilla/jss/pkcs11/PK11KeyGenerator.java
src/main/java/org/mozilla/jss/pkcs11/PK11KeyPairGenerator.java
src/main/java/org/mozilla/jss/pkcs11/PK11KeyWrapper.java
src/main/java/org/mozilla/jss/pkcs11/PK11MessageDigest.java
src/main/java/org/mozilla/jss/pkcs11/PK11PrivKey.java
src/main/java/org/mozilla/jss/pkcs11/PK11PubKey.java
src/main/java/org/mozilla/jss/pkcs11/PK11RSAPrivateKey.java
src/main/java/org/mozilla/jss/pkcs11/PK11RSAPublicKey.java
src/main/java/org/mozilla/jss/pkcs11/PK11SecureRandom.java
src/main/java/org/mozilla/jss/pkcs11/PK11Signature.java
src/main/java/org/mozilla/jss/pkcs11/PK11Store.java
src/main/java/org/mozilla/jss/pkcs11/PK11SymKey.java
src/main/java/org/mozilla/jss/pkcs11/PK11SymmetricKeyDeriver.java
src/main/java/org/mozilla/jss/pkcs11/PK11Token.java
src/main/java/org/mozilla/jss/pkcs11/PK11TokenCert.java
src/main/java/org/mozilla/jss/pkcs11/TokenProxy.java

Add missing annotations in org.mozilla.jss.pkcs11

---

src/main/java/org/mozilla/jss/asn1/BMPString.java
src/main/java/org/mozilla/jss/asn1/ENUMERATED.java
src/main/java/org/mozilla/jss/asn1/GeneralizedTime.java
src/main/java/org/mozilla/jss/asn1/IA5String.java
src/main/java/org/mozilla/jss/asn1/PrintableString.java
src/main/java/org/mozilla/jss/asn1/SEQUENCE.java
src/main/java/org/mozilla/jss/asn1/TeletexString.java
src/main/java/org/mozilla/jss/asn1/UTCTime.java
src/main/java/org/mozilla/jss/asn1/UTF8String.java
src/main/java/org/mozilla/jss/asn1/UniversalString.java
src/main/java/org/mozilla/jss/netscape/security/provider/DSAPrivateKey.java
src/main/java/org/mozilla/jss/netscape/security/provider/DSAPublicKey.java
src/main/java/org/mozilla/jss/netscape/security/provider/RSAPublicKey.java
src/main/java/org/mozilla/jss/netscape/security/x509/CertificateExtensions.java
src/main/java/org/mozilla/jss/netscape/security/x509/X509CertImpl.java
src/main/java/org/mozilla/jss/pkix/crmf/Control.java

Does what it says on the tin.
It also happens to be a test for Azure CI pipeline reporting back to Github.

Remove redundant superinterface implementation statements

---

.classpath

Drop org.hamcrest.core from classpath

---

src/main/java/org/mozilla/jss/pkcs11/PK11Signature.java

* `assert` is disabled by default and it is confusing to see it
used for control flow.

Replace use of assert in PK11Signature

---

src/main/java/org/mozilla/jss/asn1/BOOLEAN.java
src/main/java/org/mozilla/jss/netscape/security/util/PrintableCharset.java
src/main/java/org/mozilla/jss/netscape/security/x509/RevokedCertImpl.java

Largely logical tidying I did as a break between watching training videos.

Tidying up of various classes

---

symkey/src/main/java/org/mozilla/jss/symkey/SessionKey.cpp
symkey/src/main/java/org/mozilla/jss/symkey/SymKey.cpp

The `JSS_PK11_wrapSymKey()` in `SessionKey.cpp` has been modified to pass the symmetric key's nickname into `PK11SymKey`'s constructor just like the `JSS_PK11_wrapSymKey()` in `PK11SymKey.c`. Right now these methods belong to different libraries (`libjss.so` and `libjss-symkey.so`), but in the future they should be merged.
The `SessionKey.ListSymmetricKeys()` has been modified to use the internal token by default if the `tokenName` is `NULL`.
This is required by PKI PR [#4053](https://github.com/dogtagpki/pki/pull/4053).

Fix issues in symkey library

---

.github/workflows/code-analysis-pull.yml

The code is updated with the master so if there are other commits before the PR the analysis should not report problem fixed in those commits.

Rebase to master before analyse the pull request

---

.github/workflows/code-analysis.yml
build.sh
tests/bin/tomcat-start-wait.sh

Set severity to only trigger failure on warnings or higher.

Fix shellcheck issues in build.sh and tomcat-start-wait.sh

---

base/src/main/java/org/mozilla/jss/ssl/SSLClient.java
base/src/main/java/org/mozilla/jss/ssl/SSLServer.java

Clean some of the SonarCloud complaints on SSLClient and SSLServer classes.

Tidyup SSLClient and SSLServer

---

base/src/main/java/org/mozilla/jss/netscape/security/x509/X509CertInfo.java

* Simplify equals() with pattern-matching instanceof and removing
unnecessary Boolean literal.
* Combine identical catch clauses
* Use switch expressions and ternary operators where appropriate

Code simplification in X509CertInfo

---

base/src/main/java/org/mozilla/jss/netscape/security/x509/X500Name.java

The class shows 8 bugs on Sonarcloud mainly related to a potential NullPointerException with getString. A check has been added and other few fixes

Tidy up X500Name

---

base/src/main/java/org/mozilla/jss/asn1/ANY.java
base/src/main/java/org/mozilla/jss/asn1/ASN1Header.java
base/src/main/java/org/mozilla/jss/asn1/ASN1Util.java
base/src/main/java/org/mozilla/jss/crypto/Algorithm.java
base/src/main/java/org/mozilla/jss/netscape/security/util/ASN1CharStrConvMap.java
base/src/main/java/org/mozilla/jss/netscape/security/x509/AVA.java
base/src/main/java/org/mozilla/jss/netscape/security/x509/AlgorithmId.java
base/src/main/java/org/mozilla/jss/pkcs12/AuthenticatedSafes.java
base/src/main/java/org/mozilla/jss/pkix/primitive/AlgorithmIdentifier.java
base/src/main/java/org/mozilla/jss/util/Base64InputStream.java

* Where appropriate check-and-cast and ternary operators were used
* Some logic was also simplified by removing Boolean literals

Remove unnecessary else clauses from various classes

---

native/src/main/native/org/mozilla/jss/pkcs11/PK11KeyWrapper.c

Only provision OAEP parameters when non-NULL

---

base/src/main/java/org/mozilla/jss/ssl/SSLTest.java

This solve SonarClpoud critical issue in the SSLTest class.

Move socket creation to try-with-resources

---

.github/workflows/code-analysis-pull.yml

Update github-script action used in SonarCloud.
See https://github.com/actions/github-script

Update github-script action

---

base/src/main/java/org/mozilla/jss/netscape/security/pkcs/ContentInfo.java

According the documentation [1]:
In the case of external signatures, the
content being signed is absent from the EncapsulatedContentInfo value
included
The current implementation always include the content but with length equela to zero. This is modified to be consistent with the specification.
1. https://www.rfc-editor.org/rfc/rfc5652#section-5.2

Fix pkcs7 serialisation when no signatures present

---

base/src/main/java/org/mozilla/jss/JSSProvider.java
base/src/main/java/org/mozilla/jss/crypto/Algorithm.java
base/src/main/java/org/mozilla/jss/crypto/HMACAlgorithm.java
base/src/main/java/org/mozilla/jss/crypto/KeyGenAlgorithm.java
base/src/main/java/org/mozilla/jss/crypto/PBEKeyGenParams.java
base/src/main/java/org/mozilla/jss/pkcs11/PK11KeyGenerator.java
base/src/main/java/org/mozilla/jss/pkcs12/AuthenticatedSafes.java
base/src/main/java/org/mozilla/jss/pkcs12/MacData.java
base/src/main/java/org/mozilla/jss/pkcs12/PFX.java
base/src/main/java/org/mozilla/jss/pkcs7/EncryptedContentInfo.java
base/src/main/java/org/mozilla/jss/pkix/primitive/PBES2Params.java
base/src/main/java/org/mozilla/jss/pkix/primitive/PBKDF2Params.java
base/src/main/java/org/mozilla/jss/provider/javax/crypto/JSSKeyGeneratorSpi.java
native/src/main/native/org/mozilla/jss/crypto/Algorithm.c
native/src/main/native/org/mozilla/jss/crypto/Algorithm.h
native/src/main/native/org/mozilla/jss/pkcs11/PK11KeyGenerator.c

Solve the validation error on pkcs12 files identified in the bug: 2017098

[v5.3] fix pkcs12

---

base/src/main/java/org/mozilla/jss/CryptoManager.java
base/src/main/java/org/mozilla/jss/crypto/EncryptionAlgorithm.java
base/src/main/java/org/mozilla/jss/crypto/JSSOAEPParameterSpec.java
base/src/main/java/org/mozilla/jss/netscape/security/x509/HoldInstructionExtension.java
base/src/main/java/org/mozilla/jss/pkcs11/PK11KeyWrapper.java
base/src/main/java/org/mozilla/jss/provider/javax/crypto/JSSCipherSpi.java

Following SonarCloud indications some expressions always verify the same so they have been removed of modified

Remove ot modify expression which always evaluate the same

---

base/src/main/java/org/mozilla/jss/netscape/security/util/Cert.java
base/src/main/java/org/mozilla/jss/netscape/security/util/DerOutputStream.java
base/src/main/java/org/mozilla/jss/pkcs11/PK11KeyWrapper.java
base/src/main/java/org/mozilla/jss/pkix/cmmf/PKIStatusInfo.java
base/src/main/java/org/mozilla/jss/pkix/crmf/CertReqMsg.java
base/src/main/java/org/mozilla/jss/provider/java/security/IvAlgorithmParameters.java
base/src/main/java/org/mozilla/jss/provider/java/security/RC2AlgorithmParameters.java

This commit will solve some of the most critical problem identified by SonarCloud. In more details they are:
- buried exceptions: some `finally` clause where thrown exception hiding the exceptions thrown in the try block. The code has been modified so the finally exception is thrown only if the try block has not exception, preserving the order of appearance;
- some conditions where always (or never) verified;
- possible NullPointerException in several points.
This whould also allow the code quality to go from "D" to "C" level.

Fix several issues identified by SonarCloud

---

base/src/main/java/org/mozilla/jss/pkcs12/MacData.java
base/src/main/java/org/mozilla/jss/pkix/primitive/PBKDF2Params.java

For the error see:
https://cov01.lab.eng.brq2.redhat.com/covscanhub/task/269948//log/added.err

Fix potential problem identifid by Covscan

---

base/src/main/java/org/mozilla/jss/provider/javax/crypto/JSSCipherSpi.java
base/src/main/java/org/mozilla/jss/provider/javax/crypto/JSSSecretKeyFactorySpi.java
base/src/main/java/org/mozilla/jss/provider/javax/crypto/JSSTrustManager.java

The change are
- remove some assertions which are already verified in conditions;
- move instance variable to local;
- clean up if else conditions;
- using instanceof with assignment;
- fix signature to java recommendation.

Tidy up some classes in provider crypto package

---

base/src/main/java/org/mozilla/jss/asn1/ASN1Header.java
base/src/main/java/org/mozilla/jss/asn1/BIT_STRING.java
base/src/main/java/org/mozilla/jss/asn1/SEQUENCE.java

Removed some bugs/code smells from the `org.mozilla.jss.asn1` package. These include:
- convert `Vector` to `ArrayList`
- remove or convert to real check some `assert` conditions
There are several layout changes made by eclipse but they are in the javadoc comments.

Clean ASN1 package

---

.github/workflows/pki-tests.yml
.github/workflows/pki-tps-test.yml

A new test has been added to validate TPS token enrollment which will expand the test coverage for JSS symmetric key library.

Add TPS test

---

jss.spec

The `jss.spec` has been modified to build Java code, run Java tests, and build Javadoc with Maven, then build native code and run native tests with CMake.
The old RPM contains the following files:
```
$ rpm -ql dogtag-jss
/usr/lib/.build-id
/usr/lib/.build-id/8a
/usr/lib/.build-id/8a/c9295cbe5748473d70a1ab71dbea346d824e41
/usr/lib/.build-id/ea
/usr/lib/.build-id/ea/46f6226e143c8b469fb161d9c0f18344522f5e
/usr/lib/java/jss.jar
/usr/lib64/jss
/usr/lib64/jss/jss.jar
/usr/lib64/jss/libjss-symkey.so
/usr/lib64/jss/libjss.so
/usr/share/doc/dogtag-jss
/usr/share/doc/dogtag-jss/jss.html
/usr/share/licenses/dogtag-jss
/usr/share/licenses/dogtag-jss/LICENSE
/usr/share/licenses/dogtag-jss/MPL-1.1.txt
/usr/share/licenses/dogtag-jss/gpl.txt
/usr/share/licenses/dogtag-jss/lgpl.txt
```
The new RPM …

Build RPM with Maven

---

.github/workflows/build-tests.yml
README.md
azure-pipelines.yml
base/pom.xml
base/src/test/java/org/mozilla/jss/tests/BMPStringTest.java
base/src/test/java/org/mozilla/jss/tests/CertificateChainTest.java
base/src/test/java/org/mozilla/jss/tests/ChainSortingTest.java
base/src/test/java/org/mozilla/jss/tests/GenericValueConverterTest.java
base/src/test/java/org/mozilla/jss/tests/IA5StringConverterTest.java
base/src/test/java/org/mozilla/jss/tests/IA5StringTest.java
base/src/test/java/org/mozilla/jss/tests/PrintableStringTest.java
base/src/test/java/org/mozilla/jss/tests/TeletexStringTest.java
base/src/test/java/org/mozilla/jss/tests/UTF8StringTest.java
base/src/test/java/org/mozilla/jss/tests/UniversalStringTest.java
cmake/JSSConfig.cmake
cmake/JSSTests.cmake
docs/dependencies.md
jss.spec

All JUnit tests use  `junit5` and `junit4` removed.

Upgdate all junit tests to JUnit5

---

.github/workflows/pki-build-test.yml
.github/workflows/pki-ca-test.yml
.github/workflows/pki-tools-test.yml
.github/workflows/pki-tps-test.yml
jss.spec

The tests have been updated to remove references to Tomcat JSS. The spec file has been updated to remove installed Tomcat JSS packages.

Remove references to Tomcat JSS

---

.github/workflows/tomcat-tests.yml

The test for Tomcat connector with NSS database has been updated to validate the SSL connection using `sslscan`.

Update test for Tomcat connector with NSS database

---

.github/workflows/code-analysis-pull.yml
.github/workflows/code-analysis.yml
pom.xml

The `SONAR_ORGANIZATION` variable has been added to support the use of personal organization for analysis.

Add SONAR_ORGANIZATION

---

CMakeLists.txt
build.sh
docs/changes/v5.6.0/Packaging-Changes.adoc
jss.spec
tools/CMakeLists.txt
tools/src/main/native/sslget/CMakeLists.txt
tools/src/main/native/sslget/getopt.c
tools/src/main/native/sslget/sslget.c

The `sslget` command has been moved from `pki-tools` to `jss-tools`.
https://github.com/edewata/jss/blob/tools/docs/changes/v5.6.0/Packaging-Changes.adoc
**Note:** Some tests are failing due to conflicts with PKI. The tests need to be restarted after [PKI PR #4692](https://github.com/dogtagpki/pki/pull/4692) is merged.

Add sslget

---

.github/workflows/build-tests.yml
CMakeLists.txt
azure-pipelines.yml
build.sh
docs/changes/v5.6.0/Packaging-Changes.adoc
jss.spec
tools/CMakeLists.txt
tools/src/main/native/p12tool/CMakeLists.txt
tools/src/main/native/p12tool/basicutil.c
tools/src/main/native/p12tool/basicutil.h
tools/src/main/native/p12tool/berparse.c
tools/src/main/native/p12tool/derprint.c
tools/src/main/native/p12tool/ffs.c
tools/src/main/native/p12tool/moreoids.c
tools/src/main/native/p12tool/p12tool.c
tools/src/main/native/p12tool/p12tool.h
tools/src/main/native/p12tool/pk11table.c
tools/src/main/native/p12tool/pk11table.h
tools/src/main/native/p12tool/pppolicy.c
tools/src/main/native/p12tool/secpwd.c
tools/src/main/native/p12tool/secutil.c
tools/src/main/native/p12tool/secutil.h
tools/src/main/native/sslget/CMakeLists.txt

The `p12tool` command has been moved from `pki-tools` to `jss-tools`.
https://github.com/edewata/jss/blob/tools/docs/changes/v5.6.0/Packaging-Changes.adoc
**Note:** Some tests are failing due to conflicts. They need to be rerun after merging PKI PR [#4699](https://github.com/dogtagpki/pki/pull/4699).

Add p12tool

---

base/src/main/java/org/mozilla/jss/provider/javax/crypto/JSSTrustManager.java

Previously the `JSSTrustManager` would throw an exception to reject a cert if it found an issue in the cert. The code has been changed to collect all issues, then pass them into an optional callback object. If the callback approves it, the cert will be considered trusted. Otherwise, or if there is no callback, the code will throw an exception based on the first issue.

Add cert approval callback for JSSTrustManager

---

base/src/main/java/org/mozilla/jss/provider/javax/crypto/JSSTrustManager.java

If the certificate is a trusted peer there is not check of the issuer and/or the certificate.
If the issuer is not available, or it is a trusted peer, the revocation is not verified because it cannot verify the full chain in any case. The issue is already reported.

JSSTrustManager check revokation  only if trusted issuer

---

base/src/main/java/org/mozilla/jss/ssl/javax/JSSSocketChannel.java

JSSSocket can be used with blocking and non blocking channel. When used with blocking channel the write has to send all data in a single request but if the sending buffer is full only that is sent and the remaining data will be send in following write operations.
This commit fix the write adding consecutive operations if the buffer is full in order to send all application data.
As en example of the problem, if JSSSocket is used in the pki CLI, which uses blocking channels, some command with large input send only a partial amount of data and the server will timeout waiting for the remaining (this is visible in [this test](https://github.com/fmarco76/pki/actions/runs/13791116504/job/38571769253)).

Fix write problem with blocking channel

---

jss.spec
tomcat-10.1/pom.xml

Now we require tomcat version >= 10.1.43.

Adjust reuqirements for the latest tomcat-10.1.43 version.
